added help page
fylein/fyle-mobile-app2 pull request #22
Opened 2020-09-30 12:20 UTC by madhavmansuriya40

![Screenshot 2020-09-30 at 5 41 20 PM](https://user-images.githubusercontent.com/51825933/94684211-5c3c1400-0345-11eb-8090-8e3648181664.png)
![Screenshot 2020-09-30 at 5 41 09 PM](https://user-images.githubusercontent.com/51825933/94684220-5f370480-0345-11eb-8fcc-8ca38972f8fd.png)
![Screenshot 2020-09-30 at 5 49 16 PM](https://user-images.githubusercontent.com/51825933/94684224-5fcf9b00-0345-11eb-995d-7cc4ff94337b.png)
![Screenshot 2020-09-30 at 5 49 04 PM](https://user-images.githubusercontent.com/51825933/94684225-60683180-0345-11eb-9b93-8593f2a23416.png)
![Screenshot 2020-09-30 at 5 41 47 PM](https://user-images.githubusercontent.com/51825933/94684227-60683180-0345-11eb-900c-aedeea21b4e7.png)
![Screenshot 2020-09-30 at 5 41 29 PM](https://user-images.githubusercontent.com/51825933/94684230-6100c800-0345-11eb-9500-e67acc32cd02.png)

2020-10-01 06:46 UTC, Julias0 commented on src/app/core/services/extended-org-users.service.ts
> +export class ExtendedOrgUsersService {
These methods already exist inside `OrgUserService`
Remove this file and use those

2020-10-01 06:47 UTC, Julias0 commented on src/app/core/services/org-user.service.ts
> +    private authService: AuthService,
why @madhavmansuriya40 why

2020-10-01 06:47 UTC, Julias0 commented on src/app/fyle/help/help.page.html
> +  <ion-toolbar class="header-container">
help-content--header-container

2020-10-01 06:47 UTC, Julias0 commented on src/app/fyle/help/help.page.html
> +      <button (click)="openHelpLink()" mat-flat-button class="help-content--helper-buttons--btn-help">Explore Knowledge
this is not proper BEM

2020-10-01 06:48 UTC, Julias0 commented on src/app/fyle/help/help.page.scss
> +$brand-secondary-primary: #220033;
spacing should be 2 spaces - and use proper BEM

You cant have nested elements in BEM

refer to the other pages

2020-10-01 06:48 UTC, Julias0 commented on src/app/fyle/help/help.page.scss
> +				text-overflow: ellipsis;
use ellipses pipe instead of this

2020-10-01 06:49 UTC, Julias0 commented on src/app/fyle/help/help.page.scss
> +				height: 20px;
use only max and min height/ width

2020-10-01 06:49 UTC, Julias0 commented on src/app/fyle/help/help.page.ts
> +    const loading = await this.loadingController.create({
use loaderService

2020-10-01 06:50 UTC, Julias0 commented on src/app/fyle/help/help.page.ts
> +    this.presentLoading();
this approach is incorrect - use loader service - refer to how other pages have used it

2020-10-01 06:50 UTC, Julias0 commented on src/app/fyle/help/help.page.ts
> +      orgAdmins = user.filter(user =>
do this inside the pipe with map

2020-10-01 06:51 UTC, Julias0 commented on src/app/fyle/help/help.page.ts
> +      this.loadingController.dismiss();
loaderService

2020-10-01 06:52 UTC, Julias0 commented on src/app/fyle/help/help.page.ts
> +    this.presentSupportModal('log_mileage', '');
why is the second argument an empty string?

2020-10-01 06:52 UTC, Julias0 commented on src/app/fyle/help/help.page.ts
> +    this.presentSupportModal('capture_email', '');
why is the second argument an empty string?

2020-10-01 06:52 UTC, Julias0 commented on src/app/fyle/help/help.page.ts
> +    this.presentSupportModal('goibibo_support', '');
why is the second argument an empty string?

2020-10-01 06:52 UTC, Julias0 commented on src/app/fyle/help/support-dialog/support-dialog.page.html
> +  <!-- contact support dialog -->
remove all comments

2020-10-01 06:53 UTC, Julias0 commented on src/app/fyle/help/support-dialog/support-dialog.page.html
> +    <ion-buttons slot="end" style="display: block">
no inline styling

2020-10-01 06:53 UTC, Julias0 commented on src/app/fyle/help/support-dialog/support-dialog.page.html
> +      <div class="contact-support--content--admin-list">
use proper BEM

2020-10-01 06:53 UTC, Julias0 commented on src/app/fyle/help/support-dialog/support-dialog.page.scss
> +			height: 50px;
arrey indentation :(

2020-10-01 06:54 UTC, Julias0 commented on src/app/fyle/help/support-dialog/support-dialog.page.scss
> +      background-color: #f1f1f1;
colors in variables everywhere please

2020-10-01 06:55 UTC, Julias0 requested changes
Fix and ping back

2020-10-05 10:00 UTC, madhavmansuriya40 commented on src/app/fyle/help/help.page.scss
> +$brand-secondary-primary: #220033;
indentations are correct in code, problem here (can ignore)

2020-10-05 11:45 UTC, Julias0 approved these changes

2020-10-06 13:55 UTC, closed without merging