remove signup flow
fylein/fyle-mobile-app2 pull request #260
Opened 2021-02-18 04:28 UTC by madhavmansuriya40

2021-02-18 05:12 UTC, Julias0 commented on src/app/core/services/tracking.service.ts
> -  onSignin(email, properties) {
why remove onSignin?

2021-02-18 05:26 UTC, Julias0 requested changes
Few comments in tracking service. Add a loom video on what happens when app starts up when not logged in and when logged in

2021-02-18 05:28 UTC, madhavmansuriya40 commented on src/app/core/services/tracking.service.ts
> -  onSignin(email, properties) {
by mistake i have done that, but later i added

2021-02-18 05:36 UTC, madhavmansuriya40 commented
here's loom video link

https://www.loom.com/share/808480ea66de486a9ab49ca4e569c113

2021-02-18 11:10 UTC, Julias0 commented on src/app/core/services/tracking.service.ts
> -  eventTrack(action, properties) {
why remove this?

2021-02-18 11:10 UTC, Julias0 commented on src/app/core/services/tracking.service.ts
> -  onStateChange(toState, toParams, fromState, fromParams) {
confirm once that this is not being used

2021-02-18 11:11 UTC, Julias0 requested changes
illa illa

2021-02-25 16:51 UTC, abhishek1234321 approved these changes

2021-02-25 16:51 UTC, abhishek1234321 commented on src/app/auth/sign-in/sign-in.page.html
> +      <a href="https://www.fylehq.com/"> Sign Up</a>
do we need `target="_blank"`?

2021-02-26 04:38 UTC, closed without merging