Profile Settings Cleanup [Mobile-app changes]
fylein/fyle-mobile-app2 pull request #266
Opened 2021-02-19 10:37 UTC by jatzz10

2021-02-22 08:48 UTC, jatzz10 commented on src/app/auth/switch-org/switch-org.page.html
> +      Select an account to switch to it
Sai's comment -> Change this to 'Select an organization to switch to it'

2021-02-22 15:48 UTC, jatzz10 commented on src/app/auth/switch-org/switch-org.page.html
> +      Select an account to switch to it
this is done

2021-02-23 10:42 UTC, khnamrata commented on src/app/fyle/my-profile/my-profile.page.html
> +            <div class="my-profile--card-title__using-fyle">
is this ok? "card-title__using-fyle"

2021-02-23 10:58 UTC, jatzz10 commented on src/app/fyle/my-profile/my-profile.page.html
> +            <div class="my-profile--card-title__using-fyle">
This is an existing div. I have just rearranged the order of few divs in this html file. And yes, this is ok. In **my-profile.page.scss** file, we have few of these classes following the same naming rule.

```
&--card-title {
    font-size: 16px;
    font-weight: 500;
    color: #4a4a4a;

    &__using-fyle {
      margin-bottom: 16px;
    }

    &__lite {
      color: #ababab;
    }
  }
```

2021-02-23 16:41 UTC, khnamrata commented on src/app/fyle/delegated-accounts/delegated-accounts.page.html
> +      Select an account to switch to it
shouldn't it be "Select an account to switch to"

2021-02-23 16:44 UTC, khnamrata approved these changes

2021-02-23 16:49 UTC, jatzz10 commented on src/app/fyle/delegated-accounts/delegated-accounts.page.html
> +      Select an account to switch to it
Yeah, this content was given by Sai only. Will check again with him regarding this.

2021-02-23 17:37 UTC, jatzz10 commented on src/app/fyle/ccc-classify-actions/ccc-classify-actions.page.html
>      </div>
Found this typo. Have fixed this bug:
![Screenshot 2021-02-23 at 10 58 40 PM](https://user-images.githubusercontent.com/41716010/108883736-d4281500-762b-11eb-89e3-157632775607.png)

2021-02-23 17:37 UTC, jatzz10 commented on src/app/fyle/ccc-classify-actions/ccc-classify-actions.page.ts
> +        text: 'Classify as Personal'
Same comment as above

2021-02-24 14:29 UTC, madhavmansuriya40 commented on src/app/app.component.html
> +                <div *ngIf="sideMenuItem.title === 'Advances' && (allowedActions?.allowedReportsActions?.approve || allowedActions?.allowedAdvancesActions?.approve)" class="sidemenu--divider"></div>
what if the advance is disabled from org will this condition still work?

2021-02-24 14:29 UTC, madhavmansuriya40 commented on src/app/app.component.ts
> +            title: 'Switch back to my account',
please test if the text overflow is working properly

2021-02-24 14:29 UTC, madhavmansuriya40 commented on src/app/fyle/delegated-accounts/delegated-accounts.page.html
> +      Select an account to switch to it
please confirm and update here, if this is ok

2021-02-24 14:29 UTC, madhavmansuriya40 commented on src/app/app.component.ts
> +            title: 'Settings',
isn't it difficult to imagine log out under the settings tab? 😅 

if it is intentionally done, its ok

2021-02-24 14:45 UTC, jatzz10 commented on src/app/app.component.ts
> +            title: 'Settings',
Yeah, this is intentional.

2021-02-24 15:49 UTC, madhavmansuriya40 approved these changes
please resolve the comments, the rest looks good to me

2021-02-24 16:04 UTC, jatzz10 commented on src/app/fyle/delegated-accounts/delegated-accounts.page.html
> +      Select an account to switch to it
This has been changed to `Select the account you wish to manage` - discussed with Sai.

2021-02-24 16:05 UTC, jatzz10 commented on src/app/app.component.html
> +                <div *ngIf="sideMenuItem.title === 'Advances' && (allowedActions?.allowedReportsActions?.approve || allowedActions?.allowedAdvancesActions?.approve)" class="sidemenu--divider"></div>
This has been resolved thanks to @madhavmansuriya40 :)

2021-02-24 16:05 UTC, jatzz10 commented on src/app/app.component.ts
> +            title: 'Switch back to my account',
Already checked. Not overflowing.

2021-02-24 16:08 UTC, jatzz10 commented on src/app/app.component.ts
> -          },
Haven't removed anything here. Just have changed the order. Advances has been placed under Trips in the sidenav now.

2021-02-24 16:11 UTC, jatzz10 commented on src/app/app.component.ts
> -            route: ['/', 'enterprise', 'my_profile']
This is the new order of sidenav items:
- Dashboard
- Expenses
- Cards
- Reports
- Trips
- Advances
-------------
- Team Reports
- Team Trips
- Team Advances

- Live Chat
- Settings
- My Organizations
- Delegated Accounts
- Help

2021-02-25 03:30 UTC, jatzz10 commented on src/app/app.component.html
> +                <div *ngIf="sideMenuItem.title === dividerTitle && (allowedActions?.allowedReportsActions?.approve || allowedActions?.allowedAdvancesActions?.approve)" class="sidemenu--divider"></div
To understand this change, please refer to the code from file **src/app/app.component.ts** from line no. **459** to **470**.

2021-02-25 05:21 UTC, iamtarun1993 commented on src/app/app.component.ts
> +            icon: 'fy-settings-o',
why file name is "fy-settings-o" not "fy-settings" ??

2021-02-25 05:25 UTC, iamtarun1993 commented on src/app/shared/components/delegated-acc-message/delegated-acc-message.component.html
> +  You're now managing {{ delegateeName | ellipsis: 20 }}'s account
Here content size is increased, please check ellipsis 20 is ok or should we need to reduce it.
Please check this on iPhone 5 in browser

2021-02-25 05:29 UTC, iamtarun1993 commented on src/app/fyle/my-profile/my-profile.page.html
> -            Please login to the web application at <a (click)="openWebAppLink('app')">{{ROUTER_API_ENDPOINT}}</a> to change mileage settings.
Are we removing this block fully from the mobile app??

2021-02-25 07:45 UTC, jatzz10 commented on src/app/shared/components/delegated-acc-message/delegated-acc-message.component.html
> +  You're now managing {{ delegateeName | ellipsis: 20 }}'s account
Right, I have reduced the `ellipsis` from **20** to **15** and tested for iPhone5 in browser.
Here is the comparison:
- With `ellipsis: 20`:
   
   ![Screenshot 2021-02-25 at 1 11 41 PM](https://user-images.githubusercontent.com/41716010/109120017-6edb3d80-776b-11eb-959c-b0894bd3b5c0.png)

- With `ellipsis: 15`:

   ![Screenshot 2021-02-25 at 1 08 33 PM](https://user-images.githubusercontent.com/41716010/109120079-7f8bb380-776b-11eb-8213-cc9731f15761.png)

2021-02-25 07:48 UTC, jatzz10 commented on src/app/fyle/my-profile/my-profile.page.html
> -            Please login to the web application at <a (click)="openWebAppLink('app')">{{ROUTER_API_ENDPOINT}}</a> to change mileage settings.
Yes sir, this is intentional.

2021-02-25 09:39 UTC, jatzz10 commented on src/app/app.component.ts
> +      }
![Screenshot 2021-02-25 at 3 09 15 PM](https://user-images.githubusercontent.com/41716010/109133884-760a4780-777b-11eb-8170-d45a75b16703.png)

2021-02-25 16:46 UTC, abhishek1234321 requested changes

2021-02-25 16:46 UTC, abhishek1234321 commented on src/app/auth/switch-org/switch-org.page.html
> +      Select an Organization to switch to it
`Select an Organization to switch to` might be better no? `to it` sounds a little odd

2021-02-25 16:46 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.html
> +            Emp. ID
what is this?

2021-02-25 16:46 UTC, abhishek1234321 commented on src/app/shared/components/delegated-acc-message/delegated-acc-message.component.html
> +  You're now managing {{ delegateeName | ellipsis: 15 }}'s account
why change it to 15?

2021-03-02 12:53 UTC, jatzz10 commented on src/app/fyle/my-profile/my-profile.page.html
> +            Emp. ID
Employee Id

2021-03-02 12:55 UTC, jatzz10 commented on src/app/app.component.ts
> +            title: 'My Organizations',
This has been discussed

2021-03-02 12:55 UTC, jatzz10 commented on src/app/auth/switch-org/switch-org.page.html
> +      Select an Organization to switch to it
This has been discussed

2021-03-02 13:42 UTC, jatzz10 commented on src/app/shared/components/delegated-acc-message/delegated-acc-message.component.html
> +  You're now managing {{ delegateeName | ellipsis: 15 }}'s account
Tarun suggested to reduce it a bit in his comment [here](https://github.com/fylein/fyle-mobile-app2/pull/266#discussion_r582554325)

2021-03-02 13:57 UTC, jatzz10 commented on src/app/app.component.ts
> +            title: 'Advances',
Yes, sir. It is intentional. This is how this if-else block has been coded before.
```
 if (isConnected) {
   this.sideMenuList = [
     { ..... },
     { ..... },
     ....
 } else {
   this.sideMenuList = [
     { ..... },
     { ..... },
     ....
 }
```

2021-03-02 13:58 UTC, jatzz10 commented on src/app/app.component.ts
> +            title: 'My Organizations',
Same comment as [this](https://github.com/fylein/fyle-mobile-app2/pull/266/files#r585585128)

2021-03-02 16:22 UTC, abhishek1234321 approved these changes

2021-03-02 16:22 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.html
> +            Emp. ID
if we have enough space please change it to Employee ID, if not ignore

2021-03-05 08:11 UTC, merged