Changes to make offline expenses deletable
fylein/fyle-mobile-app2 pull request #269
Opened 2021-02-22 14:42 UTC by lakshmisuhas1996

2021-02-24 11:19 UTC, iamtarun1993 commented
can you put some screenshot or loom video over here?? @lakshmisuhas1996

2021-02-24 11:25 UTC, lakshmisuhas1996 commented
Loom video - https://www.loom.com/share/e6cad922141c4b00b4a526fb75241352 @iamtarun1993

2021-02-24 12:05 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +  async onDeleteOfflineExpenseClick(etxn: Expense, index) {
do we need another method to delete offline expenses?
can we not decide based on tx_id is present or not?
if id present make API call, if not present just remove from transactionOutboxService queue.
can you check this?

2021-02-24 12:07 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses-card/my-expenses-card.component.html
> +      <div class="my-expenses-card-menu--buttons" *ngIf="canDeleteOfflineExpense">
what will happen if the expense in sync mode?
i.e the user just came online and the expense start syncing to the server. You can slow the network speed and check what is happening here?

2021-02-24 12:09 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses-card/my-expenses-card.component.html
> +      <div class="my-expenses-card-menu--buttons" *ngIf="canDeleteOfflineExpense">
create 4-5 expense and start syncing and then delete any offline expense, if possible do with images/pdf with all-expense.. it will take more time to sync and give you time to repro.

2021-02-26 09:54 UTC, lakshmisuhas1996 commented on src/app/fyle/my-expenses/my-expenses-card/my-expenses-card.component.html
> +      <div class="my-expenses-card-menu--buttons" *ngIf="canDeleteOfflineExpense">
have made changes to not show options icon in expense card when sync is going on...

2021-02-26 10:39 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +          if (!etxn.tx_id) {
Use `iif()` not if else

2021-02-26 10:42 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +          if (!etxn.tx_id) {
Looks like this will break. deleteOfflineExpense method is a void/promise method but delete() is an observable method.

can you check this once??

2021-03-01 09:49 UTC, iamtarun1993 approved these changes

2021-03-01 16:58 UTC, abhishek1234321 requested changes

2021-03-01 16:58 UTC, abhishek1234321 commented on src/app/core/services/transactions-outbox.service.ts
> +    return null;
is returning absolutely required? by default the method will return null or undefined no?

2021-03-01 16:58 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses.page.html
> +                          [isSyncInProgress]="syncing">
isn't `isSyncInProgress` supposed to be a boolean and you are passing a string?

2021-03-01 16:58 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +  async onDeleteExpenseClick(etxn: Expense, index?: number) {
why is `index` optional?

2021-03-02 04:35 UTC, lakshmisuhas1996 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +  async onDeleteExpenseClick(etxn: Expense, index?: number) {
SInce we are using the same method to delete normal and offline expenses, we will pass only etxn for normal txns and etxn and index for txns created in offline mode. And delete them based on tx_id prop... so made index as optional param...

2021-03-02 04:37 UTC, lakshmisuhas1996 commented on src/app/fyle/my-expenses/my-expenses.page.html
> +                          [isSyncInProgress]="syncing">
no, the property **syncing** holds boolean value only - whether the transactions are in syncing or not

2021-03-02 04:58 UTC, lakshmisuhas1996 commented on src/app/core/services/transactions-outbox.service.ts
> +    return null;
By default, the return type of function will be Void and it will return undefined. so we are returning null to observable?

2021-03-02 05:31 UTC, abhishek1234321 approved these changes

2021-03-02 05:31 UTC, abhishek1234321 commented on src/app/core/services/transactions-outbox.service.ts
> +    return null;
ok great

2021-03-02 08:10 UTC, merged