Changed date format to MMM dd YYYY for all date fields across app
fylein/fyle-mobile-app2 pull request #274
Opened 2021-02-24 07:37 UTC by lakshmisuhas1996

2021-03-06 03:54 UTC, madhavmansuriya40 commented
can you please add few screenshots, please?

2021-03-08 05:06 UTC, lakshmisuhas1996 commented
**On cards, headers, Card details etc., Except Input fields**

1. Date format on top of cards

![Screen_Shot_2021-03-02_at_10 55 08_AM](https://user-images.githubusercontent.com/79460986/110275467-1c194580-7ff7-11eb-80c9-a67da2be8cdc.png)
2. Inside Card details pages
![Screen_Shot_2021-03-02_at_11 32 48_AM (1)](https://user-images.githubusercontent.com/79460986/110275688-8d58f880-7ff7-11eb-8869-5f7545a351b9.png)
3. On My profile page
![Screen_Shot_2021-03-02_at_11 46 48_AM (1)](https://user-images.githubusercontent.com/79460986/110275782-c09b8780-7ff7-11eb-9f6a-402e14191ddb.png)
4. On view pages like View expense, View Per diem
![Screen_Shot_2021-03-02_at_12 05 52_PM](https://user-images.githubusercontent.com/79460986/110276365-fd1bb300-7ff8-11eb-9785-ebfe318cb4d4.png)

**On Input Fields**
1. WIth date field filled in
![Screen Shot 2021-03-08 at 10 08 12 AM](https://user-images.githubusercontent.com/79460986/110276533-508e0100-7ff9-11eb-8bd3-ad884adf4e67.png)
2. Without date 
![Screen Shot 2021-03-08 at 10 31 46 AM](https://user-images.githubusercontent.com/79460986/110276827-05c0b900-7ffa-11eb-902f-9a263c34fe01.png)

2021-03-08 06:12 UTC, madhavmansuriya40 commented on src/app/shared/directive/format-date.directive.ts
> +  @Input() dateFormat = "MMM DD, YYYY";
as per the code, we are not taking input for `dateFormat` anywhere
so it should not be `@Input() dateFormat = "MMM DD, YYYY";` -> `@input`

you can declare it as a string directly, after all its a static value

it should be `dateFormat = "MMM DD, YYYY";`

2021-03-08 06:15 UTC, madhavmansuriya40 approved these changes

2021-03-08 06:25 UTC, lakshmisuhas1996 commented on src/app/shared/directive/format-date.directive.ts
> +  @Input() dateFormat = "MMM DD, YYYY";
SInce we show same date format for all date input fields and setting dateFormat value to default value here.... so that if we would like to change the format for some field we can pass dateFormat with different value

2021-03-08 06:31 UTC, lakshmisuhas1996 commented on src/app/fyle/corporate-card-expenses/corporate-card-expense-card/corporate-card-expense-card.component.html
> +      {{corporateCardExpense.txn_dt | date: 'EEEE, MMMM dd, yyyy'}}
Okay, have not formatted this field because it is an existing format that we show on top of card headers only. WIll defer to @abhishek1234321 @tarunkumarfyle

2021-03-08 11:39 UTC, iamtarun1993 commented
why two calendar icons are present in the image ???

2021-03-08 11:56 UTC, iamtarun1993 commented on src/global.scss
> +  &::-webkit-datetime-edit, &::-webkit-inner-spin-button, &::-webkit-clear-button {
why these things are needed??
if you got this from any StackOverflow or blog can you mention this here??

2021-03-09 12:10 UTC, lakshmisuhas1996 commented on src/global.scss
> +  &::-webkit-datetime-edit, &::-webkit-inner-spin-button, &::-webkit-clear-button {
added reference link

2021-03-10 06:28 UTC, lakshmisuhas1996 commented on src/app/shared/directive/format-date.directive.ts
> +  @Input() dateFormat = "MMM DD, YYYY";
Okay, removing dateFormat input and will use the value directly.

2021-03-10 07:06 UTC, iamtarun1993 commented on src/app/fyle/my-add-edit-trip/my-add-edit-trip.page.html
> +                    <input appFormatDate [dateValue]="control['controls'].onward_dt.value" (keydown)="$event.preventDefault()" [max]="fg.controls.endDate.value" [min]="fg.controls.startDate.value" cl
@madhavmansuriya40 @abhishek1234321 @Julias0 is this format ok??

2021-03-10 07:09 UTC, iamtarun1993 requested changes
please check `control['controls']` thingy.. this fix doesn't LGTM.

2021-03-11 09:27 UTC, iamtarun1993 commented on src/app/fyle/my-add-edit-trip/my-add-edit-trip.page.html
> +                    <input appFormatDate [dateValue]="control.controls.onward_dt.value" (keydown)="$event.preventDefault()" [max]="fg.controls.endDate.value" [min]="i === 0 ? fg.controls.startDate.va
this format LGTM. just make sure `control.controls.onward_dt` should not become null in any case.

2021-03-11 09:28 UTC, iamtarun1993 approved these changes

2021-03-15 06:14 UTC, Julias0 commented on src/global.scss
> +.input-date-format {
please make sure that class names follow the BEM format

2021-03-15 06:21 UTC, Julias0 commented on src/app/shared/directive/format-date.directive.ts
> +      this.elementRef.nativeElement.setAttribute("data-date", moment(this.dateValue).format('MMM DD, YYYY'));
no `"` in ts file please

2021-03-15 07:33 UTC, Julias0 commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
> +                  <input appFormatDate [dateValue]="customInput.control.value.value" class="add-edit-advance-request--date-input input-date-format" *ngIf="customInput.type === 'DATE'" type="date" for
There are two problems with this approach
 - The tag already contains the formControl. Passing it again for the directive opens up scope for bugs to come up
 - Directives are too flexbile for this use case since we would be using the same date picker everywhere. Directives are to extend features of an existing html tag but since we are using this everywhere a component makes more sense. Check fy select on how ControlValueAccessor is used

2021-03-22 10:03 UTC, Julias0 commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
> +                  <input appFormatDate class="add-edit-advance-request--date-input input-date-format" *ngIf="customInput.type === 'DATE'" type="date" formControlName="value">
rename `input-date-format` to `date-input__format`

2021-03-22 10:04 UTC, Julias0 approved these changes

2021-03-25 04:27 UTC, abhishek1234321 approved these changes

2021-04-04 19:05 UTC, merged