Changes for replacing series of /v2/expenses api call with one stats api call from profile page
fylein/fyle-mobile-app2 pull request #275
Opened 2021-02-24 07:57 UTC by lakshmisuhas1996

2021-02-24 11:30 UTC, iamtarun1993 commented on src/app/fyle/my-profile/my-profile.page.ts
> +      total: totalCount,
do we need `total:` if we haven't used this... we can remove this

2021-02-24 11:43 UTC, lakshmisuhas1996 commented on src/app/fyle/my-profile/my-profile.page.ts
> +      total: totalCount,
This is sorted

2021-02-24 11:51 UTC, iamtarun1993 approved these changes

2021-02-25 04:42 UTC, abhishek1234321 requested changes

2021-02-25 04:42 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.ts
> +  getMyexpensesStatsCountBySourceMap(stats, source) {
what does `BySourceMap` mean?

2021-02-25 04:42 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.ts
> +  getMyexpensesStatsCountBySourceMap(stats, source) {
@Julias0 shouldn't we be specifying type of stats and source? if we do not how will typescript help us catch bugs @lakshmisuhas1996

2021-02-25 04:42 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    let count = stats.filter(stat => stat.key.toLowerCase().indexOf(source.toLowerCase()) > -1);
shouldn't this be `const`?

2021-02-25 04:42 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.ts
> +  getMyexpensesStatsCountBySourceMap(stats, source) {
please explain in code comments about what is happening in this method?

2021-02-25 04:42 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    return count && count.reduce((acc, obj) => acc + obj.value, 0);
count will always be an `[]` no? so why do we need to do `count && count.`?

2021-02-25 04:42 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.ts
> +  setMyExpensesCountBySource(stats) {
model for `stats`?

2021-02-25 04:42 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    const statsCountList = stats && stats[0].value.map(stat =>  {
we shouldn't be doing `stats && stats[0]` the whole point of typescript is to avoid doing things like these, I presume `stats` will always be an array, please define the required model and clean things up? also shouldn't we be checking for `stats.length > 0`? @Julias0 @lakshmisuhas1996 @tarunkumarfyle

2021-02-25 04:42 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.ts
> +        value: stat.aggregates[0].function_value,
can aggregates ever be empty?

2021-02-25 04:42 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.ts
> +        key: stat.key[0].column_value
can key ever be empty?

2021-02-25 04:42 UTC, abhishek1234321 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    const totalCount = statsCountList.reduce((acc, obj) => acc + obj.value, 0);
instead of `obj` please use a more readable variable name?

2021-02-25 04:51 UTC, Julias0 commented on src/app/fyle/my-profile/my-profile.page.ts
> +  getMyexpensesStatsCountBySourceMap(stats, source) {
Yes.

The return type can be skipped in case the value getting returned already has a type set to it.
Ex - 

getEtxn(id: string) {
   return this.apiService.get('/transaction', { id: id }).pipe(
     map(txn => {
        return txn as Transaction;
     })
   )
}

Here typescript would be able to understand the return type of Observable<Transaction>.
But having it explicitly done would be much better

2021-02-25 04:58 UTC, Julias0 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    const statsCountList = stats && stats[0].value.map(stat =>  {
Yes, ideally the stats model should have a method to retrieve this.
But can't be avoided inside the model since the API return this in this format - properties which are nullable should be marked with ? in the model to have typescript call these out as being optional parameters.

We can enclose these things inside the model itself in the following way - 

ex - 

export class Stats {
  // properties returned by stats here
  
  getStatValue(){
    return this.stats && stats[0] && // etc or use .find to get the relevant stat
  }
}

2021-02-25 06:41 UTC, lakshmisuhas1996 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    let count = stats.filter(stat => stat.key.toLowerCase().indexOf(source.toLowerCase()) > -1);
yes changing it

2021-02-25 06:42 UTC, lakshmisuhas1996 commented on src/app/fyle/my-profile/my-profile.page.ts
> +  getMyexpensesStatsCountBySourceMap(stats, source) {
it should be source only not map

2021-02-25 10:16 UTC, abhishek1234321 approved these changes

2021-02-25 11:33 UTC, Julias0 commented on src/app/core/models/stats-one-dimension.model.ts
> +export interface StatsOneDResponse {
add a ? to the params which can be null
Ex - 
export class Person {
  name: string;
  age?: number;
}

? here means the property is nullable

https://stackoverflow.com/questions/17220114/how-to-declare-a-type-as-nullable-in-typescript

2021-02-25 11:34 UTC, Julias0 commented on src/app/core/models/stats-one-dimension.model.ts
> +export interface StatsOneDResponse {
Why name this StatsOneResponse?
I mean why is the One there?

2021-02-25 11:37 UTC, Julias0 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    const statsCountList = statsRes.value.map(stat =>  {
add it as a method inside the model, then call it here - 

Ex - 
`export class StatsReponse{
  getAggregate(index: number) {
    return this.value.map(stat =>  {
        value: stat.aggregates.length && stat.aggregates[0].function_value,
        key: stat.key.length && stat.key[0].column_value  
    });
  }
}`

Then over here - 
`statsRes.getAggregate(0);`

2021-02-25 11:39 UTC, Julias0 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    return filteresStatsRes.reduce((acc, statValue) => acc + statValue.value, 0);
This should be a method of the stat model.

2021-02-25 11:40 UTC, Julias0 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    const filteresStatsRes = stats.filter(stat => stat.key.toLowerCase().indexOf(source.toLowerCase()) > -1);
`stat.key.toLowerCase().indexOf(source.toLowerCase()) > -1`
This should be a method inside stats

2021-02-25 11:42 UTC, Julias0 requested changes
Comments given on requested changes

2021-02-26 05:18 UTC, lakshmisuhas1996 commented on src/app/core/models/stats-one-dimension.model.ts
> +export interface StatsOneDResponse {
Named it OneD because the stats res is of type one dimension (stats terminology) and the response structure changes from dimension to dimension. I mean it will be different from 0D and 2D and so on? @Julias0

2021-02-27 07:21 UTC, Julias0 commented on src/app/core/models/stats-one-dimension.model.ts
> +export interface StatsOneDResponse {
You mean the schema changes when we go from one dimension to multiple dimensions?

2021-03-02 07:29 UTC, lakshmisuhas1996 commented on src/app/core/models/stats-one-dimension.model.ts
> +export interface StatsOneDResponse {
Yes

2021-03-03 06:15 UTC, Julias0 commented on src/app/core/models/stats-one-dimension.model.ts
> +  public static getStatsCountBySource(stats: {value: number; key: string}[], source: string) {
dont pass in stats externally.
```
public static getStatsCountBySource(source: string, index = 0) {
  const stats = this.getStatAggregatesByIdx<number>(index);
  const filteresStatsRes = stats.filter(stat => stat.key.toLowerCase().indexOf(source.toLowerCase()) > -1);
  return filteresStatsRes.reduce((acc, statValue) => acc + statValue.value, 0);
}
```

2021-03-03 06:16 UTC, Julias0 commented on src/app/core/models/stats-one-dimension.model.ts
> +
getStatsTotalCount(index = 0){
  const stats = this.getStatAggregatesByIdx<number>(index);
  return stats.reduce((acc, statValue) => acc + statValue.value, 0);
}

2021-03-03 06:17 UTC, Julias0 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    const totalCount = statsCountList.reduce((acc, statValue) => acc + statValue.value, 0);
Notice that you dont need statsCountList externally.
You can make it part of the model only

2021-03-05 13:04 UTC, Julias0 approved these changes

2021-03-05 13:05 UTC, Julias0 approved these changes

2021-03-08 05:31 UTC, Julias0 approved these changes

2021-03-08 13:12 UTC, merged