initial commit for shifting travel agent call to v2
fylein/fyle-mobile-app2 pull request #277
Opened 2021-02-24 08:35 UTC by madhavmansuriya40

2021-03-03 09:22 UTC, iamtarun1993 commented on src/app/core/interceptors/httpInterceptor.ts
> +            const params = new HttpParams({encoder: new CustomEncoder(), fromString: request.params.toString()});
put ref here @madhavmansuriya40

2021-03-03 09:23 UTC, iamtarun1993 commented on src/app/core/services/api-v2.service.ts
> +import { map } from 'rxjs/operators';
remove this sir... if not needed

2021-03-03 09:27 UTC, iamtarun1993 commented on src/app/core/services/org-user.service.ts
> +      or: '(ou_status.like.*"ACTIVE",ou_status.like.*"PENDING_DETAILS")'
can we use `.in` operator instead of `.like`??

2021-03-03 09:28 UTC, iamtarun1993 commented on src/app/core/services/org-user.service.ts
> +        const count = res.count > 200 ? res.count / 200 : 1;
we are getting 200 employees at a time... are not decided to get 20?

2021-03-03 09:31 UTC, iamtarun1993 commented on src/app/shared/components/fy-modify-approver/modify-approver-dialog/modify-approver-dialog.component.ts
> +      return !this.intialSelectedApprovers.find(x => x === approver);
no `x` please.. use the proper variable name.

2021-03-03 09:32 UTC, iamtarun1993 commented on src/app/shared/components/fy-modify-approver/modify-approver-dialog/modify-approver-dialog.component.ts
> +      return !this.approverList.find(x => x === approver);
same as above

2021-03-03 09:38 UTC, iamtarun1993 commented on src/app/shared/components/fy-modify-approver/modify-approver-dialog/modify-approver-dialog.component.ts
> +      params.us_email = 'ilike.*' + searchText + '*';
can you use TS6 string manipulation ?? like " `$ "

2021-03-03 09:41 UTC, iamtarun1993 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +      params.us_email = 'in.(' + this.currentSelections.join(',') + ')';
us TS6 string manipulation

2021-03-03 09:43 UTC, iamtarun1993 commented on src/app/shared/components/fy-userlist/fy-userlist.component.ts
> +        // options: this.options,
remove this if this is not needed

2021-03-03 09:48 UTC, madhavmansuriya40 commented on src/app/core/interceptors/httpInterceptor.ts
> +            const params = new HttpParams({encoder: new CustomEncoder(), fromString: request.params.toString()});
will remove this we have different PR for this

2021-03-03 09:50 UTC, madhavmansuriya40 commented on src/app/core/services/org-user.service.ts
> +      or: '(ou_status.like.*"ACTIVE",ou_status.like.*"PENDING_DETAILS")'
i will check this, if we can user .in
as far as i remember we store this as "ACTIVE" that is quoted string

2021-03-03 09:55 UTC, madhavmansuriya40 commented on src/app/core/services/org-user.service.ts
> +        const count = res.count > 200 ? res.count / 200 : 1;
if we don't send count it will take 200 by default
we will send 20 from respected page

2021-03-03 09:56 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-modify-approver/modify-approver-dialog/modify-approver-dialog.component.ts
> +      return !this.intialSelectedApprovers.find(x => x === approver);
will change it to selected approver

2021-03-03 09:56 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-modify-approver/modify-approver-dialog/modify-approver-dialog.component.ts
> +      params.us_email = 'ilike.*' + searchText + '*';
ok sure will update this

2021-03-08 06:02 UTC, iamtarun1993 commented on src/app/core/services/org-user.service.ts
> +  getEmployees(params) {
please mention the return object also here

2021-03-08 06:03 UTC, iamtarun1993 commented on src/app/core/services/org-user.service.ts
> +  getEmployeesBySearch(params) {
return object

2021-03-08 06:03 UTC, iamtarun1993 commented on src/app/core/services/org-user.service.ts
> +    if (params.or) {
not sure this is the right way to write this.. @Julias0 @abhishek1234321 please check here.

2021-03-08 14:44 UTC, iamtarun1993 commented on src/app/shared/components/fy-apporver/approver-dialog/approver-dialog.component.html
> +    <ion-button mode="md" class="approver-list--save" fill="solid" [disabled]="equals" color="fyle-primary" (click)="saveUpdatedApproveList()">
why this changed to a static variable??

2021-03-10 08:27 UTC, iamtarun1993 commented on src/app/fyle/view-team-report/view-team-report.page.html
> +        <div class="view-reports--card__external-component-no-margin" *ngIf="actions.can_add_approver">
change the class name.. what is `-no-margin` ??

2021-03-10 08:27 UTC, iamtarun1993 commented on src/app/shared/components/fy-apporver/approver-dialog/approver-dialog.component.ts
> +  intialSelectedApprovers: any[] = [];
why `any` sir again??

2021-03-11 09:03 UTC, iamtarun1993 commented on src/app/fyle/view-team-report/view-team-report.page.html
> +      <ng-container *ngIf="this.actions$|async as actions">
why `this.` ??

2021-03-12 04:48 UTC, abhishek1234321 requested changes

2021-03-12 04:48 UTC, abhishek1234321 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +                return !employees.find(employee => employee.us_email === searchedEmployee.us_email);
`.find` returns the element found no? what does `!` mean here?

2021-03-12 04:48 UTC, abhishek1234321 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
>      this.filteredOptions$ = fromEvent(this.searchBarRef.nativeElement, 'keyup').pipe(
why is this inside `ngAfterViewInit`?

2021-03-12 04:48 UTC, abhishek1234321 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +  onElementSelected(selectedOption, event) {
`onSelect`?

2021-03-12 04:48 UTC, abhishek1234321 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +  onElementSelected(selectedOption, event) {
please define the required types

2021-03-12 04:48 UTC, abhishek1234321 commented on src/app/shared/components/fy-userlist/fy-userlist.component.ts
> +        this.displayValue = this.innerValue.join(',');
screenshot for this?

2021-03-12 08:35 UTC, madhavmansuriya40 commented on src/app/core/services/org-user.service.ts
> +    return this.apiService.get('/eous/company/count').pipe(
sir this method is not used at any places now, we have replaced all employee calls to v2

2021-03-12 08:42 UTC, madhavmansuriya40 commented on src/app/core/models/employee.model.ts
> +  ap2_email?: string;
in v2 have not unflattened response

2021-03-12 08:45 UTC, madhavmansuriya40 commented on src/app/core/models/employee.model.ts
> +export interface Employee {
we already have `ExtendedOrgUser ` model

which is like 
```import {OrgUser} from './org-user.model';
import {User} from './user.model';
import {Approver} from './approver.model';
import {BankBranch} from './bank-branch.model';
import {Dwolla} from './dwolla.model';

export interface ExtendedOrgUser {
  ou: OrgUser;
  us: User;
  ap1: Approver;
  ap2: Approver;
  ap3: Approver;
  bb: BankBranch;
  dwolla: Dwolla;
  checked?: boolean;
}
```

2021-03-12 09:29 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +          return this.getSearchedUsersList(null).pipe(
`this.getSearchedUsersList` accepts a `search_text` parameter when it loads for the first time or no search test (on clearing)

2021-03-12 09:37 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +                return !employees.find(employee => employee.us_email === searchedEmployee.us_email);
we are using it in nested props, so if no item found (`!undefined = true`) it will return true to the filter

2021-03-12 09:37 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +                return !employees.find(employee => employee.us_email === searchedEmployee.us_email);
we can use indexOf here

2021-03-12 09:40 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
>      this.filteredOptions$ = fromEvent(this.searchBarRef.nativeElement, 'keyup').pipe(
we can't use `fromEvent` in oninit, so we need to use it in `ngAfterViewInit`

2021-03-12 12:00 UTC, madhavmansuriya40 commented on src/app/core/services/org-user.service.ts
> +        return range(0, count);
it will work properly, as the range is starting from 0

2021-03-12 12:04 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-userlist/fy-userlist.component.ts
> +        this.displayValue = this.innerValue.join(',');
i just refactored this code, no updates from my end

2021-03-12 12:05 UTC, madhavmansuriya40 commented on src/app/fyle/my-add-edit-trip/my-add-edit-trip.page.html
> +                [label]="fg.controls.travelAgent.value ? 'Agent' : 'Select Agent'"
<--- with value ---->
![Screenshot 2021-03-12 at 5 34 36 PM](https://user-images.githubusercontent.com/51825933/110938074-4fdacf00-8359-11eb-8d41-d7970bc5d196.png)

<--- without value ---->
![Screenshot 2021-03-12 at 5 34 51 PM](https://user-images.githubusercontent.com/51825933/110938082-523d2900-8359-11eb-8d18-380c959d2c72.png)

2021-03-12 13:43 UTC, iamtarun1993 commented on src/app/fyle/view-team-advance/view-team-advance.page.scss
> +      margin: 0;
we have `mb-0` but no `mt-0`

2021-03-13 03:51 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-apporver/approver-dialog/approver-dialog.component.ts
> +      params.limit = 20;
this is used to get only 20 approvers in the list initially, and other will be coming based on search

2021-03-14 07:56 UTC, iamtarun1993 commented on src/app/core/services/org-user.service.ts
> +        return range(0, count);
@madhavmansuriya40 where is `range` ???

2021-03-14 07:57 UTC, iamtarun1993 commented on src/app/core/services/org-user.service.ts
> +    if (params.or) {
@madhavmansuriya40 please explain what is the reason...

2021-03-14 08:02 UTC, iamtarun1993 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +          return this.getSearchedUsersList(null).pipe(
hey, I think passing `null` is not a good idea. we need to write `this.getSearchedUsersList` in the way it should be able to handle null case. you can do this by making this param optional.

2021-03-14 08:04 UTC, iamtarun1993 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
>      this.filteredOptions$ = fromEvent(this.searchBarRef.nativeElement, 'keyup').pipe(
IIRC this is a component so we need to trigger this observable after `ngAfterViewInit` we can't do this inside ngInit .

2021-03-14 12:33 UTC, madhavmansuriya40 commented on src/app/core/services/org-user.service.ts
> +        return range(0, count);
rage is a function no?

2021-03-14 12:47 UTC, iamtarun1993 commented on src/app/core/services/org-user.service.ts
> +        return range(0, count);
sorry I missed line no 72.

2021-03-14 12:50 UTC, madhavmansuriya40 commented on src/app/core/services/org-user.service.ts
> +    if (params.or) {
so the `getEmployeesBySearch` send params and in which we already have `or` for searching with `name or email` and in this function also we append the params with `or` as stated below
and this will replace the previous `or` with the new one so we need to do some jugad to concate both `ors`

2021-03-15 16:57 UTC, abhishek1234321 requested changes

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/core/models/employee.model.ts
> +  ou_allowed_cost_centers: any[];
array of strings or ids?

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/core/models/employee.model.ts
> +  ou_band: any;
why is this any?

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/core/models/employee.model.ts
> +  is_selected: boolean; // used to show checkmarks while selecting approvers
shouldn't this be optional? it is not sent from API no?

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/fyle/view-team-advance/view-team-advance.page.scss
> +      margin: 0;
@tarunkumarfyle let us please add it?

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  onUpdateApprover(message) {
why remove the type?

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/shared/components/fy-apporver/approver-dialog/approver-dialog.component.ts
> +          }
`} else if {`

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/shared/components/fy-apporver/approver-dialog/approver-dialog.component.ts
> +      params.limit = 20;
let us get only 10 no? will that be less for any screen?

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/shared/components/fy-apporver/approver-dialog/approver-dialog.component.ts
> +      order: 'us_email.asc,ou_id',
shouldn't we be getting based on both name and email, what do we do in webapp for such fields? check with Neeraj

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/shared/components/fy-apporver/approver-dialog/confirmation-comment-popover/confirmation-comment-popover.component.html
> +            <span>{{approver | ellipsis:30}}</span>
why are we limiting?

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +      limit: 20,
limit to 10 just like the other place

2021-03-15 16:57 UTC, abhishek1234321 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +        return eouc.map(eou => {
map inside a map?

2021-03-16 03:50 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-apporver/approver-dialog/confirmation-comment-popover/confirmation-comment-popover.component.html
> +            <span>{{approver | ellipsis:30}}</span>
sir this is a confirmation popup after selecting employees, as the entire email will be visible while selecting employee, if we do ellipsis here will be ok IMHO

![Screenshot 2021-03-16 at 9 16 57 AM](https://user-images.githubusercontent.com/51825933/111253063-7be7a000-8638-11eb-94ee-2d6bed51ea5a.png)

2021-03-16 03:50 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
> +        return eouc.map(eou => {
`map(eouc => {` <- this is RxJs Map operator
`eouc.map` <- js map

2021-03-16 10:22 UTC, abhishek1234321 commented on src/app/shared/components/fy-apporver/approver-dialog/confirmation-comment-popover/confirmation-comment-popover.component.html
> +            <span>{{approver | ellipsis:30}}</span>
let is span

2021-03-16 10:24 UTC, abhishek1234321 approved these changes

2021-03-21 05:19 UTC, closed without merging