Policy call payload update for new mobile app
fylein/fyle-mobile-app2 pull request #279
Opened 2021-02-24 12:53 UTC by Sanyem

2021-03-02 05:45 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        policyETxn.tx.corporate_credit_card_expense_group_id = !!this.selectedCCCTransaction;
Do you need `policyETxn.tx.corporate_credit_card_expense_group_id` value as a boolean only??

2021-03-02 05:45 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        policyETxn.tx.corporate_credit_card_expense_group_id = !!this.selectedCCCTransaction;
If this is the case then LGTM.

2021-03-02 05:45 UTC, iamtarun1993 approved these changes

2021-03-02 06:02 UTC, Sanyem commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        policyETxn.tx.corporate_credit_card_expense_group_id = !!this.selectedCCCTransaction;
Yup; need this as boolean only

2021-03-02 06:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        policyETxn.tx.corporate_credit_card_expense_group_id = !!this.selectedCCCTransaction;
hey, not understand this, `corporate_credit_card_expense_group_id` this is supposed to be id and not boolean no? this is like saying I will use `tx_id` but pass a boolean

2021-03-02 06:12 UTC, Sanyem commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        policyETxn.tx.corporate_credit_card_expense_group_id = !!this.selectedCCCTransaction;
Hey, there's a reason behind this - Ideally this should be an id and not a boolean but while creating new expenses, this id is not yet computed or stored in db but we make policy /test calls and we have to violate the policy incase the expense is not matched. That's why for policy /test call we are sending this as boolean. For policy /result call that is made from eventhandler, we are sending this key as id. 

We are using the same key name as both policy calls use the same condition validator and it would be hacky to use different key names for different calls. Also, for policy /result call we modify the etxn before checking the conditions to make this key into a boolean and not specific ids. 

We are not concerned by what id is present. We are only concerned that some id should be present for an expense to be matched

2021-03-02 06:18 UTC, abhishek1234321 requested changes

2021-03-02 06:18 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        policyETxn.tx.corporate_credit_card_expense_group_id = !!this.selectedCCCTransaction;
it should be the policy code's job to identify whether it is present or not and then convert to boolean, in the present scenario every client has to do this no? I am happy to get on a call if need be

2021-03-04 08:14 UTC, abhishek1234321 approved these changes

2021-03-04 08:36 UTC, iamtarun1993 approved these changes

2021-03-05 05:12 UTC, merged