fix in my-expense category icon
fylein/fyle-mobile-app2 pull request #289
Opened 2021-03-03 09:08 UTC by madhavmansuriya40

2021-03-05 05:47 UTC, madhavmansuriya40 commented on src/app/fyle/my-expenses/my-expenses-card/my-expenses-card.component.html
> +          <app-fy-category-icon [category]="(expense.tx_extracted_data && expense.tx_extracted_data.category && expense.tx_fyle_category === 'Unspecified' ? (expense.tx_extracted_data.category) : exp
the code snippet is taken from old mobile app

2021-03-05 09:05 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses-card/my-expenses-card.component.html
> +          <app-fy-category-icon [category]="(expense.tx_extracted_data && expense.tx_extracted_data.category && expense.tx_fyle_category === 'Unspecified' ? (expense.tx_extracted_data.category) : exp
Screenshot sir, before and after changes??

2021-03-05 15:09 UTC, iamtarun1993 approved these changes

2021-03-08 05:02 UTC, abhishek1234321 requested changes

2021-03-08 05:02 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses-card/my-expenses-card.component.html
> +          <app-fy-category-icon [category]="(expense.tx_extracted_data && expense.tx_extracted_data.category && expense.tx_fyle_category === 'Unspecified' ? (expense.tx_extracted_data.category) : exp
yes, screenshot please @madhavmansuriya40

2021-03-08 05:19 UTC, madhavmansuriya40 commented on src/app/fyle/my-expenses/my-expenses-card/my-expenses-card.component.html
> +          <app-fy-category-icon [category]="(expense.tx_extracted_data && expense.tx_extracted_data.category && expense.tx_fyle_category === 'Unspecified' ? (expense.tx_extracted_data.category) : exp
sir have attached screenshots in conversations

2021-03-08 07:16 UTC, abhishek1234321 approved these changes

2021-03-08 08:59 UTC, merged