Fix for freshdesk chat in ios safearea rendering
fylein/fyle-mobile-app2 pull request #290
Opened 2021-03-04 13:36 UTC by iamtarun1993

2021-03-04 13:40 UTC, iamtarun1993 commented
New -> ![20210304_190341](https://user-images.githubusercontent.com/23378996/109972347-30222600-7d1d-11eb-9d42-f28f426f264d.jpg)
Old -> ![20210304_190401](https://user-images.githubusercontent.com/23378996/109972358-331d1680-7d1d-11eb-83fe-c423166f0e42.jpg)

2021-03-08 07:13 UTC, abhishek1234321 commented
you are hiding time no @tarunkumarfyle ? is this what is followed everywhere? it looks a bit odd

2021-03-08 07:14 UTC, abhishek1234321 requested changes

2021-03-08 07:14 UTC, abhishek1234321 commented on src/global.scss
> +  padding-top: constant(safe-area-inset-top); /*for iOS 11.2 and above*/
does ionic not handle this out of the box? or is it because we use freshchat, we have to take care of this?

2021-03-08 07:16 UTC, iamtarun1993 commented on src/global.scss
> +  padding-top: constant(safe-area-inset-top); /*for iOS 11.2 and above*/
ionic handle its own component... but it can't handle any frame created by other libraries.

so we need to take care of this..

2021-03-08 09:14 UTC, iamtarun1993 commented
> you are hiding time no @tarunkumarfyle ? is this what is followed everywhere? it looks a bit odd

no sir...
It was hidden in the old app.. but showing in the new app.

2021-03-08 12:03 UTC, abhishek1234321 approved these changes

2021-03-08 12:09 UTC, merged