Trips delete, pull back, close button disable when api call in progress
fylein/fyle-mobile-app2 pull request #299
Opened 2021-03-10 02:40 UTC by madhavmansuriya40

2021-03-14 13:46 UTC, iamtarun1993 approved these changes

2021-03-15 05:04 UTC, abhishek1234321 requested changes

2021-03-15 05:04 UTC, abhishek1234321 commented on src/app/fyle/my-view-trips/my-view-trips.page.ts
> +  pullbackLoading = false;
do we really need different variables for different loaders? can we not use one?

2021-03-15 05:04 UTC, abhishek1234321 commented on src/app/fyle/my-view-trips/my-view-trips.page.ts
>    async deleteTrip() {
when is this method called? any screenshots or loom will really help

2021-03-15 05:10 UTC, madhavmansuriya40 commented on src/app/fyle/my-view-trips/my-view-trips.page.ts
> +  pullbackLoading = false;
if we use 1, with all button
the loader will be shown in all buttons at the same time

2021-03-15 05:10 UTC, madhavmansuriya40 commented on src/app/fyle/my-view-trips/my-view-trips.page.ts
>    async deleteTrip() {
ok will add loom video link

2021-03-17 04:24 UTC, madhavmansuriya40 commented on src/app/fyle/my-view-trips/my-view-trips.page.ts
> +  pullbackLoading = false;
sir i checked about `using 1 variable for showing loader in all buttons` i think this can be done but that will be tricky and hard work, also need to update at many places and all behaviours will not be same

2021-03-17 04:25 UTC, madhavmansuriya40 commented on src/app/fyle/my-view-trips/my-view-trips.page.ts
> +  pullbackLoading = false;
we can have a separate task for refactoring `loaders inside button` component

2021-03-17 15:18 UTC, abhishek1234321 approved these changes

2021-03-21 05:20 UTC, merged