API call for user_app_version should not go if device is not present from browser
fylein/fyle-mobile-app2 pull request #311
Opened 2021-03-15 04:48 UTC by lakshmisuhas1996

2021-03-15 07:41 UTC, madhavmansuriya40 commented on src/app/core/services/offline.service.ts
> +    from(this.deviceService.getDeviceInfo()).subscribe(deviceInfo => {
`this.deviceService.getDeviceInfo()` returns an observable can't we directly subscribe to that ?
I think in that case we will not need `from()`

2021-03-15 12:14 UTC, madhavmansuriya40 approved these changes

2021-03-15 15:45 UTC, iamtarun1993 commented on src/app/core/services/offline.service.ts
> +      if (deviceInfo.platform === 'ios' || deviceInfo.platform === 'android') {
deviceInfo.platform.toLowerCase() === 'ios'

2021-03-15 15:47 UTC, iamtarun1993 requested changes
use .toLowerCase()

2021-03-16 08:43 UTC, iamtarun1993 approved these changes

2021-03-16 10:19 UTC, abhishek1234321 approved these changes

2021-03-22 08:14 UTC, merged