User Service Model changes
fylein/fyle-mobile-app2 pull request #318
Opened 2021-03-17 05:59 UTC by lakshmisuhas1996

2021-03-17 06:03 UTC, lakshmisuhas1996 commented on src/app/core/models/user-property.model.ts
> +  id?: string;
keeping all properties optional because for some users api res return empty object does not have any property in it.

2021-03-17 06:18 UTC, madhavmansuriya40 approved these changes
please also check if we user user service methods at other places and do required changes

2021-03-17 07:11 UTC, iamtarun1993 commented on src/app/core/models/user-property.model.ts
> +  devices?: { id: string; fcm_token: string; }[];
create another interface and use the new model here

2021-03-17 07:18 UTC, iamtarun1993 commented on src/app/core/models/user-property.model.ts
> +  id?: string;
how this can be possible.. it will always return `id, create_at, updated_at` 
`devices` can be an empty array.

2021-03-17 07:19 UTC, iamtarun1993 commented on src/app/core/models/user-property.model.ts
> +  id?: string;
check with `tarung.kumar@fyle.in`

2021-03-17 07:20 UTC, iamtarun1993 requested changes
some major comments

2021-03-17 12:35 UTC, lakshmisuhas1996 commented on src/app/core/models/user-property.model.ts
> +  id?: string;
For yours (u_id - usHOvyUSnZPS) was getting response with all props and for my acc (u_id - us2t5LrjG3sk) not getting any res. And also in **push-notification.service.ts** we are checking the res came is null or not?

2021-03-21 05:57 UTC, iamtarun1993 commented on src/app/core/models/user-property.model.ts
> +  id?: string;
ok.. got it, looks like this is a bug from the backend. let's keep optional thingy.

2021-03-21 05:59 UTC, iamtarun1993 commented on src/app/core/models/user-property.model.ts
> +export interface DeviceInfo {
move this to under `V1` directory

2021-03-22 04:52 UTC, abhishek1234321 requested changes

2021-03-22 04:52 UTC, abhishek1234321 commented on src/app/core/models/v1/user-property.model.ts
> +  id?: string;
not understanding this, can all the properties be optional? isn't that odd?

2021-03-22 05:19 UTC, lakshmisuhas1996 commented on src/app/core/models/v1/user-property.model.ts
> +  id?: string;
For this API call **users/us_id/properties**, for some user accounts the response has all those properties in the response and for some the response was empty. And also in push-notification.service (line 71) we are checking if the res is empty or not and upserting user properties if not present

2021-03-22 10:40 UTC, abhishek1234321 requested changes

2021-03-22 10:40 UTC, abhishek1234321 commented on src/app/core/models/v1/user-property.model.ts
> +  id?: string;
is this optional in API, if not then why keep this optional?

2021-03-22 12:46 UTC, abhishek1234321 approved these changes

2021-04-05 03:55 UTC, merged