fixed parallel call issue and validation issue in transport req
fylein/fyle-mobile-app2 pull request #346
Opened 2021-03-27 05:27 UTC by madhavmansuriya40

2021-03-28 04:44 UTC, madhavmansuriya40 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +        purpose: [this.fgValues.purpose || null, Validators.required],
setting default value when any new advance is added (same behaviour as old app)

2021-03-28 04:44 UTC, madhavmansuriya40 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +        if (this.otherRequests[0].hotel && this.hotelDetails.length === 0) {
case `while editing trip`
while editing trip if user want to add hote request, user needs to check hotel request checkbox that makes `this.otherRequests[0].hotel = true` also need to add `this.hotelDetails.length === 0` condition 

as it is written in the same method where all the default forms are initialized

2021-03-28 04:44 UTC, madhavmansuriya40 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +        if (this.otherRequests[2].transportation && this.transportDetails.length === 0) {
same as above

`Note: These changes will not be made in advance as advance can be added manually`

2021-03-28 04:44 UTC, madhavmansuriya40 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +                transportMode: [, Validators.required],
this was missed

2021-03-28 04:44 UTC, madhavmansuriya40 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +          } else {
added `if-else here`

if will be the case when a hotel request is already added, so we need to iterate through API response
else will be the case when the user is editing trip req and want to add hotel request, this will initialize default form

2021-03-28 04:44 UTC, madhavmansuriya40 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +          } else {
same as above

2021-03-28 04:44 UTC, madhavmansuriya40 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +          } else {
same as above

2021-03-28 04:44 UTC, madhavmansuriya40 commented on src/app/fyle/my-view-trips/transportation-requests/transportation-requests.component.html
> +          {{eTransportationRequest.tr.to_city.city || eTransportationRequest.tr.to_city.display}}</div>
if custom city name is added we need to show display

2021-03-29 11:15 UTC, iamtarun1993 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +      console.log(formValue.transportDetails);
remove console.log

2021-03-29 11:16 UTC, iamtarun1993 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +              // This logic can be modified to any way you want if you don't want to mutate the `producIds` array
remove this line

2021-03-29 11:18 UTC, iamtarun1993 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +        const tempTransportDetails = cloneDeep(formValue.transportDetails);
this logic is missed for hotel requests...
if the parallel call goes for a hotel request then also it will fail

2021-04-02 04:49 UTC, abhishek1234321 requested changes

2021-04-02 04:49 UTC, abhishek1234321 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +              if (tempAdvanceDetails.length) {
please explain in code comments, what is being done here?

2021-04-02 04:49 UTC, abhishek1234321 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +          if (hotelRequest.length > 0) {
shouldn't this be `hotelRequests`?

2021-04-02 04:49 UTC, abhishek1234321 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +              renderedCustomFeild.forEach(field => {
complexity is n*n, any way to reduce this?

2021-04-05 06:52 UTC, madhavmansuriya40 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +              renderedCustomFeild.forEach(field => {
sir each request will have their own set of custom fields in label value format, i think this will be the best way to set values in custom fields for all requests

2021-04-05 11:07 UTC, iamtarun1993 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +              renderedCustomFeild.forEach(field => {
I think we need to do it in this way only. there could be 3 hotel requests and for 3 hotel requests value of customField can be different. So we need to do run a forEach inside every hotelRequest forEach.

2021-04-05 15:25 UTC, Julias0 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +        let loop = (advanceDetail) => {
For making sequential calls please use range + concatMap.
This approach is very confusing

2021-04-08 06:10 UTC, iamtarun1993 commented on src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
> +        of(formValue.hotelDetails).pipe(
put a comment here, what this is doing

2021-04-11 04:59 UTC, abhishek1234321 approved these changes

2021-04-12 02:02 UTC, merged