Fyle 2hepcz - Adding loaders for autocomplete fields
fylein/fyle-mobile-app2 pull request #355
Opened 2021-04-01 05:53 UTC by shishirams222

Changes of new loader for autocomplete fields:

Screenshots:

When the user starts typing, only loader will be shown:
![Screenshot 2021-04-01 at 11 19 21 AM](https://user-images.githubusercontent.com/31820553/113249594-91b5c000-92dc-11eb-985e-2d04639fe615.png)

Once the user stops typing, results will be filtered and clear button will be shown (Only one icon at a time):
![Screenshot 2021-03-30 at 1 30 32 PM](https://user-images.githubusercontent.com/31820553/113246532-ce7eb880-92d6-11eb-9325-d7744437b77b.png)

2021-04-01 06:12 UTC, shishirams222 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +
Filtering recently used items on search text

2021-04-01 06:14 UTC, shishirams222 commented on src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.html
> +      <div *ngIf="!((filteredOptions$|async)?.length > 0 && (recentrecentlyUsedItems$|async)?.length > 0)" class="selection-modal--list-element">
`No Results Found` will be shown only when there are no options to show under filtered options and recently used items

2021-04-01 06:43 UTC, Julias0 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.html
> +      <button mat-button *ngIf="!loader && value" matSuffix mat-icon-button aria-label="Clear" (click)="value=''">
(click)="value=''"

Do this inside a funciton

2021-04-01 06:44 UTC, Julias0 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.html
> +      <button mat-button *ngIf="!loader && value" matSuffix mat-icon-button aria-label="Clear" (click)="value=''">
Cant we make a component / directive out of this instead of doing this manually doing this everywhere?

2021-04-01 06:44 UTC, Julias0 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.html
> +      <button mat-button *ngIf="!loader && value" matSuffix mat-icon-button aria-label="Clear" (click)="value=''">
fy-text-input with optional loader

2021-04-01 06:46 UTC, Julias0 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +            if (searchText && searchText.length > 0) {
extract everything here to a method

2021-04-01 06:47 UTC, Julias0 commented on src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.ts
> +            if (searchText && searchText.length > 0) {
same as above - you can reuse this in all of the compoenents

2021-04-01 10:28 UTC, shishirams222 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.html
> +      <button mat-button *ngIf="!loader && value" matSuffix mat-icon-button aria-label="Clear" (click)="value=''">
Will be taken care separately, need some time here

2021-04-03 12:16 UTC, abhishek1234321 requested changes

2021-04-03 12:16 UTC, abhishek1234321 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.scss
> +    fill: #f36;
use scss variable?

2021-04-03 12:16 UTC, abhishek1234321 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.scss
> +  @keyframes loading-circular {
move this to a common file?

2021-04-03 12:16 UTC, abhishek1234321 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.scss
> +    fill: #f36;
move this to a common file?

2021-04-03 12:16 UTC, abhishek1234321 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.scss
> +  &--autocomplete-loader {
move this to a common file?

2021-04-03 12:16 UTC, abhishek1234321 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +    this.cdr.detectChanges();
why is this needed? please explain in code comments

2021-04-03 12:16 UTC, abhishek1234321 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +        this.cdr.detectChanges();
why is this needed? please explain in code comments

2021-04-03 12:16 UTC, abhishek1234321 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +    if (this.recentlyUsed) {
can you get this reviewed by @Dimple16 too?

2021-04-03 12:16 UTC, abhishek1234321 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +                return item && item.label && item.label.length > 0 && item.label.toLocaleLowerCase().includes(searchTextLowerCase);
explain this in code comments?

2021-04-03 12:16 UTC, abhishek1234321 commented on src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.ts
> +  getRecentlyUsedVendors() {
we are repeating a lot of code no, can we not move it to a service method?

2021-04-03 12:16 UTC, abhishek1234321 commented on src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.ts
> +            if (searchText && searchText.length > 0) {
I think we should do it off instead of waiting for another round of cleanup @shishirams222 @Julias0

2021-04-05 05:55 UTC, shishirams222 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.scss
> +  &--autocomplete-loader {
Moved to new file _fy_select.scss

2021-04-05 07:38 UTC, shishirams222 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.html
> +      <button mat-button *ngIf="!loader && value" matSuffix mat-icon-button aria-label="Clear" (click)="value=''">
`value = ' '` will be set in clearValue() now.

2021-04-05 07:39 UTC, shishirams222 commented on src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.ts
> +  getRecentlyUsedVendors() {
Updated

2021-04-05 07:40 UTC, shishirams222 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +    this.cdr.detectChanges();
updated

2021-04-05 07:40 UTC, shishirams222 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +        this.cdr.detectChanges();
updated

2021-04-05 07:49 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +  filterRecentlyUsedItems (searchText) {
filterRecentlyUsedItems<T>(searchText) {
return map((recentrecentlyUsedItems:T[]) => {

2021-04-05 07:50 UTC, Julias0 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +import {UtilityService} from 'src/app/core/services/utility.service';
spacing

2021-04-05 07:51 UTC, Julias0 commented on src/assets/styles/_fy_select.scss
> +}
add a newline

2021-04-05 07:52 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +  filterRecentlyUsedItems (searchText) {
rename to searchArrayStream<T>(searchText: string): Observable<T[]>

2021-04-05 10:12 UTC, Julias0 approved these changes

2021-04-05 17:27 UTC, abhishek1234321 requested changes

2021-04-05 17:27 UTC, abhishek1234321 commented on src/app/core/services/utility.service.ts
> +  searchArrayStream<T>(searchText: string){
`string) {`

2021-04-05 17:27 UTC, abhishek1234321 commented on src/app/core/services/utility.service.ts
> +  searchArrayStream<T>(searchText: string){
what is `T` put in code comments?

2021-04-05 17:27 UTC, abhishek1234321 commented on src/app/core/services/utility.service.ts
> +    })
`;`?

2021-04-05 17:27 UTC, abhishek1234321 commented on src/app/core/services/utility.service.ts
> +        return recentrecentlyUsedItems.filter( item => {
`filter(item => {`

2021-04-05 17:27 UTC, abhishek1234321 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
> +import {Observable, fromEvent, of, from, forkJoin, noop, throwError, observable} from 'rxjs';
`{ Observable` `observable }`

2021-04-05 17:27 UTC, abhishek1234321 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
> +  clearValue() {
explain in code comments on what is happening here?

2021-04-05 17:27 UTC, abhishek1234321 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
> +            switchMap(({ eou, currentLocation }) => {
`(({eou, currentLocation})`

2021-04-05 17:27 UTC, abhishek1234321 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
> +              return [];
in `if` case we are returning an `[]` and in the else case an observable of `null` @Julias0 ? @shishirams222

2021-04-05 17:27 UTC, abhishek1234321 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +              return option;
is an observable returned in `else` case?

2021-04-05 17:37 UTC, Julias0 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
> +              return [];
This should be `of([])`

2021-04-06 06:54 UTC, shishirams222 commented on src/app/core/services/utility.service.ts
> +  searchArrayStream<T>(searchText: string){
updated

2021-04-06 06:54 UTC, shishirams222 commented on src/app/core/services/utility.service.ts
> +  searchArrayStream<T>(searchText: string){
updated

2021-04-06 06:54 UTC, shishirams222 commented on src/app/core/services/utility.service.ts
> +    })
updated

2021-04-06 06:55 UTC, shishirams222 commented on src/app/core/services/utility.service.ts
> +        return recentrecentlyUsedItems.filter( item => {
updated

2021-04-06 06:55 UTC, shishirams222 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
> +import {Observable, fromEvent, of, from, forkJoin, noop, throwError, observable} from 'rxjs';
updated

2021-04-06 06:55 UTC, shishirams222 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
> +  clearValue() {
updated

2021-04-06 06:55 UTC, shishirams222 commented on src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
> +            switchMap(({ eou, currentLocation }) => {
updated

2021-04-07 08:26 UTC, shishirams222 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +              return option;
Yes, the logic will remain same. Have moved this part inside a separate method. cc @Julias0

2021-04-07 08:26 UTC, shishirams222 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
> +    if (this.recentlyUsed) {
Done, and green for the changes

2021-04-07 10:28 UTC, abhishek1234321 approved these changes

2021-04-08 05:28 UTC, merged