minor
fylein/fyle-mobile-app2 pull request #356
Opened 2021-04-01 13:14 UTC by iamtarun1993

2021-04-01 14:25 UTC, madhavmansuriya40 approved these changes

2021-04-01 14:26 UTC, madhavmansuriya40 approved these changes

2021-04-01 16:05 UTC, Julias0 approved these changes

2021-04-05 04:31 UTC, Julias0 commented on src/app/core/services/permissions.service.ts
> +            return of(null);
shouldnt we return the throwError?

2021-04-05 04:34 UTC, iamtarun1993 commented on src/app/core/services/permissions.service.ts
> +            return of(null);
If we return `throwError` also then the sentry also catch this and put in their console. So no point of solving this

2021-04-05 04:42 UTC, Julias0 commented on src/app/core/services/permissions.service.ts
> +            return of(null);
But why is this error coming in the first place?

2021-04-05 11:05 UTC, Julias0 commented on src/app/core/services/permissions.service.ts
> +      }),filter(roles => roles.length > 0)
lets skip this approach

2021-04-05 11:06 UTC, Julias0 commented on src/app/core/services/permissions.service.ts
>      return filteredRoles$.pipe(
use iif to check if fitleredRoles is null or empty array. If yes, return of(null) else lets go with this flow.

Using filter will prevent this observable from resolving which might have unintented consequences

2021-04-06 04:48 UTC, abhishek1234321 requested changes

2021-04-06 04:48 UTC, abhishek1234321 commented on src/app/core/services/permissions.service.ts
> +            return throwError('no route access');
is this an observable?

2021-04-06 04:48 UTC, abhishek1234321 commented on src/app/core/services/permissions.service.ts
> +            return throwError('no route access');
is this an observable?

2021-04-06 04:48 UTC, abhishek1234321 commented on src/app/core/services/permissions.service.ts
> +            return throwError('no route access');
is this an observable?

2021-04-06 04:48 UTC, abhishek1234321 commented on src/app/core/services/permissions.service.ts
> +            return throwError('no route access');
is this an observable?

2021-04-06 04:53 UTC, abhishek1234321 approved these changes

2021-04-06 04:53 UTC, iamtarun1993 commented on src/app/core/services/permissions.service.ts
> +            return throwError('no route access');
yes throwErrror always return observables

2021-04-06 04:55 UTC, Julias0 approved these changes

2021-04-06 04:57 UTC, merged