While showing the matched expense details, expense state is not displayed
fylein/fyle-mobile-app2 pull request #359
Opened 2021-04-05 06:28 UTC by hlkavya0213

![Screenshot 2021-04-05 at 11 53 56 AM](https://user-images.githubusercontent.com/79827230/113544598-364e3f80-9606-11eb-8305-12b74d4a97a6.png)
![Screenshot 2021-04-05 at 11 55 49 AM](https://user-images.githubusercontent.com/79827230/113544606-3b12f380-9606-11eb-850a-34dc1dd55caf.png)

2021-04-05 07:29 UTC, gokulk16 commented
check with Tarun on the directive for the state name map

2021-04-05 18:37 UTC, iamtarun1993 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.scss
> +      background-color: #f90;
declare all colors as variables. Then use it here

2021-04-05 18:38 UTC, iamtarun1993 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.scss
> +    &__COMPLETE {
small case please

2021-04-05 18:39 UTC, iamtarun1993 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.html
> +                <span *ngIf="txn.state === 'COMPLETE'">FYLED</span>
can we not solve this with any state pipe.
check `reportState` pipe

2021-04-06 06:14 UTC, iamtarun1993 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.scss
> +$white: white;
`$white: #fff;`

2021-04-06 06:17 UTC, iamtarun1993 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.html
> +              <div class="ccc-classified-actions--pill ccc-classified-actions--pill__{{txn.state | reportState}}">
don't use any reportState. Create another new cccState and use it.

2021-04-06 06:17 UTC, iamtarun1993 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.html
> +              <div class="ccc-classified-actions--pill ccc-classified-actions--pill__{{txn.state | reportState}}">
`ionic -g pipe directory-name/name-of-pipe-here`
that's how you create a new pipe

2021-04-06 11:19 UTC, iamtarun1993 approved these changes

2021-04-06 11:20 UTC, iamtarun1993 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.html
>                  <span class="receipt-attached-text">-</span>
this branch have a conflict please resolve before merging

2021-04-06 12:58 UTC, abhishek1234321 requested changes

2021-04-06 12:58 UTC, abhishek1234321 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.scss
> +$fyled_pill: #f90;
we should be using `-` also these should be available globally like we do in webapp, @Julias0 could you help?

2021-04-06 12:58 UTC, abhishek1234321 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.scss
> +$paid_pill: #3d8b3d;
we should have a mixin for this @Julias0 isn't that what we do in webapp? @tarunkumarfyle @hlkavya0213

2021-04-06 12:58 UTC, abhishek1234321 commented on src/app/shared/pipes/expense-state.pipe.ts
> +export class ExpenseState implements PipeTransform {
any reason why this should be ExpenseState and not just State?

2021-04-06 12:58 UTC, abhishek1234321 commented on src/app/shared/pipes/expense-state.pipe.ts
> +export class ExpenseState implements PipeTransform {
we could add advance/trip/report states as well

2021-04-08 06:06 UTC, iamtarun1993 commented on src/app/shared/pipes/expense-state.pipe.ts
> +export class ExpenseState implements PipeTransform {
we already have `reportState`. state of different models can be different. 
in the web app, we have one single state and another advanceState.
so it's good if we make different states for different models. 
If tomorrow we need to change something for a particular model we can easily do it.

2021-04-08 06:06 UTC, iamtarun1993 commented on src/app/shared/pipes/expense-state.pipe.ts
> +export class ExpenseState implements PipeTransform {
@Julias0 what do you think ?

2021-04-08 07:50 UTC, Julias0 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.scss
> +$fyled_pill: #f90;
@hlkavya0213 can you refer to how @shishirams222 did the autocomplete styling in lieu of setting up a scss file with these variables?

2021-04-08 07:53 UTC, Julias0 commented on src/app/shared/pipes/expense-state.pipe.ts
> +export class ExpenseState implements PipeTransform {
I dont like the idea of these being pipes at all :P 
There should be a component called state - where we pass in one input which map of colors to choose and in the other the value.

That way it would be very easy to acheive homogenity plus all state color wala stuff will be encapsulated in one place

2021-04-08 07:54 UTC, Julias0 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.scss
> +$paid_pill: #3d8b3d;
We should encapsulate state inside a component imho. That way we encapsulate the state wala pill behavior

2021-04-09 03:53 UTC, abhishek1234321 approved these changes

2021-04-09 03:53 UTC, abhishek1234321 commented on src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.scss
> +$fyled_pill: #f90;
@hlkavya0213 this needs. to be taken care of

2021-04-19 06:53 UTC, merged