My advances page
fylein/fyle-mobile-app2 pull request #361
Opened 2021-04-05 15:20 UTC by iamtarun1993

2021-04-07 05:30 UTC, Julias0 approved these changes

2021-04-09 04:00 UTC, abhishek1234321 requested changes

2021-04-09 04:12 UTC, iamtarun1993 commented on src/app/fyle/my-advances/my-advances.page.html
> +      <ng-container *ngIf="advances.length > 0; else advanceZeroState">
resolving Observables in 2 places parallelly in HTML, triggering the method in ts file twice, which is triggering loaderService twice. This is not actually creating any problem because of loaderService, but throwing error in console. And here we just need an else case to show zeroState why resolve the observables twice.

2021-04-09 04:17 UTC, iamtarun1993 commented on src/app/fyle/my-advances/my-advances.page.ts
> +    this.myAdvancerequests$ = this.advanceRequestService.getMyadvanceRequests({queryParams: { offset:0, limit: 10, areq_trip_request_id: 'is.null', areq_advance_id: 'is.null', order: 'areq_created_at
This is actually a paginated call to get data for the first batch, but we are only using the count value.
now inside `concatMap` there is the same call going. For the first batch, there will be only one call now because of ts-cacheable.

We can also remove `order: 'areq_created_at.desc,areq_id.desc'` but then ts-cacheable will consider this as a new queryParams and call another API for this.

2021-04-09 04:18 UTC, iamtarun1993 commented on src/app/fyle/my-advances/my-advances.page.ts
> +    this.myAdvances$ = this.advanceService.getMyadvances({queryParams: {offset:0, limit: 10, order: 'adv_created_at.desc,adv_id.desc'}}).pipe(
No first date and then id.

order by create_at first and then created_at can be same so merge id with it.

2021-04-09 04:46 UTC, abhishek1234321 approved these changes

2021-04-09 05:49 UTC, merged