Fyle inverse highlight: Text highlight changes for fy-select dropdowns
fylein/fyle-mobile-app2 pull request #364
Opened 2021-04-06 10:34 UTC by shishirams222

Screenshots:

2021-04-06 11:07 UTC, Julias0 commented on src/global.scss
> +.inverse-highlight {
move this to component ka scss file

2021-04-07 09:05 UTC, abhishek1234321 requested changes

2021-04-07 09:05 UTC, abhishek1234321 commented on src/app/shared/pipes/highlight.pipe.ts
> +        text = text.toString(); // sometimes comes in as number
when does it come as a number? if it comes as a number and you return a string, wouldn't it cause other issues? when the selection happens in the modal and stuff?

2021-04-07 09:05 UTC, abhishek1234321 commented on src/app/shared/pipes/highlight.pipe.ts
> +          let pattern = search.trim().replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, '\\$&');
what does this do? explain in code comments and give SO ref in code comments

2021-04-07 09:05 UTC, abhishek1234321 commented on src/app/shared/pipes/highlight.pipe.ts
> +          }).join('|');
why join with `|`, explain with an example in code comments

2021-04-08 07:25 UTC, shishirams222 commented on src/app/shared/pipes/highlight.pipe.ts
> +        text = text.toString(); // sometimes comes in as number
There no cases currently where it will be a number. So removed it. Changes in the existing places are working fine post removal

2021-04-08 07:27 UTC, shishirams222 commented on src/app/shared/pipes/highlight.pipe.ts
> +          let pattern = search.trim().replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, '\\$&');
Added reference and explained in detail with a example for every step

2021-04-08 07:27 UTC, shishirams222 commented on src/app/shared/pipes/highlight.pipe.ts
> +          }).join('|');
Updated

2021-04-09 08:44 UTC, Julias0 approved these changes

2021-04-09 13:40 UTC, abhishek1234321 approved these changes

2021-04-09 18:56 UTC, merged