Switch to org option should not be visible when switched to delegatee account
fylein/fyle-mobile-app2 pull request #368
Opened 2021-04-08 09:12 UTC by lakshmisuhas1996

2021-04-08 14:07 UTC, iamtarun1993 approved these changes

2021-04-09 03:48 UTC, abhishek1234321 requested changes

2021-04-09 03:48 UTC, abhishek1234321 commented on src/app/app.component.ts
> +            isVisible: (orgs.length > 1) && !this.isSwitchedToDelegator,
if I am in the delegatee's account, how do I switch to other delegatee's account?

2021-04-09 04:35 UTC, lakshmisuhas1996 commented on src/app/app.component.ts
> +            isVisible: (orgs.length > 1) && !this.isSwitchedToDelegator,
When we switch to any delegatee's account, we will get an option to **Switch back to own account** then we can switch to other delegatee's account by clicking on **Delegated Accounts**
![Screen Shot 2021-04-09 at 10 01 44 AM](https://user-images.githubusercontent.com/79460986/114128852-f4c9d700-991a-11eb-8a2e-7f4a63c2bed9.png)
![Screen Shot 2021-04-09 at 10 03 44 AM](https://user-images.githubusercontent.com/79460986/114128858-f72c3100-991a-11eb-95aa-ca7c0c7e13fd.png)

2021-04-09 05:11 UTC, abhishek1234321 approved these changes

2021-04-27 10:15 UTC, merged