Delegated Account
fylein/fyle-mobile-app2 pull request #39
Opened 2020-10-20 15:44 UTC by madhavmansuriya40

2020-10-20 16:25 UTC, Julias0 commented on src/app/core/services/org-user.service.ts
> +  // TODO: move to v2
dei this is a post call

2020-10-20 16:26 UTC, Julias0 approved these changes

2020-10-20 16:28 UTC, Julias0 commented on src/app/app.module.ts
> +    DelegatedAccMessageComponent
Why is this here? This should be declared inside the shared.module.ts

2020-10-20 16:29 UTC, Julias0 commented on src/app/fyle/delegated-accounts/delegated-accounts.page.html
> +            <div class="delegated--org-element-usdetails">
delegated--org-element-us-details

2020-10-20 16:30 UTC, Julias0 commented on src/app/fyle/delegated-accounts/delegated-accounts.page.ts
> +    const switchToOwn = this.activatedRoute.snapshot.params.switchToOwn && JSON.parse(this.activatedRoute.snapshot.params.switchToOwn);
Why is parsing required here?

2020-10-20 16:31 UTC, Julias0 commented on src/app/fyle/delegated-accounts/delegated-accounts.page.ts
> +    const switchToOwn = this.activatedRoute.snapshot.params.switchToOwn && JSON.parse(this.activatedRoute.snapshot.params.switchToOwn);
mention with a comment why parsing is required here

2020-10-20 16:33 UTC, Julias0 requested changes
Please fix

2020-10-21 03:01 UTC, madhavmansuriya40 commented on src/app/fyle/delegated-accounts/delegated-accounts.page.ts
> +    const switchToOwn = this.activatedRoute.snapshot.params.switchToOwn && JSON.parse(this.activatedRoute.snapshot.params.switchToOwn);
actually, this is not required will remove it

2020-10-21 05:07 UTC, Julias0 approved these changes

2020-10-21 15:04 UTC, closed without merging