Dashboard revamp
fylein/fyle-mobile-app2 pull request #405
Opened 2021-05-24 09:41 UTC by Julias0

2021-05-26 14:22 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.html
> +    <clipPath id="wave" clipPathUnits="objectBoundingBox">
this is a svg to be used with clip path property to get that wavy look as in design

2021-05-27 13:30 UTC, Julias0 commented on src/app/fyle/dashboard/dashboard.page.scss
> +    --background: #{$background-color};
#{} <--- this is required to pass a value from a scss variable to css variable

2021-05-27 13:41 UTC, Julias0 commented
![Screenshot 2021-05-27 at 7 06 54 PM](https://user-images.githubusercontent.com/5515766/119836398-57a11d00-bf1f-11eb-947c-f11cc0f95e1e.png)
![Screenshot 2021-05-27 at 7 11 00 PM](https://user-images.githubusercontent.com/5515766/119836422-5b34a400-bf1f-11eb-8140-5a52d68a0d26.png)
![Screenshot 2021-05-27 at 7 11 11 PM](https://user-images.githubusercontent.com/5515766/119836426-5c65d100-bf1f-11eb-8dff-6fb9e83e9bbe.png)

2021-05-27 16:56 UTC, abhishek1234321 commented
@Julias0 would it appear as USD or `$`?

2021-05-27 16:58 UTC, abhishek1234321 commented
do we show a shimmer when the data is loaded? should we not @Julias0 ?

2021-05-27 17:16 UTC, abhishek1234321 commented
The last screen appears as if `Home` is the active tab, but that isn't the case

2021-05-27 17:59 UTC, abhishek1234321 reviewed
The styling of the action sheet is different from designs @Julias0

2021-05-27 17:59 UTC, abhishek1234321 commented on src/theme/colors.scss
> +$card-background: #FFFFFF;
#fff should do, can we define some global colors? like, white black, primary, secondary etc? check what is the standard followed or recommended by ionic?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/theme/colors.scss
> +$badge-background: #ffffff66;
hey, this should be `rgba`, I am not sure how many browsers support this format, please check

2021-05-27 17:59 UTC, abhishek1234321 commented on src/theme/colors.scss
> +$badge-value: #fff;
DRY is violated

2021-05-27 17:59 UTC, abhishek1234321 commented on src/theme/colors.scss
> +$badge-highlight-black: #464D57;
convention is mixed, uppercase and lowercase, please stick to one?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/global.scss
> +    background: #fafafa;
use scss variables

2021-05-27 17:59 UTC, abhishek1234321 commented on src/assets/svg/fy-calendar.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
are you able to style these via css? I remember @Dimple16 mentioning she wasn't able to

2021-05-27 17:59 UTC, abhishek1234321 commented on src/assets/images/no-internet.svg
> +<svg viewBox="0 0 315 189" fill="none" xmlns="http://www.w3.org/2000/svg">
should this be an image or SVG? please check what works best @Julias0

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/icon/icon.module.ts
> +  svgImageArray = ['fy-individual.svg', 'fy-add-new-expense.svg', 'fy-dismiss.svg', 'fy-done.svg', 'fy-classify-ccc.svg', 'fy-chat.svg', 'add-advance.svg', 'fy-filter.svg', 'fy-card.svg', 'fy-team-re
what is this about? is it for generating a single SVG? if yes, shouldn't all the icons present in a specific folder be taken automatically? that is what we do in webapp, could we figure out something similar here?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/fy-zero-state/fy-zero-state.component.ts
> +  @Input() unscaledImage = false;
what is this about?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/fy-zero-state/fy-zero-state.component.scss
> +    &__unscaled {
why is this needed?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/fy-zero-state/fy-zero-state.component.scss
> +    &__unscaled {
why is this needed?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/footer/footer.component.ts
> +  constructor() { }
shouldn't this be the first method? can we check JohnPapa style guide once? also let us add of ESLint rules

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/footer/footer.component.scss
> +    width: 100%;
why use both width and flex together?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/footer/footer.component.scss
> +    display: flex;
can we not use grid for these?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/footer/footer.component.scss
> +    bottom: 0px;
`0`

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/footer/footer.component.scss
> +    color: #fff;
scss

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/footer/footer.component.html
> +      <mat-icon *ngIf="activeState === FooterState.HOME" svgIcon="fy-home-solid"></mat-icon>
can we use a single element and change svgIcon dynamically?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/footer/footer.component.html
> +    <div class="fy-footer--button" expand="full" (click)="onHomeClick()">
`goToHome`

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/shared/components/footer/footer.component.html
> +    <div class="fy-footer--button fy-footer--button__disabled" expand="full" (click)="onTasksClick()">
`goToTasks`

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/fyle/tasks/tasks.page.scss
> +    --background: #{$background-color};
what is this `--` about?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/fyle/tasks/tasks.page.scss
> +    --background: #{$background-color};
is it for CSS variables?

2021-05-27 17:59 UTC, abhishek1234321 commented on src/app/fyle/tasks/tasks.page.scss
> +    margin: 42px 24px;
margin is used for spacing b/w elements, would padding make more sense?

2021-05-27 18:32 UTC, abhishek1234321 requested changes

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/core/models/v2/stats-response.model.ts
> +        return this.data && this.data.length && this.data[index];
`this.data.length > 0`

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/core/services/transaction.service.ts
> +    reimbursible_total: number,
`reimbursable`

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +      this.router.navigate(['/', 'enterprise', 'add_edit_expense', {dataUrl: this.recentImage, extractData: this.instafyleEnabled}]);    }
`canExtractData` could be better

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +      this.instafyleEnabled = orgUserSettings.insta_fyle_settings.allowed && orgUserSettings.insta_fyle_settings.enabled;
`isInstaFyleEnabled`

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/dashboard.page.ts
> +    await getStartedPopup.onWillDismiss();
why not use observables everywhere?

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/dashboard.page.ts
> +      isGetStartedPopupShown: from(this.storageService.get('getStartedPopupShown')),
is this not observable? I mean the convention is observable ends with `$` no?

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/dashboard.page.ts
> +    ).subscribe(_ => this.showGetStartedPopup());
what is `_` about?

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stat-badge/stat-badge.component.html
> +  <div class="stat-badge--count" [ngClass]="{'stat-badge--count__black': color === StatBadgeColors.BLACK, 'stat-badge--count__blue': color === StatBadgeColors.BLUE, 'stat-badge--count__green': color
let us use the state names for colors? tmrw we change blue to red, it will be a problem

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
> +  display: flex;
can we use ion grid?

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
> +    width: 64%;
this is an odd value

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            <div class="stats--menu-button">
we should make this a common header component later, since both header and footer would be same everywhere

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stats/stats.component.scss
> +    left: -12px;
is this absolutely needed?

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +  goToDraftState() {
`gotToMyExpenses` pass the query params from html?

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +  goToReportedState() {
same as above

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +    const that = this;
is this needed?

2021-05-27 18:32 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +        text: 'Add Mileage',
hey, this will depend on a lot of settings no sire?

2021-05-27 19:18 UTC, Julias0 commented on src/app/shared/components/footer/footer.component.ts
> +  constructor() { }
Yes, this is the first method - the one before this is a getter, which should stay with the variables

2021-05-27 19:23 UTC, Julias0 commented on src/theme/colors.scss
> +$card-background: #FFFFFF;
Ionic has theming with css variables but using it is problematic since it would effect a bunch of existing places - using it would require us to make a ton of changes.

Since the designs were not consistent earlier on too we couldn't use it at that time

2021-05-27 19:24 UTC, Julias0 commented on src/theme/colors.scss
> +$badge-background: #ffffff66;
resolved offline - ionic webviews come with inbuilt rendering so this is supported

2021-05-27 19:24 UTC, Julias0 commented on src/theme/colors.scss
> +$badge-value: #fff;
I can make these color specific but that means I have to think of names for all of the colors :P

2021-05-27 19:29 UTC, Julias0 commented on src/app/shared/icon/icon.module.ts
> +  svgImageArray = ['fy-individual.svg', 'fy-add-new-expense.svg', 'fy-dismiss.svg', 'fy-done.svg', 'fy-classify-ccc.svg', 'fy-chat.svg', 'add-advance.svg', 'fy-filter.svg', 'fy-card.svg', 'fy-team-re
This is to register the icons with material icons so that all of the rendering stuff is taken care by it.Heres the [link](https://www.digitalocean.com/community/tutorials/angular-custom-svg-icons-angular-material)
 we followed
 
 Looping through all of the icons is not possible directly in angular
 https://stackoverflow.com/questions/49445719/loop-through-all-files-images-in-a-folder-with-angular
 
 Would require major jugaad

2021-05-27 19:30 UTC, Julias0 commented on src/app/shared/components/fy-zero-state/fy-zero-state.component.ts
> +  @Input() unscaledImage = false;
So the older zero state had a max-width associated with the image.
This meant that I couldn't reuse it for the new places without the image appearing very small

2021-05-27 19:31 UTC, Julias0 commented on src/app/shared/components/fy-zero-state/fy-zero-state.component.scss
> +    &__unscaled {
So the older zero state had a max-width associated with the image.
This meant that I couldn't reuse it for the new places without the image appearing very small 
I added a param to remove off the max width and height for now - once all the previous zero states are removed off I can clean this up

2021-05-27 19:32 UTC, Julias0 commented on src/app/shared/components/footer/footer.component.ts
> +  constructor() { }
The linting thing I should take care of separately - it will increase the size of this PR if I introduce it now

2021-05-27 19:34 UTC, Julias0 commented on src/app/shared/components/footer/footer.component.scss
> +    display: flex;
So, for one-dimensional stuff flexbox is much easier / better to work with - ionic grid doesn't help much for the footer since we have the custom styling of the camera icon, which would need some extra css treatment anyway

2021-05-27 19:36 UTC, Julias0 commented on src/app/shared/components/footer/footer.component.scss
> +    width: 100%;
ah width will effect this division. The flex will effect the children of this division.
Since the footer is inside the ion content part as a fixed position element, I had to manually stretch it over the screen (I couldn't put it inside footer since it wouldn't allow the hanging camera)

2021-05-28 06:02 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +    reimbursible_total: number,
Ah the spelling mistake is in the response :P Needs to be fixed in API

2021-05-28 06:10 UTC, Julias0 commented on src/app/fyle/dashboard/dashboard.page.ts
> +    await getStartedPopup.onWillDismiss();
ionic modals ka syntax uses promises multiple time - using observables effect readability quite a lot
Ex - 
```
from(
this.popoverController.create({      component: GetStartedPopupComponent,      cssClass: 'get-started-popup'    })
).pipe(
  switchMap(popup => from(popup)),
  switchMap(renderedPopup => from(renderedPopup))
  ).subscribe(async _ => {
    await this.storageService.set('getStartedPopupShown', true);
  })

```
Observable ka syntax doesn't do much here other than add complexity

2021-05-28 06:12 UTC, Julias0 commented on src/app/fyle/dashboard/dashboard.page.ts
> +      isGetStartedPopupShown: from(this.storageService.get('getStartedPopupShown')),
a variable which contains a observable we mark with a $.
This is not exactly an observable but a dictionary of observables, to mark the response type.

If we use `isGetStartedPopupShown$` here, in the response the variable will come as `isGetStartedPopupShown$` which is not an observable but has the observable mark creating confusion

2021-05-28 06:16 UTC, Julias0 commented on src/app/fyle/dashboard/dashboard.page.ts
> +    ).subscribe(_ => this.showGetStartedPopup());
I saw this syntax being used in some blog articles. This means that the response of the observable is not used

2021-05-28 06:20 UTC, Julias0 commented on src/app/fyle/dashboard/stat-badge/stat-badge.component.html
> +  <div class="stat-badge--count" [ngClass]="{'stat-badge--count__black': color === StatBadgeColors.BLACK, 'stat-badge--count__blue': color === StatBadgeColors.BLUE, 'stat-badge--count__green': color
Then this would look like -
```
export enum StatBadgeColors {    
  BLACK = 'black',    
  GREEN = 'green',    
  BLUE = 'blue'
  }

```
```
<div class="stat-badge--count" [class]="'stat-badge--count__' + color.toString()">
```

2021-05-28 06:21 UTC, Julias0 commented on src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
> +    width: 64%;
Had to use some eye estimation to make this look good in responsive :P

2021-05-28 06:31 UTC, Julias0 commented on src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
> +  display: flex;
it will add a lot of boilerplate code here for a simple component :( 

Ex - 
 ```
 <ion-grid>
   <ion-row>
      <ion-col>
        <div class="stats--count">{{count}}</div>
      </ion-col>
      <ion-col>
        <ion-grid>
          <ion-row>
             <ion-col>
               {{name}}
             </ion-col>
          </ion-row>
          <ion-row>
             <ion-col>
              {{value}}
             </ion-col>
          </ion-row>
        </ion-grid>
      </ion-col>
    </ion-row>
 </ion-grid>
 ```

2021-05-28 06:40 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            <div class="stats--menu-button">
The header for dashboard is not at all consistent with the ones in the list view pages na.
The dashboard header needs to be inside the same div as the stat elements because they have the same background - 
Also list view headers have a lot of functionality which we would need to hide with configs or booleans if we make it generic.

2021-05-28 06:50 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +    const that = this;
Yes, because the handler is nested function references of this will start pointing to global

2021-05-28 06:50 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +        text: 'Add Mileage',
my bad - will fix this

2021-05-28 06:51 UTC, Julias0 commented on src/app/fyle/tasks/tasks.page.scss
> +    --background: #{$background-color};
Ionic recommends customizing their component this way. Yes these are css variables

2021-05-28 06:52 UTC, Julias0 commented on src/app/fyle/tasks/tasks.page.scss
> +    margin: 42px 24px;
This is actually used to space the zero state element within the page i.e.space outside of the zero state.

2021-05-28 06:53 UTC, Julias0 commented on src/assets/svg/fy-calendar.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
didnt try :P

2021-05-28 07:50 UTC, abhishek1234321 requested changes

2021-05-28 07:50 UTC, abhishek1234321 commented on src/app/core/services/transaction.service.ts
> +    reimbursible_total: number,
check if we can use `stats` service

2021-05-28 07:50 UTC, abhishek1234321 commented on src/app/fyle/dashboard/dashboard.page.ts
> +    ).subscribe(_ => this.showGetStartedPopup());
put a comment wherever this is used for reference, with a link

2021-05-28 07:50 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stat-badge/stat-badge.component.html
> +  <div class="stat-badge--count" [ngClass]="{'stat-badge--count__black': color === StatBadgeColors.BLACK, 'stat-badge--count__blue': color === StatBadgeColors.BLUE, 'stat-badge--count__green': color
could use `STATES`

2021-05-28 07:50 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
> +    &__black {
do not use color names in class names

2021-05-28 07:50 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stats/stats.component.scss
> +  &--expenses-count {
verify the optimization once

2021-05-28 07:50 UTC, abhishek1234321 commented on src/app/shared/components/fy-zero-state/fy-zero-state.component.scss
> +    &__unscaled {
add a comment, `TODO`

2021-05-28 07:50 UTC, abhishek1234321 commented on src/app/shared/icon/icon.module.ts
> +  svgImageArray = ['fy-individual.svg', 'fy-add-new-expense.svg', 'fy-dismiss.svg', 'fy-done.svg', 'fy-classify-ccc.svg', 'fy-chat.svg', 'add-advance.svg', 'fy-filter.svg', 'fy-card.svg', 'fy-team-re
let us do this separately

2021-05-31 09:52 UTC, Julias0 commented on src/app/shared/components/fy-zero-state/fy-zero-state.component.scss
> +    &__unscaled {
Added in TS file

2021-05-31 10:17 UTC, Julias0 commented
> @Julias0 would it appear as USD or `$`?

$ only

2021-05-31 13:20 UTC, Julias0 commented
![Screenshot 2021-05-31 at 6 32 33 PM](https://user-images.githubusercontent.com/5515766/120199552-ff308f00-c240-11eb-96df-a69356144051.png)
![Screenshot 2021-05-31 at 6 32 50 PM](https://user-images.githubusercontent.com/5515766/120199559-022b7f80-c241-11eb-86ff-a4f731abdc7e.png)
![Screenshot 2021-05-31 at 6 44 08 PM](https://user-images.githubusercontent.com/5515766/120199566-035cac80-c241-11eb-90e4-2ac2025addb1.png)
![Screenshot 2021-05-31 at 6 48 25 PM](https://user-images.githubusercontent.com/5515766/120199570-03f54300-c241-11eb-9270-fcf1d4d99e40.png)

2021-05-31 13:24 UTC, Julias0 commented on src/app/fyle/dashboard/dashboard.page.ts
> +    ).subscribe(_ => this.showGetStartedPopup());
Placed above the forkjoin

2021-06-01 04:35 UTC, abhishek1234321 approved these changes

2021-06-01 04:35 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stats/stats.component.html
> +          <app-stat-badge [currency]="homeCurrency$|async"
this is not report state @Julias0 , I think it is expense state, check with Aditi once?

2021-06-01 04:35 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +    that.offlineService.getOrgSettings().subscribe(orgSettings => {
`orgSettings` we should be adding a `model` for this

2021-06-01 04:35 UTC, abhishek1234321 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +    const mileageEnabled = orgSettings.mileage.enabled;
`isMileageEnabled`

2021-06-02 07:19 UTC, iamtarun1993 commented on src/app/core/models/v2/stats-response.model.ts
> +    function_name: string;
2 space tab

2021-06-02 07:20 UTC, iamtarun1993 commented on src/app/core/services/report.service.ts
> +        map(rawStatsResponse => new StatsResponse(rawStatsResponse))
2 space tab

2021-06-02 07:20 UTC, iamtarun1993 commented on src/app/fyle/dashboard/dashboard.page.html
> +    <app-stats #stats></app-stats>
2 space tab

2021-07-27 10:38 UTC, closed without merging