Fyle t 3khv6k: Critical policy violation popup
fylein/fyle-mobile-app2 pull request #423
Opened 2021-06-09 12:01 UTC by iamtarun1993

2021-06-13 13:06 UTC, iamtarun1993 commented
iPhone x and iPhone 5 with 2 policy violations
<img width="341" alt="Screenshot 2021-06-13 at 6 32 16 PM" src="https://user-images.githubusercontent.com/23378996/121808465-4160c400-cc76-11eb-9470-3dd51ae52e48.png">
<img width="358" alt="Screenshot 2021-06-13 at 6 31 47 PM" src="https://user-images.githubusercontent.com/23378996/121808468-445bb480-cc76-11eb-9f30-f5ebbc0d4087.png">

2021-06-13 13:07 UTC, iamtarun1993 commented
iPhone 5 and iPhone X with more than 5- 10 violations.
<img width="367" alt="Screenshot 2021-06-13 at 6 33 10 PM" src="https://user-images.githubusercontent.com/23378996/121808492-65bca080-cc76-11eb-90f9-3b82f91a167d.png">
<img width="344" alt="Screenshot 2021-06-13 at 6 32 55 PM" src="https://user-images.githubusercontent.com/23378996/121808496-68b79100-cc76-11eb-9c17-e404775ee11d.png">

2021-06-14 07:41 UTC, Julias0 approved these changes

2021-06-14 09:29 UTC, abhishek1234321 requested changes

2021-06-14 09:29 UTC, abhishek1234321 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    text-align: center;
can we use a `utility` class like we do in webapp? `text-center`?

2021-06-14 09:29 UTC, abhishek1234321 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    font-weight: 400;
isn't this `400` by default?

2021-06-14 09:29 UTC, abhishek1234321 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    text-align: center;
this is repeated, could be reused

2021-06-14 09:29 UTC, abhishek1234321 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    --height: calc(100% - 288px);
why `288`?

2021-06-14 09:29 UTC, abhishek1234321 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    max-height: 40vh;
why 40?

2021-06-14 09:29 UTC, abhishek1234321 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    padding: 2px 13px 2px 5px;
this padding value is quite odd and asymmetrical

2021-06-14 09:29 UTC, abhishek1234321 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    margin: 0;
can we not use `m-0` and `p-0` utility classes? if they aren't already present, please add them

2021-06-14 09:29 UTC, abhishek1234321 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    width: 90%;
what is this about?

2021-06-14 09:29 UTC, abhishek1234321 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    font-size: 14px;
repeated

2021-06-14 09:44 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.module.ts
>  import { SharedModule } from 'src/app/shared/shared.module';
After clicking on the "Continue" we are closing the popup instantly . We are not doing any API call here.
So we shouldn't show any loader on "Continue".

2021-06-14 10:18 UTC, iamtarun1993 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    --height: calc(100% - 288px);
most probably this is not needed now.

2021-06-14 10:20 UTC, iamtarun1993 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    max-height: 40vh;
The list of expense violations screen should be 40% visible at max for the larger screen.
Else it should be scrollable.

2021-06-14 10:24 UTC, iamtarun1993 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    width: 90%;
We are not using the ionic button here, by default button will be sized based on the text, here we want to increase the button size to 90% of the grid.
<img width="78" alt="Screenshot 2021-06-14 at 3 53 36 PM" src="https://user-images.githubusercontent.com/23378996/121877846-affe5a00-cd28-11eb-87af-649f1066b400.png">

<img width="238" alt="Screenshot 2021-06-14 at 3 54 36 PM" src="https://user-images.githubusercontent.com/23378996/121877980-d45a3680-cd28-11eb-8120-02d87714cbd8.png">

2021-06-14 10:31 UTC, iamtarun1993 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    padding: 2px 13px 2px 5px;
<img width="241" alt="Screenshot 2021-06-14 at 4 00 41 PM" src="https://user-images.githubusercontent.com/23378996/121878739-ade8cb00-cd29-11eb-8173-6ec49e06047e.png">

2021-06-14 16:00 UTC, iamtarun1993 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
> +    font-size: 14px;
was it for font-size or text-center?

2021-06-17 10:16 UTC, abhishek1234321 approved these changes

2021-06-17 12:07 UTC, merged