Added changes for search
fylein/fyle-mobile-app2 pull request #429
Opened 2021-06-14 12:41 UTC by Julias0

2021-06-16 07:41 UTC, Julias0 commented
![Screenshot 2021-06-16 at 1 10 07 PM](https://user-images.githubusercontent.com/5515766/122178500-43a86580-cea4-11eb-9618-fe85665f9692.png)
![Screenshot 2021-06-16 at 1 10 18 PM](https://user-images.githubusercontent.com/5515766/122178515-45722900-cea4-11eb-89ed-9f88fe31bdf8.png)
![Screenshot 2021-06-16 at 1 10 26 PM](https://user-images.githubusercontent.com/5515766/122178519-460abf80-cea4-11eb-92ad-b8641f329f55.png)
![Screenshot 2021-06-16 at 1 08 45 PM](https://user-images.githubusercontent.com/5515766/122178543-4c00a080-cea4-11eb-9b7a-650567c1ee83.png)
![Screenshot 2021-06-16 at 1 08 54 PM](https://user-images.githubusercontent.com/5515766/122178550-4d31cd80-cea4-11eb-9b51-7c3fd112015c.png)
![Screenshot 2021-06-16 at 1 09 11 PM](https://user-images.githubusercontent.com/5515766/122178557-4e62fa80-cea4-11eb-96fa-7264207fb6e0.png)
![Screenshot 2021-06-16 at 1 09 20 PM](https://user-images.githubusercontent.com/5515766/122178562-4efb9100-cea4-11eb-8111-9fa08a01e7a1.png)

2021-06-16 16:21 UTC, abhishek1234321 requested changes

2021-06-16 16:21 UTC, abhishek1234321 commented on src/app/shared/components/fy-filters/fy-filters.component.ts
> +    const activeFilterInitialIndex = (this.activeFilterInitialName && this.filterOptions.findIndex(option => option.name === this.activeFilterInitialName)) || 0;
why default to 0?

2021-06-16 16:21 UTC, abhishek1234321 commented on src/app/shared/components/fy-filters/fy-filters.component.ts
> +    const activeFilterInitialIndex = (this.activeFilterInitialName && this.filterOptions.findIndex(option => option.name === this.activeFilterInitialName)) || 0;
is it to select the first element?

2021-06-16 16:21 UTC, abhishek1234321 commented on src/app/shared/components/fy-filters/fy-filters.component.ts
> +  switchFilter(currentFilter: FilterOptions<any>, option: { label: string; value: any }) {
what is `switchFilter` about?

2021-06-16 16:21 UTC, abhishek1234321 commented on src/app/shared/components/fy-filters/selected-filters.interface.ts
> +  value: T | T[];
is this a good way? sometimes `string` sometimes `[]` of numbers :P

2021-06-16 16:21 UTC, abhishek1234321 commented on src/app/shared/components/fy-filters/selected-filters.interface.ts
> +  associatedData?: {
you could have this without `?` and use `as` this usually works well when you use things for `post` and you don't have `id`

2021-06-17 07:41 UTC, Julias0 commented on src/app/shared/components/fy-filters/selected-filters.interface.ts
> +  associatedData?: {
`as` is used for typecasting data but since this is an interface we cant use it here

2021-06-17 07:44 UTC, Julias0 commented on src/app/shared/components/fy-filters/selected-filters.interface.ts
> +  value: T | T[];
Using unions is actually ok in typescript - since typescript doesn't have a good way of serialization of classes, we cant do it in the object-oriented way of creating implementations of the interface and only having methods here.

Heres a reference why unions are awesome - https://reallifeprogramming.com/why-union-is-your-best-friend-in-modeling-types-in-typescript-bb6d53a130ba

2021-06-17 07:45 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.ts
> +  switchFilter(currentFilter: FilterOptions<any>, option: { label: string; value: any }) {
switch filter is about maintaining the state of the filter which is currently being modified by type.

2021-06-17 07:46 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.ts
> +    const activeFilterInitialIndex = (this.activeFilterInitialName && this.filterOptions.findIndex(option => option.name === this.activeFilterInitialName)) || 0;
Yes, if no activeFilterName is passed we default to the first filter as the activeFilter

2021-06-17 07:49 UTC, Julias0 commented on src/app/shared/components/fy-filters/selected-filters.interface.ts
> +  associatedData?: {
`as` is used for typecasting data mostly - not for defining types 
https://stackoverflow.com/questions/55781559/what-does-the-as-keyword-do

2021-06-17 07:51 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.ts
> +  customDateMap: {[key: string]: {
we would have to use `?` or Partial with `as` since the params would still be required . Plus `as` is used for typecasting mostly

2021-06-17 08:20 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.html
> +      <ion-button class="fy-filters--save" (click)="save()" expand="block" color="fyle-primary" fill="solid">
ionic defaults this to `button` 
https://ionicframework.com/docs/api/button
I don't think we should use type='submit' since that is used in old style forms and I would have to add a preventDefault

2021-06-17 08:21 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.scss
> +    height: 100%;
Yes, the row optimizes space on what is inside but in this case we can to expand the space to take up the whole space inside the body of the filter

2021-06-17 08:23 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.scss
> +    --inner-padding-top: 13px;
the ion label which is used inside has a padding of 9px by default. This is basically to sum it up and make total padding 22px

2021-06-17 08:25 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.html
> +                <input matInput [(ngModel)]="startDate" (ngModelChange)="onDateChange()" [matDatepicker]="picker1">
picker1 is the reference to `<mat-datepicker #picker1></mat-datepicker>` 
This is required for the input to link to the datepicker - has no usage / will have no usage otherwise.

2021-06-17 08:27 UTC, Julias0 commented on src/app/shared/components/fy-filters/filter-options.interface.ts
> +  options: { label: string, value: T }[];
Since filters is generic the value can be anything - strings, enums etc. Plus this is not getting it at runtime - this would be creating a generic class that is resolved at compile-time only.

2021-06-17 08:35 UTC, Julias0 commented on src/app/shared/components/fy-delete-dialog/fy-delete-dialog.component.ts
> +  get LoaderPosition() {
This is to get the enum definition available inside the template via a getter -
https://stackoverflow.com/questions/59289095/use-of-enums-in-angular-8-html-template-for-ngif

2021-07-27 16:17 UTC, closed without merging