Fyle t 3nfz8f: My expenses card redesign
fylein/fyle-mobile-app2 pull request #435
Opened 2021-06-18 10:31 UTC by iamtarun1993

2021-06-28 04:27 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.html
> +<div class="my-expenses--body">
Will fix this indentation after review.
Fixing indentation showing too many changes on this page. 
not easy to review. just added `<div class="my-expenses--body">` in the body

2021-07-01 14:47 UTC, Julias0 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
> +    @Inject(MAT_BOTTOM_SHEET_DATA) public data: any,
why is @Inject required

2021-07-01 14:48 UTC, Julias0 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      this.homeCurrencySymbol = getCurrencySymbol(homeCurrency, 'wide');
I think we use the narrow symbol everywhere - can you check inside stat component

2021-07-01 14:51 UTC, Julias0 commented on src/app/shared/components/create-new-report/create-new-report.component.ts
> +        this.homeCurrencySymbol = getCurrencySymbol(homeCurrency, 'wide');
do this inside subscribe than inside map

2021-07-01 14:52 UTC, Julias0 commented on src/global.scss
> +  border-radius: 16px !important;
cant we avoid these :(

2021-07-04 07:52 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      this.homeCurrencySymbol = getCurrencySymbol(homeCurrency, 'wide');
no we use wide symbol

2021-07-04 09:33 UTC, iamtarun1993 commented on src/global.scss
> +  border-radius: 16px !important;
We need to put important. else `.mat-snack-bar-container` has border-radius 4px..
and overwriting our own css.

2021-07-05 05:14 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +  getReportAbleExpenses(expenses: Expense[]): Expense[] {
getReportableExpenses

2021-07-05 05:15 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +    return reportAbleExpenses;
return expenses. filter(expense => !this.getIsCriticalPolicyViolated(expense) && !this.getIsDraft(expense))

2021-07-05 05:15 UTC, Julias0 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
> +    line-height: 17.92px;;
round off these fractional line heights

2021-07-05 05:16 UTC, Julias0 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +  isReportAbleExpensesSelected = false;
isReportableExpensesSelected

2021-07-05 05:17 UTC, Julias0 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +            message: `We could not delete the expenses. Please try again `,
dont use ` unless you are using templating

2021-07-06 03:53 UTC, abhishek1234321 commented
could you please put the required screenshots for various cases?

2021-07-06 04:38 UTC, iamtarun1993 commented
Scanning receipt, critical policy violation, and normal expense card
<img width="360" alt="Screenshot 2021-07-06 at 10 07 26 AM" src="https://user-images.githubusercontent.com/23378996/124542938-fb94b700-de41-11eb-9659-099e3322fc80.png">

2021-07-06 04:39 UTC, iamtarun1993 commented
Long category name 
![Uploading Screenshot 2021-07-06 at 10.09.02 AM.png…]()

2021-07-06 04:40 UTC, iamtarun1993 commented
Long category name with policy violation
<img width="377" alt="Screenshot 2021-07-06 at 10 10 04 AM" src="https://user-images.githubusercontent.com/23378996/124543147-58906d00-de42-11eb-95f8-41606cb70736.png">

2021-07-06 04:41 UTC, iamtarun1993 commented
Same page when selection mode is enabled.
<img width="369" alt="Screenshot 2021-07-06 at 10 10 42 AM" src="https://user-images.githubusercontent.com/23378996/124543187-6fcf5a80-de42-11eb-87fc-64a6c1a8659c.png">

2021-07-06 04:42 UTC, iamtarun1993 commented
Alert popup when more critical policy expenses or draft expenses are selected.
<img width="378" alt="Screenshot 2021-07-06 at 10 12 17 AM" src="https://user-images.githubusercontent.com/23378996/124543313-a7d69d80-de42-11eb-91c6-089bbac5a7c2.png">

2021-07-06 04:43 UTC, iamtarun1993 commented
Add new report modal controller
<img width="369" alt="Screenshot 2021-07-06 at 10 13 07 AM" src="https://user-images.githubusercontent.com/23378996/124543375-c6d52f80-de42-11eb-8076-5ef016259550.png">

2021-07-06 04:44 UTC, iamtarun1993 commented
Add to old report action controller
<img width="365" alt="Screenshot 2021-07-06 at 10 13 48 AM" src="https://user-images.githubusercontent.com/23378996/124543441-deacb380-de42-11eb-89e3-68c7b8d4f7df.png">

2021-07-06 04:45 UTC, iamtarun1993 commented
With expense field name and foreign currency
<img width="371" alt="Screenshot 2021-07-06 at 10 14 27 AM" src="https://user-images.githubusercontent.com/23378996/124543480-f5eba100-de42-11eb-8507-6e5c1b08afbe.png">

2021-07-06 15:59 UTC, abhishek1234321 requested changes

2021-07-06 15:59 UTC, abhishek1234321 commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> +    if (this.expense.source_account_type === "PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT") {
single quotes no?

2021-07-06 15:59 UTC, abhishek1234321 commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> +      if (!this.expense.tx_skip_reimbursement) {
what happens in the case of advances payment mode?

2021-07-06 15:59 UTC, abhishek1234321 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.html
> +          [ngClass]="{'popup-alert--cta-button__disabled': primaryCta.isDisabled}" [disabled]="primaryCta.isDisabled"
why disable? why not show an error on tap?

2021-07-06 15:59 UTC, abhishek1234321 commented on src/global.scss
> +  border-radius: 16px !important;
is there no other way to overwrite these?

2021-07-06 16:11 UTC, iamtarun1993 commented on src/app/core/models/expense.model.ts
> +  isPolicyViolated: boolean;
We don't get any columns from API for critical policy violations and policy violations.
we calculate this in web-app and mobile-app..
for critical = (typeof expense.tx_policy_amount === 'number' && expense.tx_policy_amount < 0.0001)
for policy = (this.expense.tx_manual_flag || this.expense.tx_policy_flag)

We can ignore this but in HTML pages and ts file in multiple places we need to write this to show icons / text.
want to avoid that.. so did this.

2021-07-06 16:12 UTC, iamtarun1993 commented on src/app/core/models/expense.model.ts
> +  isDraft: boolean;
same like previous... We need to write `expense.tx_state === 'DRAFT';` in too many places.. instead of this did inside the model.

2021-07-06 16:14 UTC, iamtarun1993 commented on src/app/core/services/report.service.ts
> +              map(() => newReport)
Report `/reports/' + rptId + '/submit'` call doesn't return any response only 200 code...
But we need to show the redirect option in toast message ..  and bind the report id to it for redicetion. So need to
return report id from report POST call

2021-07-07 03:58 UTC, iamtarun1993 commented on src/app/core/services/transaction.service.ts
> +      vendorName = expense.tx_distance || 0;
naming it to `vendorDisplayName`

2021-07-07 04:02 UTC, iamtarun1993 commented on src/app/core/services/transaction.service.ts
> +  getIsCriticalPolicyViolated(expense: Expense): boolean{
I'm using these two methods inside other pages also

2021-07-07 04:14 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
> +          <ion-col size="8.5" class="ion-no-padding">
yes, it works..
you can test it in this stackbiltz
https://stackblitz.com/edit/ionic-ng-basic-grid-5pehld?file=src%2Fapp%2Fapp.component.html

2021-07-07 04:18 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
> +    font-weight: 400;
yes we can remove it... 
this is inside the mat bottom sheet, which default font-weight is 400.

2021-07-07 04:21 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
> +    line-height: 26px;
<img width="504" alt="Screenshot 2021-07-07 at 9 50 34 AM" src="https://user-images.githubusercontent.com/23378996/124699632-c901c180-df08-11eb-9e8e-9873d449bbab.png">
Not too much effect in HTML if we make it 20 px also..
but in design it is 26 px;

2021-07-07 04:25 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
> +    max-width: 86px;
yes it is needed... else the pill width is taking the full size of ion-col .
and looks bad in iPhone X and above

2021-07-07 04:39 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
> +    @Inject(MAT_BOTTOM_SHEET_DATA) public data: any,
copy-pasted from stack overflow.. updated this to proper datatype...

2021-07-07 05:12 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
> +        this.reportCurrencySymbol = getCurrencySymbol(homeCurrency, 'wide');
This used to get the currency symbol... like $

2021-07-07 05:14 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
> +    ).subscribe(noop);
no if we are not doing anything inside subscribe we need to pass noop inside subscribe..

2021-07-07 05:15 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
> +    ).subscribe(noop);
Actually, all assignments should be done inside subscribe... not inside map

2021-07-07 05:21 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.html
> +          [previousExpenseTxnDate]="list[i-1]?.tx_txn_dt"
We need to show the date of all expenses if the previous date of txns is different.
We need to group expenses where with tx_txn_dt if it is present.. if not then with tx_created_at

2021-07-07 05:23 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.html
> +      <app-expenses-card
yes, this is only one expense. changing it to `app-expense-card`

2021-07-07 05:36 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.html
> -    <app-fy-zero-state
This is for offline zero states.. 
right now we shouldn't allow users to come to redirect to my expenses page in offline mode

2021-07-07 05:39 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.html
> +  <div class="my-expenses--footer">
yes this div is not needed now..

2021-07-07 05:40 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.html
> +    <app-fy-footer *ngIf="!selectionMode" (homeClicked)="onHomeClicked()" (taskClicked)="onTaskClicked()" (cameraClicked)="onCameraClicked()"></app-fy-footer>
This was implemented by Aiyush before we agreed on this..
and changing this now will lead to change in many places. not putting this inside this branch

2021-07-07 05:41 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.html
> +                <button type="button" [disabled]="!isReportableExpensesSelected || (openReports.length === 0)"
No we are not showing any error why this two CTA are disabled

2021-07-07 05:43 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
>      setTimeout(() => {
Not sure but this looks like used to show/ hide shimmers. 
Implemented by Dimple.. I changed nothing here

2021-07-07 08:26 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +  async openCriticalPolicyViolationPopOver(config: Partial<{ title: string, message: string, report_type: string}>) {
partial was needed when some of these values inside are not mandatory.
but here we need all.. removing partial

2021-07-07 08:30 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +        if (config.report_type === 'old_report') {
When the user selected one or more critical policy violated expenses or draft expenses, and choose to add to an old report or new report we need to show criticalPolicyViolationPopOver.

After the user continues with the flow we need to open the old report modal or a new report modal based on the last selection. 
We can store in a global value but global values are costly, so passing the types from method to method

2021-07-07 08:30 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +  openCreateReportWithSelectedIds(report_type: 'old_report' | 'new_report') {
for this
https://github.com/fylein/fyle-mobile-app2/pull/435/files#r665158544

2021-07-07 08:31 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +        const amount = current.tx_amount || current.tx_user_amount;
when critical policy violated expenses are present tx_amount is 0 and tx_user_amount store the original amount.
We need to show total amount in the popover.. so need this.

2021-07-07 08:32 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    if ((noOfExpensesWithCriticalPolicyViolations > 0) || (noOfExpensesInDraftState > 0)) {
if both values are 0 no need to show popup.. just open report modal

2021-07-07 09:31 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +          title = `${noOfExpensesWithCriticalPolicyViolations} Critical Policy and ${noOfExpensesInDraftState} Draft Expenses blocking the way`;
<img width="507" alt="Screenshot 2021-07-07 at 3 01 17 PM" src="https://user-images.githubusercontent.com/23378996/124735986-324afa00-df34-11eb-8e0a-a0de2da548fa.png">
"blocking the way" in the design

2021-07-07 09:35 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +          map(() => report)
`'/reports/' + rptId + '/txns'` API doesn't return any response, only 200.
But we need the report's data to show toast message.. 
Message is different based on report type and id also needed to give an option to view report

2021-07-07 09:38 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      if (report) {
We are sending `of(null)` from switchMap when users doesn't click on any report and click outside..
To handle this case we need this check here

2021-07-07 11:52 UTC, iamtarun1993 commented on src/app/shared/components/create-new-report/create-new-report.component.scss
> +    margin-left: -15%;
in header, if ion-buttons are present, ion title add extra padding to it.. which will move header to right side.
To overcome this issue we need this -15%. We used this in many places because of new design changes..

2021-07-07 12:18 UTC, iamtarun1993 commented on src/app/shared/components/create-new-report/create-new-report.component.spec.ts
> +import { async, ComponentFixture, TestBed } from '@angular/core/testing';
no changed to `waitForAsync` now

2021-07-07 12:30 UTC, iamtarun1993 commented on src/app/shared/components/expenses-card/expenses-card.component.html
> +          <mat-checkbox *ngIf="isSelected" [checked]="true" class="expenses-card--checkbox"></mat-checkbox>
This I need to check.. IIRC there was some issue with mat-checkbox when formControl is not used.

2021-07-07 12:52 UTC, iamtarun1993 commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> +      if (!this.expense.tx_skip_reimbursement) {
tx_skip_reimbursement will be True so else case will be validated and it will show non-reimbursable icon

2021-07-07 12:54 UTC, iamtarun1993 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.html
> +          [ngClass]="{'popup-alert--cta-button__disabled': primaryCta.isDisabled}" [disabled]="primaryCta.isDisabled"
we are not disabling the button in this popup, we will resolve it in parent page based on new design

2021-07-07 12:55 UTC, iamtarun1993 commented on src/global.scss
> +  border-radius: 16px !important;
Don't think there will be any other way to do this.

2021-07-07 13:12 UTC, iamtarun1993 commented on src/app/shared/components/expenses-card/expenses-card.component.html
> +          <mat-checkbox *ngIf="isSelected" [checked]="true" class="expenses-card--checkbox"></mat-checkbox>
Can we punt on this for now @abhishek1234321 .  In old expense cards also we do the same thing...
 Changing this will need to change the full flow about select, redirect, tap, tap and hold in my expense card page.

2021-07-07 16:14 UTC, iamtarun1993 commented on src/app/fyle/my-expenses/my-expenses.page.scss
> +    width: 100%;
<img width="254" alt="Screenshot 2021-07-07 at 9 43 41 PM" src="https://user-images.githubusercontent.com/23378996/124794221-693d0200-df6c-11eb-8eba-78b739460276.png">
If we don't use 100%, the button text will be shrinked to button left and right

2021-07-07 16:47 UTC, iamtarun1993 commented on src/app/shared/components/create-new-report/create-new-report.component.html
> +          [loadingText]="'Submitting Report'" [loading]="submitReportLoader" [disabled]="selectedElements.length === 0 || (submitReportLoader || saveDraftReportLoader)"
Design pending from design team

2021-07-07 16:49 UTC, iamtarun1993 commented on src/app/shared/components/create-new-report/create-new-report.component.scss
> +    position: fixed;
this is inside footer, so this always should be fixed. On scroll it should't change

2021-07-07 16:51 UTC, iamtarun1993 commented on src/app/shared/components/create-new-report/create-new-report.component.ts
> +  selectedTotalAmount = 0;
For this type is not needed na...I already declared it as a `= 0'`. So Ts will convert it datatype to number.

2021-07-07 16:51 UTC, iamtarun1993 commented on src/app/shared/components/create-new-report/create-new-report.component.ts
> +  submitReportLoader = false;
same as above

2021-07-07 16:53 UTC, iamtarun1993 commented on src/app/shared/components/expenses-card/expenses-card.component.html
> +                  {{expense.tx_org_category === 'Unspecified' && expense?.tx_extracted_data?.category ? expense?.tx_extracted_data?.category : expense.tx_org_category}}
Not getting this
https://github.com/fylein/fyle-mobile-app2/pull/435/files#r664618856

2021-07-07 16:53 UTC, iamtarun1993 commented on src/app/shared/components/expenses-card/expenses-card.component.html
> +                  {{expense.tx_org_category === 'Unspecified' && expense?.tx_extracted_data?.category ? expense?.tx_extracted_data?.category : expense.tx_org_category}}
are you saying this
`expense.tx_org_category || expense?.tx_extracted_data?.category`

2021-07-07 16:55 UTC, iamtarun1993 commented on src/global.scss
> +  border-radius: 16px !important;
Changing `.mat-snack-bar-container` deafult class style is not a good idea.

2021-07-09 13:23 UTC, abhishek1234321 requested changes

2021-07-09 13:23 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
> +    line-height: 26px;
are, I meant use `1.4` like that

2021-07-09 13:23 UTC, abhishek1234321 commented on src/app/shared/components/create-new-report/create-new-report.component.ts
> +  selectedTotalAmount = 0;
selectedTotalAmount = '0' will this work or break?

2021-07-09 13:23 UTC, abhishek1234321 commented on src/app/shared/components/create-new-report/create-new-report.component.ts
> +  submitReportLoader = false;
same as earlier

2021-07-09 13:23 UTC, abhishek1234321 commented on src/app/shared/components/expenses-card/expenses-card.component.html
> +          <mat-checkbox *ngIf="isSelected" [checked]="true" class="expenses-card--checkbox"></mat-checkbox>
not understanding, it is one condition no?

2021-07-09 18:12 UTC, abhishek1234321 approved these changes

2021-07-14 17:08 UTC, merged