FYLE-3xeygj: Split expense in expense form
fylein/fyle-mobile-app2 pull request #446
Opened 2021-06-23 18:55 UTC by Dimple16

![Screenshot 2021-06-24 at 12 22 07 AM](https://user-images.githubusercontent.com/31147415/123152838-a391a400-d482-11eb-9332-a6b20e20a37a.png)

2021-06-25 13:45 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +        <div class="add-edit-expense--split-expense-container" (click)="this.fg.valid && splitExpense()" appFormdivValidation>
I don't think `(click)="this.fg.valid && splitExpense()"` is a good practice.
To check validation in HTML. You can move this validation to .ts file

2021-06-25 13:45 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +        <div class="add-edit-expense--split-expense-container" (click)="this.fg.valid && splitExpense()" appFormdivValidation>
what is `appFormdivValidation`??

2021-06-25 13:47 UTC, iamtarun1993 commented on src/app/shared/icon/icon.module.ts
> +      "fy-individual.svg", "fy-iphone.svg", "fy-info.svg",
missed to add "fy-info.svg" file in this PR.

2021-06-26 15:39 UTC, Dimple16 commented on src/app/shared/icon/icon.module.ts
> +      "fy-individual.svg", "fy-iphone.svg", "fy-info.svg",
this icon is already there, wasn't used as `svgIcon` before

2021-06-28 05:17 UTC, iamtarun1993 approved these changes

2021-06-28 08:07 UTC, abhishek1234321 requested changes

2021-06-28 08:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +        <div class="add-edit-expense--split-info-container">
shouldn't this message come only when the required fields are not filled?

2021-06-28 08:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    if (this.fg.valid) {
if the form is not valid and I press the button, how will I know what is wrong?

2021-06-28 08:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +        <div class="add-edit-expense--split-expense-container" (click)="splitExpense()">
shouldn't this be a `button`?

2021-06-28 08:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    width: fit-content;
is this needed?

2021-06-28 08:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        costCenters: this.costCenters$,
do we not get this from offline service? curious to know why is it this way here

2021-06-28 08:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        const areCostCentersAvailable = res.costCenters.length > 0;
don't we check if cost centers are enabled or not before checking their length?

2021-06-28 10:35 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +        <div class="add-edit-expense--split-info-container">
Confirmed with Aditi, this will be visible always - as a message info

2021-06-28 10:36 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    if (this.fg.valid) {
will show error messages in fields and scroll to the error message

2021-06-28 10:41 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        costCenters: this.costCenters$,
yes, `this.costCenters$` is set using offline service `getcostcenters`

2021-06-28 10:42 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        const areCostCentersAvailable = res.costCenters.length > 0;
while we set `this.costCenters$` we check if cost centers is enabled and then set the value, so at this line, the values will be there only if cost centers are enabled

2021-06-28 14:16 UTC, abhishek1234321 approved these changes

2021-06-29 16:39 UTC, merged