recently used currencies in add_edit_expense
fylein/fyle-mobile-app2 pull request #447
Opened 2021-06-24 12:32 UTC by pradeep8093

Recently Currency is shown now in add edit expense page

[](url)
![Screenshot 2021-06-24 at 5 49 43 PM](https://user-images.githubusercontent.com/13829940/123263197-55c67b80-d516-11eb-9f47-a2404bbbd08e.png)

2021-06-24 13:33 UTC, abhishek1234321 requested changes

2021-06-24 13:33 UTC, abhishek1234321 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentCurrencies(currencies, recentValue): Observable<{ label: string, value: string }[]> {
define the model

2021-06-24 13:33 UTC, abhishek1234321 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentCurrencies(currencies, recentValue): Observable<{ label: string, value: string }[]> {
`recentValue` define the model

2021-06-24 13:33 UTC, abhishek1234321 commented on src/app/core/services/recently-used-items.service.ts
> +        { id: id, value: currencies[id]})).filter(id => id);
`.filter(id => id);` not needed

2021-06-24 13:33 UTC, abhishek1234321 commented on src/app/core/services/recently-used-items.service.ts
> +    } else {
return `[]`

2021-06-24 13:33 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                  [cacheName]="'recentCurrencyCache'"
talk to @tarunkumarfyle this may not be needed, talk to @Dimple16 too

2021-06-24 13:33 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.html
> +      <div matRipple class="selection-modal--list-element" *ngFor="let recentrecentlyUsedItem of recentrecentlyUsedItems$ | async as list" (click)="onElementSelect(recentrecentlyUsedItem)">
`track by`

2021-06-24 18:48 UTC, Dimple16 commented on src/app/core/services/recently-used-items.service.ts
> +        { id: id, value: currencies[id]})).filter(id => id);
need to check if the order is retained after removing .filter(id => id), I remember adding this in another place as the recent items order got messed up

2021-06-24 18:51 UTC, Dimple16 commented on src/app/core/services/recently-used-items.service.ts
> +    } else {
in if we are returning observable

2021-06-28 19:36 UTC, pradeep8093 commented
![Screenshot 2021-06-29 at 1 02 32 AM](https://user-images.githubusercontent.com/13829940/123693889-40cf4c80-d876-11eb-9a7f-7f52e9fddbc5.png)

2021-06-29 07:13 UTC, pradeep8093 commented
![Screenshot 2021-06-29 at 12 42 35 PM](https://user-images.githubusercontent.com/13829940/123753516-91c35d00-d8d7-11eb-8368-c9beab6effcf.png)
![Screenshot 2021-06-29 at 12 42 42 PM](https://user-images.githubusercontent.com/13829940/123753527-95ef7a80-d8d7-11eb-9997-256f5fa51128.png)

2021-06-29 08:02 UTC, Dimple16 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentCurrencies(currencies, recentValue): Observable<Currency[]> {
add type of arguments, `currencies: string[], recentValue: RecentlyUsed`

2021-06-29 08:08 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.html
> +      <div matRipple class="selection-modal--list-element" *ngFor="let recentrecentlyUsedItem of recentrecentlyUsedItems$ | async as list" (click)="onCurrencySelect(recentrecentlyUsedItem)">
recentrecentlyUsedItem -> `recentCurrency` any reason for using recentrecentlyUsedItem?

2021-06-29 08:13 UTC, Dimple16 commented on src/app/core/models/currency.model.ts
> +}
add an extra line

2021-06-29 09:44 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.ts
> +  recentlyUsedItems$: Observable<any[]>;
use model

2021-06-29 09:45 UTC, Dimple16 approved these changes

2021-06-29 12:37 UTC, abhishek1234321 approved these changes

2021-06-29 12:37 UTC, abhishek1234321 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentCurrencies(currencies: string[], recentValue:RecentlyUsed): Observable<Currency[]> {
recentValue: RecentlyUsed

2021-06-29 12:37 UTC, abhishek1234321 commented on src/app/core/services/recently-used-items.service.ts
> +        { id: id, value: currencies[id]}));
`{ id: id, value: currencies[id] })` or `{id: id, value: currencies[id]})`

2021-06-29 12:37 UTC, abhishek1234321 commented on src/app/core/services/recently-used-items.service.ts
> +      } else {
can remove all the else and at the end put `return of([])`

2021-07-05 05:58 UTC, merged