Fyle t 41fg8c
fylein/fyle-mobile-app2 pull request #462
Opened 2021-07-05 11:14 UTC by iamtarun1993

2021-07-22 12:09 UTC, iamtarun1993 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.scss
> +      background: $red;
We can't make this `background-color`...
In line no 42 we declared background: $pink-gradient-1;
which will remove background color and apply it as background image.

2021-07-23 04:58 UTC, iamtarun1993 commented
![Image from iOS (3)](https://user-images.githubusercontent.com/23378996/126738997-57162082-43ff-4fac-a417-1c3bccfaf8a2.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/23378996/126739009-9eb4cb0b-d23c-430f-ac68-9975a5532080.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/23378996/126739015-d32b7a19-d685-4897-b85f-7bd3f062db86.png)
![Image from iOS](https://user-images.githubusercontent.com/23378996/126739018-e4dadd0f-1913-4766-b4a7-fb38b9a4332f.png)

2021-07-23 13:33 UTC, Julias0 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +    background-color: rgba(0, 0, 0, 0.3);
move to `colors.scss`

2021-07-23 13:33 UTC, Julias0 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +type Images = Partial<{
Images -> Image

2021-07-23 13:34 UTC, Julias0 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +      map((isConnected) => {
move this inside subscribe

2021-07-23 13:39 UTC, Julias0 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.html
> +      <button type="submit" class="popup-alert--cta-button popup-alert--primary-cta popup-alert--primary-cta__{{primaryCta.type}} text-center"
[ngClass]="'popup-alert--primary-cta__'+primaryCta.type"

2021-07-23 13:40 UTC, Julias0 commented on src/app/fyle/fyle-routing.module.ts
> +    path: 'camera_overlay_1',
lets just remove this na

2021-07-23 13:47 UTC, Julias0 commented on src/app/fyle/capture-receipt/receipt-preview/receipt-preview.component.html
> +      <!-- <button *ngIf="mode === 'bulk'" type="button" class="receipt-preview--cta-button receipt-preview--secondary-cta text-center" (click)="addMore()">
🤔

2021-07-23 14:01 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/receipt-preview/receipt-preview.component.html
> +      <!-- <button *ngIf="mode === 'bulk'" type="button" class="receipt-preview--cta-button receipt-preview--secondary-cta text-center" (click)="addMore()">
Coming in V2.. keep this so easy to find later

2021-07-23 14:10 UTC, iamtarun1993 commented on src/app/fyle/fyle-routing.module.ts
> +    path: 'camera_overlay_1',
Will remove this in another PR

2021-07-23 16:00 UTC, Julias0 approved these changes

2021-07-27 03:29 UTC, abhishek1234321 requested changes

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +    setTimeout(() => {
not understanding this

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +        Asset: 'Mobile'
let us please make this common

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +        this.router.navigate(['/', 'enterprise', 'my_expenses']);
confirm this with Aditi?

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +        source: 'MOBILE_SINGLE',
is this per the new or the old convention?

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +    this.imagePicker.hasReadPermission().then((permission) => {
what happens when permissions are

- denied
- not present

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +          quality: 50
if we make it 70, what would the size increase to? and what is at 50?

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +          if (imageBase64Strings.length > 0) {
`imageBase64Strings` will this be an `[]` always?

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/receipt-preview/receipt-preview.component.html
> +        <mat-icon class="fy-icon-close" svgIcon="fy-delete" ></mat-icon>
`svgIcon="fy-delete"></mat-icon>`

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/receipt-preview/receipt-preview.component.html
> +      <ng-container *ngFor="let base64ImageWithSource of base64ImagesWithSource">
track by?

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/receipt-preview/receipt-preview.component.scss
> +    height: 28px;
a lot of these should be reused

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/receipt-preview/receipt-preview.component.ts
> +    this.sliderOptions = {
what is this for?

2021-07-27 03:29 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/receipt-preview/receipt-preview.component.ts
> +    const {data} = await closePopOver.onWillDismiss();
merge with master and fix lint issues

2021-07-27 05:31 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt-routing.module.ts
> +    component: CaptureReceiptPage
In ionic everything is page/component.
This got added by default. We need to run only this command to add pag
`ionic g page abc` -> This will create `abcPage`
https://ionicframework.com/docs/cli/commands/generate

2021-07-27 05:46 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +    bottom: 50%;
<img width="317" alt="Screenshot 2021-07-27 at 11 16 03 AM" src="https://user-images.githubusercontent.com/23378996/127102044-ed2bd45e-d9d6-449b-9fe1-49e0cac5ad79.png">
We need to show this at middle of the screen

2021-07-27 05:47 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +    line-height: 1.3;
This is text inside the switch mode block.. so line height needed

2021-07-27 05:50 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +    margin-top: auto;
<img width="443" alt="Screenshot 2021-07-27 at 11 19 45 AM" src="https://user-images.githubusercontent.com/23378996/127102380-28310d64-b6e2-40b6-a45a-8bfd698c20f5.png">
We need to position the gallery icon and bulk mode icon at the bottom of the div compare to the middle block..
so need margin-top auto

2021-07-27 05:51 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +    line-height: 1.26;
text needed line height

2021-07-27 05:52 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +    letter-spacing: -0.3px;
Yes it helps, other wise width of this area getting increased

2021-07-27 05:54 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +    background: $pink-gradient-3;
We can't make this background-color, this is linear-gradient
`$pink-gradient: linear-gradient(137.88deg, $brand-primary 14.22%, $brand-primary-light 85.5%);`

2021-07-27 06:13 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +const {CameraPreview} = Plugins;
This is ok, will not create any issue of this placemnet.

2021-07-27 06:17 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +        billable: false,
Copied from old app.

2021-07-27 06:17 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +        amount: null,
Same copied from old app

2021-07-27 06:18 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +      attachmentUrls.push(attachment);
in transactionOutBox service we can add multiple files for a single txn

2021-07-27 06:21 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +    if (this.isCameraShown === true) {
In the browser when you refresh this page, the camera is already started, so no need to start again for setUpAndStartCamera() method.,  to stop the camera in the browser we need to do this.
In android /iOS devices all time always this will be true.

2021-07-27 06:22 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +        Asset: 'Mobile',
Will fix it another PR.

2021-07-27 06:22 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +    setTimeout(() => {
show "Bluk Mode" or "Single Mode" for 1 sec.

2021-07-27 06:25 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +        this.router.navigate(['/', 'enterprise', 'my_expenses']);
<img width="549" alt="Screenshot 2021-07-27 at 11 54 35 AM" src="https://user-images.githubusercontent.com/23378996/127106020-5c17e0d6-5c01-4db7-a595-0fd4e8dfeb9e.png">
Yes it will take user to my exp list page

2021-07-27 06:25 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +        source: 'MOBILE_SINGLE',
new convention

2021-07-27 06:26 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +    this.imagePicker.hasReadPermission().then((permission) => {
```this.imagePicker.requestReadPermission();
        this.galleryUpload();
        ```
        check line no 287

2021-07-27 06:28 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +          if (imageBase64Strings.length > 0) {
yes, always an array
https://github.com/Telerik-Verified-Plugins/ImagePicker#using-the-plugin

2021-07-27 07:17 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/receipt-preview/receipt-preview.component.html
> +      <ng-container *ngFor="let base64ImageWithSource of base64ImagesWithSource">
No trackBy, we use index here

2021-07-27 07:20 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/receipt-preview/receipt-preview.component.ts
> +    this.sliderOptions = {
For the sliding feature of images and pinch zoom, we need to pass these options.
https://ionicframework.com/docs/api/slides#custom-animations

2021-07-27 10:32 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +      display: flex;
added `--camera-pointer-container__common` class

2021-07-27 15:17 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +          quality: 50
We used 50 for the older app, and the new app camera-overlay page also...and working fine for 50

2021-07-27 15:18 UTC, abhishek1234321 approved these changes

2021-07-27 15:18 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +    position: absolute;
you need to use translate refer this https://css-tricks.com/centering-css-complete-guide/

2021-07-27 15:18 UTC, abhishek1234321 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +    line-height: 1.26;
line-height is needed usually when the text is multi-line no?

2021-07-28 04:46 UTC, iamtarun1993 commented on src/app/fyle/capture-receipt/capture-receipt.page.scss
> +    line-height: 1.26;
https://stackoverflow.com/a/4517177/8527342

2021-07-28 07:15 UTC, merged