Fyle 4bbmph - Ionic App flow Intergration
fylein/fyle-mobile-app2 pull request #486
Opened 2021-07-19 06:28 UTC by iravisankar

Added android folder
Added hooks for automate the build setup
Integration with Appflow for automate releases

2021-07-19 08:29 UTC, abhishek1234321 requested changes

2021-07-19 08:29 UTC, abhishek1234321 commented on android/app/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
compare the file with @tarunkumarfyle

2021-07-19 08:29 UTC, abhishek1234321 commented on .npmrc
> +unsafe-perm=true
@Julias0 could you check if there are any security implications

2021-07-19 08:29 UTC, abhishek1234321 commented on android/app/build.gradle
> +        applicationId "com.ionicframework.fyle595781.staging"
@iravisankar to take care of this

2021-07-19 08:29 UTC, abhishek1234321 commented on android/app/src/main/assets/capacitor.config.json
> +{
same as earlier

2021-07-19 08:29 UTC, abhishek1234321 commented on hooks/build.js
> +const fs = require('fs');
node version 14 and above

2021-07-19 08:29 UTC, abhishek1234321 commented on hooks/build.js
> +    if (!ctx.build.platform == 'android') return;
`{return;}`

2021-07-19 08:29 UTC, abhishek1234321 commented on hooks/build.js
> +module.exports = function (ctx) {
write code comments

2021-07-19 08:29 UTC, abhishek1234321 commented on hooks/build.js
> +    if (!ctx.build.platform == 'android') return;
`if (ctx.build.platform === 'android')`

2021-07-19 08:29 UTC, abhishek1234321 commented on hooks/build.js
> +        "android.cameraPreview": ctx.project.dir+"/node_modules/@capacitor-community/camera-preview/android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java"
use template strings `${}`

2021-07-19 08:29 UTC, abhishek1234321 commented on hooks/build.js
> +    {
import this

2021-07-19 08:29 UTC, abhishek1234321 commented on hooks/prebuild.js
> +const fs = require('fs');
Sentry source map stuff to be taken care of and pass the commit id in the `main.ts`

2021-07-19 08:29 UTC, abhishek1234321 commented on hooks/preserve.js
> +const fs = require('fs');
not needed

2021-07-19 08:29 UTC, abhishek1234321 commented on hooks/build.js
> +const fs = require('fs');
figure out a way to build staging connected and prod connected APK

2021-08-02 15:08 UTC, Julias0 approved these changes

2021-08-02 15:12 UTC, merged