Change Toast message designs
fylein/fyle-mobile-app2 pull request #538
Opened 2021-08-11 10:32 UTC by yksolanki9

Click [here](https://www.notion.so/fyleuniverse/Toast-messages-redesign-9b5feacfbd4642e58301df8372437161) to see design changes

2021-08-11 11:28 UTC, Dimple16 commented on src/assets/svg/tick-square-filled.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
remove height and width in svg

2021-08-11 11:29 UTC, Dimple16 commented on src/app/fyle/my-profile/my-profile.page.ts
> +
remove extra line

2021-08-11 11:30 UTC, Dimple16 commented on src/assets/svg/warning-white.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
remove height and width

2021-08-11 11:31 UTC, Dimple16 commented on src/global.scss
> +  margin-bottom: 30px !important;
`margin: 0 16px 30px 16px !important;`

2021-08-11 11:32 UTC, Dimple16 commented on src/global.scss
> +  background-color: #24A148;
this color is there in `theme/colors.scss`, use `$green`

2021-08-11 11:36 UTC, Dimple16 requested changes
few comments

2021-08-11 12:01 UTC, Dimple16 approved these changes

2021-08-11 12:05 UTC, Julias0 commented on src/assets/svg/warning-white.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M12.0647 3.70174L18.122 14.2143C18.2553 14.5281 18.3137 14.7833 18.3303 15.0484C18.3636 15.6677 18.147 16.2696 17.7221 16.7329C17.2972 17.1945 16.7223
this looks like a duplicated svg of warning.svg

Remove off the color and assign it via css everywhere

2021-08-11 12:06 UTC, Julias0 commented on src/app/shared/icon/icon.module.ts
> +    'warning-inverted.svg', 'warning-white.svg', 'warning.svg'
we shouldnt have multiple svgs with different colors. Assign different colors externally via css

2021-08-11 12:07 UTC, Julias0 commented on src/app/post-verification/invited-user/invited-user.page.ts
> +        data: {
create a factory function to generate these configuration objects. A lot of these properties are duplicated and can be reduced by setting default values in the arguments of the factory function

2021-08-11 12:09 UTC, Julias0 requested changes
fix and send back

2021-08-12 06:17 UTC, Julias0 commented on src/global.scss
> +  color: #E1AF05 !important;
reference colors from colors.scss file

2021-08-12 06:18 UTC, Julias0 commented on src/app/shared/components/toast-message/toast-message.component.html
> +    <mat-icon *ngIf="data.icon" class="toast-message--left-icon color-white" svgIcon="{{data.icon}}"></mat-icon>
adding classes like `color-white` dosnt follow proper BEM convention.Please update this correspondingly

2021-08-12 06:18 UTC, Julias0 commented on src/app/shared/components/fy-alert-info.component.html/fy-alert-info.component.html
> +  <mat-icon *ngIf="type === 'warning'" class="alert-info-container--icon color-danger-yellow" svgIcon="danger"></mat-icon>
Dosnt follow BEM

2021-08-12 06:20 UTC, Julias0 commented on src/app/core/services/snackbar-properties.service.ts
> +    if(data.icon === 'danger') {
use a ternary operator to set the class to a variable.
Otherwise there is too much duplication

2021-08-12 06:21 UTC, Julias0 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      return;
dont use return to break out of function blocks. Have an explicit else portion

2021-08-12 06:40 UTC, yksolanki9 commented on src/app/shared/components/toast-message/toast-message.component.html
> +    <mat-icon *ngIf="data.icon" class="toast-message--left-icon color-white" svgIcon="{{data.icon}}"></mat-icon>
will `icon--white` work?

2021-08-13 05:30 UTC, Julias0 commented on src/app/core/services/snackbar-properties.service.ts
> +    return { data: {...data, showCloseButton: true}, panelClass: [ 'mat-snack-bar', data.icon === 'danger' ? 'msb-failure' : 'msb-success',
make this multiline

2021-08-13 05:30 UTC, Julias0 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      .setSnackbarProperties({ icon: 'danger', message, redirectionText: null }, ['msb-with-report-button'], 3000));
multiline everywhere

2021-08-13 05:31 UTC, Julias0 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +            // eslint-disable-next-line max-len
do not disable lint issues. Please fix them properly

2021-08-13 05:31 UTC, Julias0 commented on src/app/core/services/snackbar-properties.service.ts
> +import { Injectable } from '@angular/core';
The lint check is missing. Please make sure that linting gives green before raising PR

2021-08-13 05:35 UTC, yksolanki9 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +            // eslint-disable-next-line max-len
I did not add it. It was there already. Should I remove it?

2021-08-16 10:19 UTC, abhishek1234321 requested changes

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/core/services/snackbar-properties.service.ts
> +        data.icon === 'danger' ? 'msb-failure' : 'msb-success',
make it more readable

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/core/services/snackbar-properties.service.ts
> +  setSnackbarProperties(data: { icon: string; message: string; redirectionText: string },
write code comments? multi line

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +        redirectionText: null },
`ng lint`?

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    this.matSnackBar.openFromComponent( ToastMessageComponent,
add mixpanel event

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +  async openCreateReportWithSelectedIds(report_type: 'oldReport' | 'newReport') {
camelCase please

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    if(!selectedElements.length) {
`if (!selectedElements.length) {`

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      this.trackingService.addToReport({ Asset: 'Mobile' });
we should not be defining this everywhere

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      if ((noOfExpensesWithCriticalPolicyViolations > 0) || (noOfExpensesInDraftState > 0)) {
`if (noOfExpensesWithCriticalPolicyViolations > 0 ||`

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      this.snackbarProperties.setSnackbarProperties({icon: 'tick-square-filled', message: config.message, redirectionText: 'View Report'},
`...` try?

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +          icon: 'tick-square-filled',
we shouldn't be building the object everywhere

2021-08-16 10:19 UTC, abhishek1234321 commented on src/app/post-verification/invited-user/invited-user.page.ts
>          message: 'Please fill all required fields to proceed',
message needs changning

2021-08-17 16:50 UTC, Dimple16 commented on src/theme/colors.scss
> +$dark-yellow: #e1af05;
`!default`

2021-08-17 16:52 UTC, Dimple16 commented on src/app/core/services/snackbar-properties.service.ts
> +  /*
use this format for multi-line comments - https://tsdoc.org/

2021-08-17 16:53 UTC, Dimple16 commented on src/app/core/services/tracking.service.ts
> +  onDisplayToastMessage(properties) {
`showToastMessage`

2021-08-17 17:00 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    if(!selectedElements.length) {
this is not fixed

2021-08-17 17:02 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      this.trackingService.addToReport({ Asset: 'Mobile' });
this will be fixed across the app in a different pr

2021-08-17 17:10 UTC, Dimple16 commented on src/global.scss
> +  margin: 0 16px 30px 16px !important;
`margin: 0 16px 30px !important;`

2021-08-17 17:11 UTC, Dimple16 commented on src/global.scss
> +  margin: 0 16px 30px 16px !important;
`margin: 0 16px 30px !important;`

2021-08-17 17:11 UTC, Dimple16 commented on src/global.scss
> +  margin: 0 16px 133px 16px !important;
margin: 0 16px 133px !important;

2021-08-17 17:11 UTC, Dimple16 commented on src/global.scss
> +  margin: 0 16px 133px 16px !important;
`margin: 0 16px 133px !important;`

2021-08-17 17:12 UTC, Dimple16 commented on src/global.scss
> +  margin: 0 16px 96px 16px !important;
`margin: 0 16px 96px !important;`

2021-08-17 17:13 UTC, Dimple16 commented on src/global.scss
> +.icon--white {
`.icon-alert-warning`

2021-08-17 17:13 UTC, Dimple16 commented on src/global.scss
> +.icon--dark-yellow {
`.icon-toast-danger`

2021-08-17 17:18 UTC, Dimple16 requested changes
few comments

2021-08-18 16:49 UTC, Dimple16 commented on src/app/core/services/snackbar-properties.service.ts
> +   *
remove blank line

2021-08-18 16:56 UTC, Dimple16 approved these changes

2021-08-19 06:40 UTC, Julias0 commented on src/app/core/services/snackbar-properties.service.ts
> +  setSnackbarProperties(toastMessageType: string, toastMessageData: {message: string; redirectiontext?: string}) {
toastMessageType: string -> toastMessageType : 'success' | 'danger'

2021-08-19 15:40 UTC, Julias0 approved these changes

2021-08-20 04:51 UTC, abhishek1234321 approved these changes

2021-08-20 05:07 UTC, merged