Fix camera options popup design
fylein/fyle-mobile-app2 pull request #586
Opened 2021-08-26 13:36 UTC by yksolanki9

Before:
![localhost_8100_enterprise_my_dashboard(Moto G4) (17)](https://user-images.githubusercontent.com/39493102/130972265-204e6cd2-e1c7-424d-9c5d-a68f3c705cbc.png)

After:
![localhost_8100_enterprise_add_edit_expense;id=txCbAa8cEtsp;persist_filters=true(Moto G4) (4)](https://user-images.githubusercontent.com/39493102/130972285-2fc8cc52-dc2f-4fdf-b6a3-23a3cc659f24.png)

2021-08-27 09:20 UTC, Dimple16 requested changes
few comments

2021-08-30 05:20 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.scss
> +    line-height: 23px;
verify the line height in Figma

2021-08-30 05:21 UTC, Dimple16 approved these changes

2021-08-30 11:35 UTC, Julias0 approved these changes

2021-09-02 22:04 UTC, merged