Add discard comments popup and cancel cta in edit expenses
fylein/fyle-mobile-app2 pull request #599
Opened 2021-08-31 15:32 UTC by yksolanki9

Discard comments popup:
https://user-images.githubusercontent.com/39493102/131531709-5be2f253-5b04-4c9b-9f04-24005216ea83.mp4

Cancel cta in edit expenses:
https://user-images.githubusercontent.com/39493102/131531808-b581955e-68ea-464a-b91e-9a9e1daff912.mp4

2021-08-31 18:01 UTC, Dimple16 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.scss
> +    padding: 14px 16px 14px 16px;
padding: 14px 16px;

2021-08-31 18:02 UTC, Dimple16 commented on src/app/shared/components/comments-history/view-comment/view-comment.component.ts
> +        this.trackingService.viewComment({ Asset: 'Mobile' });
remove `Asset: 'Mobile'`

2021-08-31 18:02 UTC, Dimple16 commented on src/app/shared/components/comments-history/view-comment/view-comment.component.ts
> +        this.trackingService.addComment({ Asset: 'Mobile' });
same as above

2021-08-31 18:03 UTC, Dimple16 requested changes
few comments

2021-09-01 09:42 UTC, yksolanki9 commented on src/app/shared/components/comments-history/view-comment/view-comment.component.ts
> +        this.trackingService.viewComment({ Asset: 'Mobile' });
These change have been taken care of in another pr

2021-09-01 10:41 UTC, Dimple16 approved these changes

2021-09-02 22:06 UTC, merged