Update reports and team-reports zero state
fylein/fyle-mobile-app2 pull request #614
Opened 2021-09-02 21:16 UTC by yksolanki9

Reports
Before:
![localhost_8100_enterprise_my_reports_filters=%7B%7D(iPhone 6_7_8 Plus) (3)](https://user-images.githubusercontent.com/39493102/131916761-791a9332-b9b2-406a-8a9c-5de8b3ffe617.png)

After:
![localhost_8100_enterprise_my_reports_filters=%7B%7D(iPhone 6_7_8 Plus) (1)](https://user-images.githubusercontent.com/39493102/131916695-f33c318b-4390-4f76-abde-2e03986cbf20.png)

Team reports:
Before:
![localhost_8100_enterprise_my_reports_filters=%7B%7D(iPhone 6_7_8 Plus) (2)](https://user-images.githubusercontent.com/39493102/131916642-07ee5bca-28d1-4691-8dd5-82789806b3f0.png)

After:
![localhost_8100_enterprise_team_reports_filters=%7B%7D(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/39493102/131916628-44a3b2b6-5ddb-4044-a834-6bc9653105c5.png)

2021-09-06 05:53 UTC, Dimple16 commented on src/app/fyle/team-reports/team-reports.page.html
> +    <ion-title mode="md" class="page-title"> Reports - Team </ion-title>
should be `Team Reports`

2021-09-06 05:54 UTC, Dimple16 commented on src/app/fyle/team-reports/team-reports.page.html
> +        header="No Reports found !"
I guess the content here is not updated based on new design, can you verify this - https://www.figma.com/file/7QTRyXwGZWWG8BCwcTAzob/%5BMobile%5D-Reports?node-id=705%3A125180

2021-09-06 05:55 UTC, Dimple16 requested changes
few comments

2021-09-14 05:17 UTC, yksolanki9 commented
Merged with other pr

2021-09-14 05:17 UTC, closed without merging