Fyle b9pznb Personal cards - Navigation bars and Zero states
fylein/fyle-mobile-app2 pull request #643
Opened 2021-09-14 09:51 UTC by iravisankar

![localhost_8100_enterprise_personal_cards(iPhone X)](https://user-images.githubusercontent.com/86199056/133236109-00aa949b-2961-4270-886a-8f6768bc505d.png)

2021-09-14 16:16 UTC, Dimple16 commented on src/app/core/services/personal-cards.service.ts
> +  getLinkedAccounts(): Observable<any> {
can we use a model here? instead of `any`?

2021-09-14 16:20 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.html
> +  <ng-container  *ngIf="((linkedAccountsCount$ | async) === 7) && isConnected$|async" >
`(linkedAccountsCount$ | async) === 7)` is this intentional?

2021-09-14 16:21 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.scss
> +    border-bottom: 1px solid #e6e6e6;
we can use `$grey-lightest`

2021-09-14 16:22 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.scss
> +    color: #4a4a4a;
let us add `#4a4a4a` to colors.scss

2021-09-14 16:23 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.scss
> +
remove extra lines

2021-09-14 16:25 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.scss
> +    width: fit-content;
need to check if this works on devices properly

2021-09-14 16:26 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +  linkedAccounts$: Observable<any>;
can use linked accounts model

2021-09-14 16:27 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.scss
> +      opacity: 0.8;
we aren't disabling cta buttons across the app, in case we do, is this intentional by design?

2021-09-14 16:28 UTC, Dimple16 requested changes
few comments

2021-09-16 05:12 UTC, iravisankar commented on src/app/fyle/personal-cards/personal-cards.page.scss
> +    width: fit-content;
its used in my expenses page

2021-09-21 07:20 UTC, Julias0 commented on src/app/core/services/personal-cards.service.ts
> +  postBankAccounts(request_ids): Observable<any> {
request_ids -> requestIds

2021-09-21 07:20 UTC, iravisankar commented on src/app/app.component.ts
> +        isVisible: environment.ROOT_URL === 'https://staging.fyle.tech',
Just to show personal cards only on staging ...

2021-09-21 07:21 UTC, Julias0 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +    this.linkedAccountsCount$ = this.personalCardsService.getLinkedAccountsCount().pipe(
this.loadCount$.pipe(
  switchMap(()=> this.personalCardsService.getLinkedAccountsCount()),
  shareReplay(1)
)

recommending this because we have use this pattern everywhere and don't want it to change unless required

2021-09-21 08:10 UTC, merged