Update Add Approver Modal
fylein/fyle-mobile-app2 pull request #644
Opened 2021-09-14 11:28 UTC by yksolanki9

Uploading Ionic App (27).mp4…

2021-09-14 15:42 UTC, Dimple16 commented
Few comments from the video
- The parent pop over should have a top and right bottom radius
- Let us set the minimum approvers displayed in the list to 3
- The parent pop over header should have the same design as the select approvers modal
 - The cancel icon should be the `fy-close` svg
 - The save button should have the `$primary` color
 - It should have a bottom border
- Verify the chips height and inner padding in Figma

2021-09-14 15:43 UTC, Dimple16 commented on src/theme/colors.scss
> +$red-3: #ff3366 !default;
this is defined as `$primary` , we can use the same one

2021-09-14 15:47 UTC, Dimple16 commented on src/app/shared/components/fy-apporver/add-approvers-popover/approver-dialog/approver-dialog.component.scss
> +    color: #ababab;
use `$gray-3`

2021-09-14 15:48 UTC, Dimple16 commented on src/app/shared/components/fy-apporver/add-approvers-popover/approver-dialog/approver-dialog.component.scss
> +    border-bottom: 1px solid #e0e0e0;
define this color in the colors.scss

2021-09-14 15:48 UTC, Dimple16 commented on src/app/shared/components/fy-apporver/add-approvers-popover/approver-dialog/approver-dialog.component.scss
> +    color: $red-3;
use `$primary`

2021-09-14 15:53 UTC, Dimple16 commented on src/app/shared/components/fy-apporver/add-approvers-popover/add-approvers-popover.component.ts
> +  @Input() from;
can we change this to type? `this.type === 'Trips'` etc

2021-09-14 15:54 UTC, Dimple16 commented on src/app/shared/components/fy-apporver/add-approvers-popover/add-approvers-popover.component.ts
> +      backdropDismiss: false
`backdropDismiss` is added as true by default in the properties, any reason we are disabling this?

2021-09-14 15:55 UTC, Dimple16 commented on src/app/shared/components/fy-apporver/add-approvers-popover/add-approvers-popover.component.ts
> +      if(this.selectedApproversList.length > 2) {
`this.selectedApproversList && this.selectedApproversList.length > 2`

2021-09-14 15:58 UTC, Dimple16 requested changes
added comments

2021-09-22 13:36 UTC, Julias0 commented on src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.ts
> +type approverModel = {
approverModel -> Approver

2021-09-22 13:36 UTC, Julias0 approved these changes

2021-09-22 16:29 UTC, yksolanki9 commented on src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.ts
> +type approverModel = {
Done

2021-09-24 06:34 UTC, merged