Edit Report Name flow
fylein/fyle-mobile-app2 pull request #667
Opened 2021-09-22 09:10 UTC by yksolanki9

https://user-images.githubusercontent.com/39493102/134315994-d8bdf23f-6ce6-4604-9271-35231cb2babf.mp4

2021-09-22 12:12 UTC, Dimple16 commented
few comments:
- The icon color should be `$primary`
- Let us add a left margin to the icon temporarily - It looks very near to the name
- Edit name header in the pop up is not center-aligned
- Aren't we showing an error message if the report name is erased completely?

2021-09-22 12:16 UTC, Dimple16 requested changes
resolve conflict

2021-09-29 09:59 UTC, Dimple16 approved these changes

2021-10-02 07:28 UTC, Julias0 commented on src/app/core/services/report.service.ts
> +      .pipe(switchMap((res) => this.clearTransactionCache().pipe(map(() => res))));
this.clearTransactionCache() - do this inside a tap

2021-10-02 07:30 UTC, Julias0 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      from(this.loaderService.showLoader())
extract the content inside the if into a function

2021-10-02 07:30 UTC, Julias0 approved these changes

2021-10-04 13:30 UTC, merged