FYLE-cqkpw9: Fixed purpose field error alignment in per diem page
fylein/fyle-mobile-app2 pull request #670
Opened 2021-09-22 10:47 UTC by MasterYushi

### Before
![image](https://user-images.githubusercontent.com/24858182/134330394-027c29dd-7151-414d-bd22-52c8072d8baa.png)

### After
![image](https://user-images.githubusercontent.com/24858182/134330452-d86a8b07-4fa7-49f7-9163-cf8df6273938.png)

2021-09-22 12:39 UTC, abhishek1234321 requested changes

2021-09-22 12:39 UTC, abhishek1234321 commented on src/global.scss
> +.mt-1 {
I would like us to avoid this, since we may not reuse this a lot

2021-09-23 07:57 UTC, MasterYushi commented on src/global.scss
> +.mt-1 {
The only other way would be to add inline styles. Do you want me to do that?

2021-09-23 11:35 UTC, MasterYushi commented on src/global.scss
> +.mt-1 {
@abhi The only other way would be to add inline styles. Do you want me to do that?

2021-09-23 11:37 UTC, MasterYushi commented on src/global.scss
> +.mt-1 {
> I would like us to avoid this, since we may not reuse this a lot

@abhishek1234321 The only other way would be to add inline styles. Do you want me to do that?

2021-10-19 05:10 UTC, Dimple16 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
> +                          style="margin-top: 4px"
@MasterYushi add a class like `add-edit-per-diem--purpose-error` in the scss class, we don't use inline-styles

2021-10-19 08:48 UTC, Dimple16 approved these changes

2021-10-20 06:54 UTC, merged