Added changes to add support for tasks
fylein/fyle-mobile-app2 pull request #671
Opened 2021-09-22 12:31 UTC by Julias0

2021-09-22 12:33 UTC, Julias0 commented on src/app/core/models/task.model.ts
> +	header: string;
the spacing is showing incorrectly here for some reason

2021-09-22 12:34 UTC, Julias0 commented on src/app/core/models/task-event.enum.ts
> +	expensesAddToReport,
spacing showing incorrectly here - checked in file, spacing is proper there

2021-09-22 12:36 UTC, Julias0 commented on src/app/core/services/tracking.service.ts
> +  async tasksFiltersApplied(properties = {}) {
will raise a separate PR with all tracking stuff - this PR has become a bit big

2021-09-23 04:03 UTC, abhishek1234321 requested changes

2021-09-23 06:41 UTC, Julias0 commented on src/app/core/services/report.service.ts
> +      this.userEventService.clearTaskCache();
The task cache is just the count values. This recalculates the values to show the proper count values everywhere

Rest of the stuff we don't store in taskcache since we are getting those from transactions and reports wala stats / v2 endpoints so their cache is in transaction & reports

2021-09-23 06:44 UTC, Julias0 commented on src/app/core/services/tasks.service.ts
> +      homeCurrency: this.offlineService.getHomeCurrency()
I will checkout the resolvers separately - I think it can be used in a lot of places

2021-09-23 06:47 UTC, Julias0 commented on src/app/fyle/dashboard/tasks/tasks.component.ts
> +      this.transactionService.clearCache(),
The tasks are created from expenses and reports services via the v2 / stats wala endpoints and those methods are cached there directly. On pull to reload I need to clear them otherwise the tasks will come up from the cache only

2021-09-23 06:57 UTC, Julias0 commented on src/app/core/services/report.service.ts
> +            rp_org_user_id: `eq.${eou.ou.id}`,
If I switch to person A's account via switch to delegate, I will see persons A's tasks in the task pane.
Verfied this in app - the behavior is proper

2021-09-25 05:26 UTC, abhishek1234321 approved these changes

2021-10-04 08:22 UTC, closed without merging