Fyle-chqc37 linked cards on personal cards
fylein/fyle-mobile-app2 pull request #676
Opened 2021-09-23 06:18 UTC by iravisankar

![localhost_8100_(Pixel 2 XL)](https://user-images.githubusercontent.com/86199056/134462058-6de40780-8f39-48b0-8619-a06a7987ba94.png)
![localhost_8100_(Pixel 2 XL) (1)](https://user-images.githubusercontent.com/86199056/134462075-51ccb99c-310f-4869-bba8-242ed86912e2.png)
![localhost_8100_(iPhone X)](https://user-images.githubusercontent.com/86199056/134462092-24886751-4943-486b-a0cb-b2caa2f57a71.png)

2021-09-23 19:35 UTC, Julias0 commented on src/app/fyle/personal-cards/personal-cards.page.html
> +        header="You're Offline!"
lets double check the content with team product management

2021-09-23 19:36 UTC, Julias0 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +      tap(() => {
do this in finalize

2021-09-23 19:37 UTC, Julias0 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.scss
> +    letter-spacing: -0.005em;
nei nei dont have this, no negative letter spacing

2021-09-23 19:38 UTC, Julias0 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
> +  styles: [
move to separate files both the template and the styles

2021-09-28 19:51 UTC, Julias0 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +          finalize(() => {
bring the finalize on the same level as the switchMap

2021-09-28 19:53 UTC, Julias0 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +      `<form id="fastlink-form" name="fastlink-form" action="` +
move the html into a service if possible.
Convert it into a function 

Also use string interpolation

getPageContent = function (url, accessToken) {
  return  `<form id="fastlink-form" name="fastlink-form" action="${url}" method="POST"> .....`
}

2021-09-28 19:55 UTC, Julias0 commented on src/app/fyle/personal-cards/personal-cards.page.ts
>    ngOnInit() {
if the network goes offline the page should redirect to dashboard similar to reports, advances etc pages

2021-09-28 19:55 UTC, Julias0 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +  isLoading = true;
where is `isLoading` used? I cant see any reference to this in the html

2021-09-28 19:58 UTC, Julias0 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
> +    this.deletecardPopOver = await this.popoverController.create({
this looks a little hacky. Can we discuss this on a call?

2021-09-28 19:58 UTC, Julias0 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
> +    this.deletecardPopOver = await this.popoverController.create({
we can discuss this while in the standup

2021-10-02 07:32 UTC, Julias0 commented on src/app/core/services/personal-cards.service.ts
> +  htmlFormUrl(url, access_token) {
access_token -> accessToken

2021-10-02 07:32 UTC, Julias0 commented on src/app/core/services/personal-cards.service.ts
> +  htmlFormUrl(url, access_token) {
And define data type for passed in props and return type

2021-10-02 07:32 UTC, Julias0 commented on src/app/core/services/personal-cards.service.ts
> +  getToken(): Observable<any> {
dont use any

2021-10-02 07:33 UTC, Julias0 commented on src/app/core/services/personal-cards.service.ts
> +  deleteAccount(accountid): Observable<any> {
dont use any.
Also mention datatype of accounted
accountid -> accountId

2021-10-02 07:36 UTC, Julias0 commented on src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
> +      return '<span class="fyle ' + className + '"> </span>';
```typescript
return  `<span class="fyle${className}"> </span>`
```

Use template strings

2021-10-02 07:36 UTC, Julias0 approved these changes

2021-10-04 09:29 UTC, abhishek1234321 requested changes

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
> +        message: 'Are you want to delete this card ?',
`Are you sure`

please to check in all places?

`card?`

2021-10-04 09:29 UTC, abhishek1234321 commented on android/app/src/main/assets/capacitor.config.json
> +	"appId": "com.ionicframework.fyle595781",
indentation is off

2021-10-04 09:29 UTC, abhishek1234321 commented on package.json
> +    "cordova-plugin-inappbrowser": "^5.0.0",
are we upgrading it? If yes, shouldn't this be a different release altogether?

2021-10-04 09:29 UTC, abhishek1234321 commented on package.json
> +    "swiper": "^7.0.6",
could we not use https://ionicframework.com/docs/api/slides

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +  constructor(private apiv2Service: ApiV2Service, private expenseAggregationService: ExpenseAggregationService) {}
better to write in multi line no? do we not have an eslint rule for this?

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +    const pageContent = `<form id="fastlink-form" name="fastlink-form" action="${url}" method="POST">
Could we not put it in the HTML template?

also do we need to use this `document.getElementById("fastlink-form").submit();` or could we submit via Angular?

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +  deleteAccount(accountId: string): Observable<PersonalCard> {
deleteCard or account?

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/fyle/personal-cards/personal-cards.page.html
> +  <ng-container *ngIf="((linkedAccountsCount$ | async) !== 0) && (isConnected$|async)">
`> 0` for readability

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +    this.isConnected$.subscribe((isOnline) => {
when would this be needed?

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +      .subscribe((accessToken) => {
yodleeConfig or something?

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +      .subscribe((accessToken) => {
also type?

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +      if (event.url.substring(0, 22) === 'https://www.fylehq.com') {
could you put code comments on what this is about?

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +    from(this.loaderService.showLoader('Linking your card to Fyle...', 30000))
`Linking your card with Fyle...` please confirm with Harman and @gokulk16

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.html
> +<div class="perosnal-card--card-details">
`personal`

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.scss
> +    background: url('../../../../../assets/images/personal-card-bg.png') no-repeat bottom;
we can specify size here I think instead of another `background-size` property

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.scss
> +    font-weight: bold;
`700` could we use a utility class?

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.scss
> +    padding-top: 0;
use a utility class?

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
> +    from(this.loaderService.showLoader('Deleting your card..', 5000))
`...`

2021-10-04 09:29 UTC, abhishek1234321 commented on src/app/shared/components/bank-account-cards/bank-account-card/delete-button/delete-button-component.html
> +  <ion-icon src="assets/svg/delete.svg" class="delete-button--icon" slot="icon-only"></ion-icon> Delete Card
should we say `Delete` or `Remove` check with Shubhangi and Kavya?

2021-10-04 09:51 UTC, Julias0 commented on src/app/core/services/personal-cards.service.ts
> +  constructor(private apiv2Service: ApiV2Service, private expenseAggregationService: ExpenseAggregationService) {}
Prettier automatically breaks into multiline above a certain length. I think this case this smalled that the breaking point

2021-10-14 06:54 UTC, iravisankar commented on src/app/core/services/personal-cards.service.ts
> +    const pageContent = `<form id="fastlink-form" name="fastlink-form" action="${url}" method="POST">
we just push Html to in-app browser,  Fastlink URL only  if we post access token via post method

2021-10-14 06:54 UTC, iravisankar commented on src/app/core/services/personal-cards.service.ts
> +  deleteAccount(accountId: string): Observable<PersonalCard> {
we are linking the bank accounts only

2021-10-14 06:54 UTC, iravisankar commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +    this.isConnected$.subscribe((isOnline) => {
if offline, it will redirect to the dashboard page

2021-10-14 06:54 UTC, iravisankar commented on src/app/shared/components/bank-account-cards/bank-account-card/delete-button/delete-button-component.html
> +  <ion-icon src="assets/svg/delete.svg" class="delete-button--icon" slot="icon-only"></ion-icon> Delete Card
Delete used in webapp

2021-10-14 09:08 UTC, merged