Add View Info Modal for Individual and Team reports
fylein/fyle-mobile-app2 pull request #684
Opened 2021-09-27 04:59 UTC by yksolanki9

2021-09-27 12:12 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +    } else if (paymentMode === 'ccc') {
add a comment beside every condition to tell what it means. Get help from Chethan for this

2021-09-27 12:12 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +  isEtxnInPaymentMode(etxn, paymentMode) {
etxn, paymentMode 
data types missing

2021-09-27 12:12 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +  getPaymentModeWiseSummary(etxns) {
etxns -> Data type missing

2021-09-27 12:17 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +      paymentModes.forEach((paymentMode) => {
you are grouping the etxns by payment mode? If yes, make etxns the inside loop.

And think of a way to avoid the nested loop.
Like - 
getPaymentModeForEtxn(etxn, paymentModes) {
  return paymentModes.find(paymentMode => this.isEtxnInPaymentMode(etxn, paymentMode.key));
}

etxns.map(etxn => { ...etxn,paymentModeKey: getPaymentModeForEtxn(etxn, paymentModes) } ).reduce(...figurethispartout....)

2021-09-27 12:18 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +  getCurrenyWiseSummary(etxns) {
data types. Add data types everywhere

2021-09-27 12:18 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +    etxns.forEach(function (etxn) {
same as above

2021-09-27 12:18 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +        if (currencyMap.hasOwnProperty(etxn.tx_orig_currency)) {
both parts look similar - see if you can reuse

2021-09-27 12:19 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +    return Object.keys(currencyMap)
add a few unit tests in the spec ts file for this method

2021-09-27 12:20 UTC, Julias0 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.html
> +<ion-content *ngIf="isReportView && !isEmployeeView" (swipe)="onSwipeReport($event)">
isReportView && !isEmployeeView -> put this inside a getter function

2021-09-27 12:22 UTC, Julias0 commented on src/app/shared/icon/icon.module.ts
> -    'fy-info.svg',
double check if this dosnt break anything pre existing

2021-09-27 12:26 UTC, Julias0 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +      this.orgUserService.getUserById(erpt.ou_id).subscribe((user) => {
have a method inside orgUserSettingsService

```typescript
getOrgUserSettingsById(ouId: string) {
  return this.orgUserService.getUserById(ou_id).pipe(
  switchMap(user =>this.orgUserSettingsService.getUserSettings(user.ou_settings_id))
  );
}

getAllowedCostCentersByOuId(ouId: string){
  return getOrgUserSettingsById(ouId).pipe(
   switchMap(orgUserSettings => this.orgUserSettingsService.getAllowedCostCenteres(orgUserSettings))
  )
}

```

2021-09-27 12:27 UTC, Julias0 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +      this.orgUserService.getUserById(erpt.ou_id).subscribe((user) => {
Very important rule - never have nested subscribes.

2021-09-27 12:28 UTC, Julias0 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +    this.erpt$.subscribe((erpt) => {
where is this.erpt$ being initialized?

2021-09-27 12:30 UTC, Julias0 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +              this.employeeDetails = {
extract to method

createEmployeeDetails(erpt: ExtendedReports,  allowedCostCenters: CostCenters[])

2021-09-27 12:30 UTC, Julias0 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +      this.erpt$.subscribe((erpt) => {
try to remove off this nested subscribe by yourself

2021-09-27 16:35 UTC, yksolanki9 commented on src/app/shared/icon/icon.module.ts
> -    'fy-info.svg',
It was defined twice. Hence removed it

2021-09-28 09:32 UTC, yksolanki9 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +    this.erpt$.subscribe((erpt) => {
It is input from parent component

2021-10-04 05:18 UTC, Dimple16 commented on src/app/core/services/org-user-settings.service.ts
> +import { finalize, map, switchMap } from 'rxjs/operators';
are we using `switchMap` anywhere?

2021-10-04 05:19 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> +  getPaymentModeForEtxn(etxn: Expense, paymentModes: any[]) {
create a `paymentMode` model and use it here

2021-10-04 05:23 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> +    return Object.keys(currencyMap)
@yksolanki9 are the unit tests added in this pr? if not, mention pr here if being taken care in the other pr

2021-10-04 05:25 UTC, Dimple16 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +        isTeamReport: false,
`view: 'Team' / 'Individual'`

2021-10-04 05:26 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +        isTeamReport: true,
same as above

2021-10-04 05:27 UTC, Dimple16 commented on src/app/shared/components/comments-history/view-comment/view-comment.component.ts
>    swipeRightToHistory(event) {
let us track the swipes too, @yksolanki9 can you please add trackers to know if users are using the swipes here

2021-10-04 05:29 UTC, Dimple16 commented on src/app/shared/components/comments-history/view-comment/view-comment.component.ts
>    swipeRightToHistory(event) {
can you also add trackers on the tab switch? basically, on click of comments and history, as the comments view is by default, we'll know how many of them are actually clicking on the history tab and vice versa

2021-10-04 05:30 UTC, Dimple16 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.html
> +    >
add trackers for segment switch, need to track usage of all tabs

2021-10-04 05:31 UTC, Dimple16 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.html
> +      <ion-segment-button *ngIf="isTeamReport" value="employee" class="view-info--segment-block-container__btn">
*ngIf="view"

2021-10-04 05:33 UTC, Dimple16 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.scss
> +      text-transform: capitalize;
use `text-capitalize` class - this is globally added

2021-10-04 05:33 UTC, Dimple16 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +  @Input() etxns$: Observable<any[]>;
any?

2021-10-04 05:34 UTC, Dimple16 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +        Owner: erpt.us_full_name,
is this intentional?

2021-10-04 05:35 UTC, Dimple16 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +  segmentChanged(event) {
add trackers for this

2021-10-04 05:37 UTC, Dimple16 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +  createEmployeeDetails(erpt: ExtendedReport) {
In the HTML, these details should be shown only when there is a value, ex: `Level : A1`, only if A1 is present we show Level section

2021-10-04 05:37 UTC, Dimple16 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +  createEmployeeDetails(erpt: ExtendedReport) {
can you verify this for all?

2021-10-04 05:37 UTC, Dimple16 requested changes
added comments

2021-10-04 12:31 UTC, yksolanki9 commented on src/app/core/services/transaction.service.ts
> +    return Object.keys(currencyMap)
Unit tests will be added in a separate pr. Clickup: https://app.clickup.com/t/dtz1df

2021-10-04 13:53 UTC, yksolanki9 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +  createEmployeeDetails(erpt: ExtendedReport) {
This check is there in html. Only keys with valid values are displayed `*ngIf="item && item.value && item.value.length`

2021-10-05 13:37 UTC, Dimple16 commented on src/app/core/services/tracking.service.ts
> +  //Reports
/* Use multi line comments */

2021-10-05 13:40 UTC, Dimple16 approved these changes

2021-10-11 10:54 UTC, iravisankar commented on src/app/fyle/my-view-report/my-view-report.page.html
> +          <mat-icon class="view-reports--view-info__icon" svgIcon="fy-info-gradient"></mat-icon>
use ion-icon

2021-10-11 10:54 UTC, iravisankar commented on src/app/fyle/view-team-report/view-team-report.page.html
> +          <mat-icon class="view-reports--view-info__icon" svgIcon="fy-info-gradient"></mat-icon>
use ion-icon

2021-10-19 04:58 UTC, Dimple16 approved these changes

2021-10-19 06:01 UTC, merged