Fyle-1rwunbh filters and fixes in personal cards
fylein/fyle-mobile-app2 pull request #733
Opened 2021-11-08 05:50 UTC by iravisankar

![localhost_8100_enterprise_personal_cards(iPhone X) (8)](https://user-images.githubusercontent.com/86199056/140690752-ec6be862-b371-4ffe-a204-d4d35bda2c9d.png)

2021-11-08 09:33 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    console.log(newQueryParams);
remove

2021-11-08 09:39 UTC, Dimple16 commented on src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.scss
> +    font-weight: normal;
this is by default

2021-11-08 09:40 UTC, Dimple16 commented on src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.scss
> +    font-size: 14px;
this is default font size, can be removed

2021-11-08 09:41 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.html
> +    <ion-toolbar mode="ios">
this should be device platform specific

2021-11-08 09:42 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.html
> +    <ion-toolbar mode="ios">
mode is not required here, it'll automatically display based on device, need to have corresponding styling

2021-11-08 09:45 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.scss
> +      font-size: 11px;
10/12?

2021-11-08 09:50 UTC, Dimple16 requested changes
few comments

2021-11-09 07:51 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    console.log(newQueryParams);
remove

2021-11-09 07:54 UTC, Dimple16 requested changes
few comments

2021-11-09 07:54 UTC, Dimple16 commented on src/global.scss
> +  .segment-button-checked {
this class already exists added for the other tabs, can reuse the same

2021-11-15 12:22 UTC, Dimple16 commented on src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.html
> +  <mat-icon *ngIf="isIos" class="fy-modal-top-bar" svgIcon="fy-rectangle"></mat-icon>
use `platform.is('ios')` directly

2021-11-15 12:22 UTC, Dimple16 commented on src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
>    isIos = false;
can remove this

2021-11-15 12:24 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.html
> +    <ion-toolbar mode="{{mode}}">
mode gets applied automatically, any reason for specifying this here?

2021-11-15 12:25 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +    const isIos = this.platform.is('ios');
won't be required

2021-11-15 12:28 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +    }, 15000);
15000?

2021-11-15 12:30 UTC, Dimple16 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +      showBackdrop: true,
these can be reused

2021-11-15 12:30 UTC, Dimple16 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.scss
> +    margin-right: 4px;
combine the margin properties

2021-11-15 12:31 UTC, Dimple16 requested changes
few comments

2021-11-15 20:00 UTC, pradeep8093 commented on src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.html
> +    <mat-date-range-picker #picker></mat-date-range-picker>
share a loom video for this interaction

2021-11-15 20:03 UTC, pradeep8093 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
> +    this.lastSyncedAt = this.convertUTCDateToLocalDate(new Date(this.accountDetails.last_synced_at));
check for existence of this.accountDetails.last_synced_at before calling `this.convertUTCDateToLocalDate` function

2021-11-15 20:31 UTC, pradeep8093 commented on src/app/fyle/personal-cards/personal-cards.page.scss
> +    width: fit-content;
check for compatibility in other devices

2021-11-15 20:34 UTC, pradeep8093 commented
src/app/fyle/personal-cards/personal-cards.page.ts 

would like to review this over call

2021-11-16 03:45 UTC, iravisankar commented on src/app/fyle/personal-cards/personal-cards.page.html
> +    <ion-toolbar mode="{{mode}}">
here we passed segment to fy-header,  we used MD header on that component, so we need to specify the platform here.

2021-11-16 05:41 UTC, iravisankar commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +    }, 15000);
added for failsafe.., if loadstop not triggred even after 15 seconds.

2021-11-16 05:42 UTC, iravisankar commented on src/app/fyle/personal-cards/personal-cards.page.scss
> +    width: fit-content;
tested on both ios and android working fine

2021-11-16 05:46 UTC, iravisankar commented on src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.html
> +    <mat-date-range-picker panelClass="datepickerOne" #picker></mat-date-range-picker>
Preview from date range Picker 
https://www.loom.com/share/17b7cc892f7d417aab93d0d57e791b4b

2021-11-16 14:16 UTC, Dimple16 approved these changes

2021-11-16 14:44 UTC, pradeep8093 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +    const updatedOnDateFilter = selectedFilters.find((filter) => filter.name === 'Updated On');
extract it out to a function

2021-11-16 14:48 UTC, pradeep8093 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +      }
transactionTypeMap = {
  credit: '(btxn_transaction_type.in.(credit))',
  debit:  '(btxn_transaction_type.in.(debit))'
}

newQueryParams.or = transactionTypeMap[this.filters.showCredited.toLowerCase()];

2021-11-16 14:49 UTC, pradeep8093 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +    }
await this.openFilters(filterLabel)

2021-11-18 05:38 UTC, Julias0 commented on src/app/core/services/date.service.ts
> +  getLastDaysRange(numOfDays) {
this method looks unused

2021-11-18 05:39 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            from(this.transactionOutboxService.fileUpload(file.url, file.type))
Ok this would be adding a subscription inside the pipeline inside a map. This is not proper rxjs - lets clean this up into a proper pipeline

2021-11-18 05:41 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        this.newExpenseDataUrls.map((fileObj) => {
this.newExpenseDataUrls = addFileType(this.newExpenseDataUrls);

function addFileType(dataUrls) {
  const dataUrlsCopy = deepClone(dataUrls);
  dataUrlsCopy.forEach(dataUrl => {
  dataUrl.type = this.isPDF(fileObj.type) ? 'pdf' : 'image';  
  });

  return dataUrlsCopy;
}

2021-11-18 05:44 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            from(this.transactionOutboxService.fileUpload(file.url, file.type))
```typescript
return addExpenseAttachments$.pipe(
 switchMap(
   (fileObjs) => forkJoin(
     fileObjs.map(
       file => from(this.transactionOutboxService.fileUpload(file.url, file.type).pipe(
        switchMap((fileObj: any)=> {
                  fileObj.transaction_id = txn.split_group_id;
                  return this.fileService.post(fileObj);
        })
       )
       )
     )
   )
 )
```

2021-11-18 05:48 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            from(this.transactionOutboxService.fileUpload(file.url, file.type))
Now lets extract out the functions from this - 
```typescript
switchMap((fileObj: any)=> {
                  fileObj.transaction_id = txn.split_group_id;
                  return this.fileService.post(fileObj);
        })
        
       switchMap(fileObj => postToFileService(fileObj))
       
       function postToFileService(fileObj, txn) {
         const fileObjCopy = deepClone(fileObj);
         fileObjCopy.transaction_id = txn.split_group_id;
         return this.fileService.post(fileObjCopy);
       }
```

2021-11-18 05:51 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            from(this.transactionOutboxService.fileUpload(file.url, file.type))
If the above is done
```typescript
fileObjs.map(file =>
from(this.transactionOutboxService.fileUpload(file.url, file.type).pipe(
        switchMap((fileObj: any)=> {
                  fileObj.transaction_id = txn.split_group_id;
                  return this.fileService.post(fileObj);
        })
       )
)
```

becomes
``` typescript
fileObjs.map(file =>
from(this.transactionOutboxService.fileUpload(file.url, file.type).pipe(
        switchMap((fileObj: any)=> postToFileService)
       )
 )
```

2021-11-18 05:55 UTC, Julias0 commented on src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses-routing.module.ts
> +    component: PersonalCardsMatchedExpensesPage,
This is done by prettier - this is ok

2021-11-18 06:13 UTC, iravisankar commented on src/app/core/services/date.service.ts
> +  getLastDaysRange(numOfDays) {
Used here on personal-cards.ts 
![image](https://user-images.githubusercontent.com/86199056/142362129-a78f24ae-fbe3-45d4-bee1-d6e4705300ac.png)

2021-11-18 16:02 UTC, Julias0 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +  generateCreatedOnDateParams(newQueryParams) {
a lot of these methods can be extracted out to a service. Check how it is done in tasks

2021-11-18 16:03 UTC, Julias0 commented on src/app/fyle/personal-cards/personal-cards.page.ts
> +      if (data.range === 'This Month') {
extract out function and move to service this whole section

2021-11-23 05:21 UTC, abhishek1234321 requested changes

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +      generatedFilters.createdOn = { name: createdOnDateFilter?.value };
please fix it everywhere

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +        generatedFilters.createdOn.customDateStart = createdOnDateFilter.associatedData?.startDate;
please fix it everywhere

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +  generateSelectedFilters(filter: Filters): SelectedFilters<any>[] {
shouldn't this by like `filters: Filter[]` assuming filter is an array? the convention looks odd

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +  generateCreatedOnCustomDateParams(newQueryParams: any, filters) {
please define data type for filters

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +  generateUpdatedOnDateParams(newQueryParams, filters) {
is this not similar to CreatedOn method? could we pass the dynamic and reuse the same method?

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +  generateUpdatedOnCustomDateParams(newQueryParams: any, filters) {
is this not similar to `generateCreatedOnCustomDateParams` could we not pass a key and reuse?

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +  generateFilterPills(filter: Filters) {
would it be a single filter or filters? convention is incorrect

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +  generateCreatedOnDateFilterPills(filter, filterPills: FilterPill[]) {
this could also be reused, IMHO

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/core/services/personal-cards.service.ts
> +        type: 'string',
what is this about?

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          ...this.snackbarProperties.setSnackbarProperties('success', { message: 'Expense created successfully.' }),
is this change ok? especially if someone uses the add expense directly?

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.saveExpenseLoader = true;
where is this unset?

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>    uploadAttachments(txn) {
please define type for each parameter

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  addFileType(dataUrls) {
please define type for each parameter, please fix it everywhere

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    dataUrlsCopy.forEach((dataUrl) => {
shouldn't this be a map?

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  isPDF(type) {
this should be a service method

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.html
> +          [loadingText]="'Un matching'"
`Unmatching` this is a single word

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
> +  convertUTCDateToLocalDate(date) {
shouldn't this be in DateService?

2021-11-23 05:21 UTC, abhishek1234321 commented on src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
> +  selectedCard;
define type?

2021-11-23 20:42 UTC, iravisankar commented on src/app/core/services/personal-cards.service.ts
> +        type: 'string',
for showing transactions type on pills

2021-11-24 09:02 UTC, abhishek1234321 approved these changes

2021-11-24 18:21 UTC, merged