Fyle 1tz94ty : Fixed list element does not have right spacing inside pop ups
fylein/fyle-mobile-app2 pull request #736
Opened 2021-11-09 09:44 UTC by siddharth0-0

![image](https://user-images.githubusercontent.com/66034160/140899653-a4564b33-40b6-4c88-9fee-2cf9666ab887.png)

![image](https://user-images.githubusercontent.com/66034160/140899729-672ade71-a67c-4fdb-adb2-788b9cdad708.png)

2021-11-09 10:16 UTC, Dimple16 approved these changes

2021-11-10 05:57 UTC, Dimple16 requested changes
include the changes of text alignment

2021-11-10 08:25 UTC, siddharth0-0 commented
![image](https://user-images.githubusercontent.com/66034160/141076833-5eb96962-b29e-4428-b8c2-c261bf8b4bd2.png)

2021-11-11 08:15 UTC, Dimple16 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.scss
> +    margin: 0 16px 0 16px;
`margin: 0 16px;` should work

2021-11-11 08:16 UTC, Dimple16 requested changes
few comments

2021-11-11 08:16 UTC, Dimple16 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.scss
> +    margin: 0 16px 0 16px;
refer this - https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

2021-11-15 12:08 UTC, Dimple16 approved these changes

2021-11-15 13:07 UTC, Julias0 approved these changes

2021-11-16 06:17 UTC, merged