Fyle 1uvx789 : Fixed change top Information Box to Alert Box in expense/mileage/per diem pages
fylein/fyle-mobile-app2 pull request #759
Opened 2021-11-19 09:47 UTC by siddharth0-0

![Screenshot_20211119-150631_Fyle Staging](https://user-images.githubusercontent.com/66034160/142601943-e0146a17-3257-401b-8afd-1d9736344ffd.jpg)

![image](https://user-images.githubusercontent.com/66034160/142601354-206ee783-fc9d-4f3e-b162-7c8843e25364.png)

2021-11-19 10:23 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +              <mat-icon class="add-edit-expense--critical-policy-icon" svgIcon="fy-info"></mat-icon>
this is not a critical-policy-icon, can reuse the same class of split expense

2021-11-19 10:23 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    border: 1px solid #dfdfe2;
use color variable

2021-11-19 10:23 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +  &--critical-policy-icon {
use the same class used for split expense info

2021-11-19 10:24 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
> +  &--critical-policy-icon {
same as above

2021-11-19 10:24 UTC, Dimple16 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.scss
> +  &--critical-policy-icon {
same as above

2021-11-19 10:24 UTC, Dimple16 requested changes
few comments

2021-11-22 10:43 UTC, Dimple16 approved these changes

2021-11-29 17:40 UTC, Julias0 approved these changes

2021-11-30 04:48 UTC, merged