Switch-org page: Add back btn, search animation, make search sticky, fix shimmers and other minor fixes
fylein/fyle-mobile-app2 pull request #761
Opened 2021-11-22 07:04 UTC by yksolanki9

2021-11-30 07:43 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.html
> +        <ng-container *ngIf="orgs.length > 1">
are we showing the zero state when `orgs.length > 1` ?

2021-11-30 07:44 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.scss
> +    position: sticky;
need to verify this on iOS

2021-11-30 07:45 UTC, Dimple16 requested changes
few comments

2021-11-30 10:24 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.html
> +        <ng-container *ngIf="orgs.length > 1">
Loom video: https://www.loom.com/share/c1a71588cced4975b15ff7c06890bcdd
- When a user logs in, we redirect them to the switch org page straight away. Now, if the user is part of only one org, we show a loader on top of the switch org page and user is logged into that org.
- Since the user is not part of any other org, `filteredOrgs` is an empty array and so a zero state will be shown
- This check hides the zero state if user is part of only one org.

2021-11-30 10:25 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.scss
> +    position: sticky;
Will share ipa in a while. Thanks:)

2021-11-30 13:01 UTC, Dimple16 approved these changes

2021-11-30 17:31 UTC, abhishek1234321 approved these changes

2021-11-30 17:31 UTC, abhishek1234321 commented on src/app/auth/switch-org/switch-org.page.html
> +          <div class="text-ellipsis switch-org__content-container__content__sub-title">
why is this needed `text-ellipsis`?

2021-11-30 17:31 UTC, abhishek1234321 commented on src/app/auth/switch-org/switch-org.page.html
> +    <div #searchDiv class="switch-org__content-container__block switch-org__content-container__search-block">
#search is enough IMHO

2021-11-30 17:31 UTC, abhishek1234321 commented on src/app/auth/switch-org/switch-org.page.html
> +              (click)="clearSearchInput()"
clearSearch or resetSearch or reset?

2021-12-02 05:47 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.html
> +    <div #searchDiv class="switch-org__content-container__block switch-org__content-container__search-block">
Done

2021-12-02 05:49 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.html
> +              (click)="clearSearchInput()"
Done

2021-12-02 06:24 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.html
> +          <div class="text-ellipsis switch-org__content-container__content__sub-title">
- The issue is that for smaller devices (Iphone 5), the text - `Select the organization you want to switch to` continues in the next line.
-  And since we are putting search bar on top, overflown text is visible (ss1 below).
- Since it works fine on other devices Moto G4 and above, I went with hiding the overflowing text with ellipsis(ss2 below)
- Other solution will be to change height of searchbar based on the height of text content.

![localhost_8100_auth_sign_in(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/39493102/144368307-15955ce9-f309-4acd-b13e-c3bc167b9e20.png)

![localhost_8100_auth_sign_in(iPhone 5_SE)](https://user-images.githubusercontent.com/39493102/144368005-75d201e2-0561-4a60-af27-f92f40898486.png)

2021-12-08 08:09 UTC, merged