Fyle 1v1hkjc : Fixed 'Please add a project ' alignment in Expenses
fylein/fyle-mobile-app2 pull request #764
Opened 2021-11-23 10:24 UTC by siddharth0-0

![image](https://user-images.githubusercontent.com/66034160/143007513-1088a82a-8a1e-4d87-bf4e-3de844dd793b.png)

![image](https://user-images.githubusercontent.com/66034160/143007596-38e3dbe0-a742-42a2-8dfa-b359467982cf.png)

2021-11-23 11:27 UTC, Dimple16 commented
Is this tested for the below cases:
- When projects are assigned 
- When projects are not assigned but it is mandatory 
- When billable is checked and not checked
- Project field width should change based on whether billable is present or not

2021-11-23 11:27 UTC, Dimple16 requested changes
verify all the cases

2021-11-24 07:41 UTC, siddharth0-0 commented
> Is this tested for the below cases:
> 
> * When projects are assigned  - Tested and able to save the expense
> * When projects are not assigned but it is mandatory - Tested and message is hidden in this case
> * When billable is checked and not checked - Tested and able to save expense
> * Project field width should change based on whether billable is present or not - Tested and looks fine

2021-11-24 09:40 UTC, Dimple16 approved these changes

2021-11-29 05:46 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
> +                        [ngClass]="{'add-edit-mileage--no-project': !fg.controls.project.value}"
why change this condition?

2021-11-29 06:31 UTC, siddharth0-0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
> +                        [ngClass]="{'add-edit-mileage--no-project': !fg.controls.project.value}"
In Css  --no-project is set to 'margin-right: 0px !important' 
Earlier when was selecting project as 'None' it was giving a certain margin which was making select dropdown look short 

![InkedScreenshot_20211129-115502_Fyle_LI](https://user-images.githubusercontent.com/66034160/143819242-19a7c443-4f48-4e95-8ae1-c4454abf7c3b.jpg)

2021-11-29 06:52 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
> +                        [ngClass]="{'add-edit-mileage--no-project': !fg.controls.project.value}"
but this css class will still be added under certain conditions right? Will it look ok in those cases?

2021-11-29 07:05 UTC, siddharth0-0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
> +                        [ngClass]="{'add-edit-mileage--no-project': !fg.controls.project.value}"
Yes, --no-project will only be used under when the project value is none.
This is the only time when this --no-project class will be used, In other condition when project value is !Null there will be an checkbox option on right.
![image](https://user-images.githubusercontent.com/66034160/143822646-638e9ec5-f263-4295-a0f8-a28686a05ec9.png)
In this condition the select dropdown will have 'margin-right: 20px;'

2021-11-29 17:41 UTC, Julias0 approved these changes

2021-11-30 06:16 UTC, merged