Fyle 1vcx46z : Fixed change the split expense success pop up to success toast message
fylein/fyle-mobile-app2 pull request #765
Opened 2021-11-29 12:19 UTC by siddharth0-0

![Screenshot 2021-11-27 170159](https://user-images.githubusercontent.com/66034160/143866801-11a325a5-4089-4188-b855-4d88dc967aff.png)

![image](https://user-images.githubusercontent.com/66034160/143866982-05edacdf-7852-4627-bff4-6fc47861b7f6.png)

2021-11-30 07:39 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +              const message = 'The expense has split successfully';
`Your expense was split successfully`

2021-11-30 07:39 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +              const toastMessageData = {
Add a screenshot/recording for the failure case

2021-11-30 07:40 UTC, Dimple16 requested changes
few comments

2021-12-02 05:13 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +                message: 'Seems to be a stormy day. You should try this after sometime',
`Seems to be a stormy day. Please try again after sometime`

2021-12-02 05:14 UTC, Dimple16 commented
the error toast should also be above the bottom nav (above the pink camera) it shouldn't hide the bottom sections. Can we fix this @siddharth0-0 ?

2021-12-02 05:15 UTC, Dimple16 requested changes
few comments

2021-12-06 08:35 UTC, Dimple16 approved these changes

2021-12-09 05:48 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +                this.router.navigate(['/', 'enterprise', 'my_expenses']);
Shouldnt this open up the split page again instead of opening my expenses?

2021-12-09 11:13 UTC, Dimple16 approved these changes

2021-12-09 13:28 UTC, siddharth0-0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +                this.router.navigate(['/', 'enterprise', 'my_expenses']);
Removed the retry option as it was leading to same route as default route `my_expense`

2021-12-10 11:20 UTC, Julias0 approved these changes

2021-12-10 19:29 UTC, merged