Fyle 1vcwg0y : Fixed Project Save is not consistent in Expenses on condition : 'When projects are not assigned but it is mandatory '
fylein/fyle-mobile-app2 pull request #767
Opened 2021-11-30 13:44 UTC by siddharth0-0

No UI Changes

2021-12-02 05:24 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              } else if (txnFieldKey === 'project_id') {
mention the 4 cases tested we discussed about, just to make sure this handles every case

2021-12-02 05:25 UTC, Dimple16 requested changes
add test cases

2021-12-03 07:01 UTC, siddharth0-0 commented
Test cases tested : 

![image](https://user-images.githubusercontent.com/66034160/144559510-bd42aa75-3f3f-41a6-9850-2521db9d722f.png)

2021-12-08 14:17 UTC, Dimple16 approved these changes

2021-12-10 11:43 UTC, Julias0 approved these changes

2021-12-14 10:37 UTC, merged