Sidemenu: Add sidemenu options, dropdown, update icons and minor fixes
fylein/fyle-mobile-app2 pull request #768
Opened 2021-11-30 14:32 UTC by yksolanki9

Loom video: https://www.loom.com/share/a172db6c55dc463e84b7bba577bc811e

2021-11-30 14:34 UTC, yksolanki9 commented on src/app/app.component.ts
> +import { Component, OnInit, EventEmitter, NgZone, ElementRef, ViewChild } from '@angular/core';
Ignore this file for now. Needs refactoring

2021-11-30 14:40 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.ts
> +// type SideMenuItem = {
Ignore this commented code.
Any `undefined` or `any` data types will be handled in refactoring pr

2021-11-30 14:40 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.html
>  <!-- <ion-content class="sidemenu--content">
Ignore from here below

2021-11-30 14:41 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +import { Component, OnInit, EventEmitter } from '@angular/core';
Ignore this file

2021-12-02 05:17 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.scss
> +      color: $black-light;
as this is used in multiple places, should we add it to global?

2021-12-02 05:19 UTC, Dimple16 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.scss
> +    font-size: 14px;
isn't this by default?

2021-12-02 05:19 UTC, Dimple16 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.scss
> +      padding-left: 16px;
`padding: 4px 0 0 16px`

2021-12-02 05:21 UTC, Dimple16 requested changes
few comments

2021-12-02 05:32 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.scss
> +    font-size: 14px;
No it defaults to 20px

2021-12-03 13:49 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.scss
> +      padding-left: 16px;
Done

2021-12-03 13:53 UTC, yksolanki9 commented on src/app/fyle/view-expense/view-expense.page.scss
> +      color: $black-light;
Is it fine if I add it as a task in tech debt since there are a lot of repeated classes and it is out of scope of this pr? Shishira had suggested creating a common css file for this

2021-12-06 07:30 UTC, yksolanki9 commented on src/app/fyle/view-expense/view-expense.page.scss
> +      color: $black-light;
Tracking here: https://app.clickup.com/t/1ttbrrp

2021-12-06 08:16 UTC, Dimple16 approved these changes

2021-12-08 06:02 UTC, Julias0 commented on src/app/app.component.ts
> +  // openHelp() {
avoid dead code. Remove commented code

2021-12-08 06:02 UTC, Julias0 commented on src/app/app.component.ts
> +  // }
There is too much commented code

2021-12-08 06:19 UTC, merged