Prior date fix
fylein/fyle-mobile-app2 pull request #780
Opened 2021-12-08 08:47 UTC by iravisankar

2021-12-08 09:18 UTC, abhishek1234321 requested changes

2021-12-08 09:18 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                etxn.tx.txn_dt = etxn.tx.extracted_data.date.slice(0, -1);
not understanding this, how would this be converted to a date object?

2021-12-08 11:10 UTC, Julias0 approved these changes

2021-12-09 11:24 UTC, abhishek1234321 approved these changes

2021-12-09 11:25 UTC, merged