Fixed : Split expenses should be added to the report if the report is selected in an expense form
fylein/fyle-mobile-app2 pull request #781
Opened 2021-12-08 11:11 UTC by siddharth0-0

No visual changes

2021-12-08 14:17 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +  saveToReports(data) {
`addToReport`

2021-12-08 14:19 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +        this.saveToReports(data);
shouldn't we call this only when report ID is present?

2021-12-08 14:20 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +      return this.reportService.addTransactions(reportId, txnIds).subscribe(noop);
let us add a toast message here as to how many expenses got successfully added to report

2021-12-08 14:20 UTC, Dimple16 requested changes
few comments

2021-12-16 13:16 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +  splitExpenseTxn: any;
let us avoid using `any`

2021-12-16 13:17 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +        const message = 'Your expense was split successfully. But no Expense was added to report.';
I guess showing a green toast here would mislead, can we show the dark blue toast for this case?

2021-12-16 13:17 UTC, Dimple16 requested changes
few comments

2021-12-22 08:21 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +  completeTxnIds;
is this a list?

2021-12-22 08:22 UTC, Dimple16 approved these changes

2021-12-22 13:08 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +      if (this.completeTxnIds.length === this.splitExpenseTxn.length) {
the structure of each if condition is duplicated, try to cut down the duplication here and make this simpler too.

2021-12-22 13:10 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +    return this.reportService.addTransactions(reportId, this.completeTxnIds).subscribe(noop);
dont subscribe to observables inside like this. Make this a separate switch map

switchMap(data => {
  if (this.reportId) {
    return this.addToReport(data).pipe(map(_=> data))
  } else {
    return of(data);
  }
})

2021-12-28 12:16 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +          .filter((tx) => {
.filter((tx) => tx.state === 'COMPLETE')

2021-12-28 12:17 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +  toastWithCTA(toastMessage) {
you can combine this and the below one by adding a boolean - withCTA: boolean parameter

2021-12-28 12:18 UTC, Julias0 approved these changes

2021-12-28 12:48 UTC, merged