New Advances Design
fylein/fyle-mobile-app2 pull request #788
Opened 2021-12-16 12:19 UTC by siddharth0-0

![image](https://user-images.githubusercontent.com/66034160/146370761-6c530695-679a-415e-9585-53c9a64e97a1.png)
![1](https://user-images.githubusercontent.com/66034160/146370782-f6a5c5b0-450d-4d31-b64f-096319743e20.png)

![image](https://user-images.githubusercontent.com/66034160/146370841-a2daf7dc-33e0-4775-8e9d-0c0af5b9e325.png)
![2](https://user-images.githubusercontent.com/66034160/146370875-150fa0cb-7266-484f-b02b-9c977b7d80aa.png)

2021-12-16 13:11 UTC, Dimple16 commented on src/app/fyle/my-advances/my-advances-card/my-advances-card.component.scss
> +@import '../../../../theme/colors.scss';
import at the top

2021-12-16 13:12 UTC, Dimple16 commented on src/app/fyle/my-advances/my-advances-card/my-advances-card.component.scss
> +    font-size: 14px;
check if 14px is by default

2021-12-16 13:13 UTC, Dimple16 commented on src/app/fyle/my-advances/my-advances-card/my-advances-card.component.scss
>      color: #fff;
use `$pure-white`

2021-12-16 13:13 UTC, Dimple16 commented on src/app/fyle/team-advance/team-adv-card/team-adv-card.component.html
> +  {{ advanceRequest.areq_created_at | date: 'EEEE' }},{{ advanceRequest.areq_created_at | date: 'MMM dd, yyyy' }}
same as above

2021-12-16 13:14 UTC, Dimple16 commented on src/app/fyle/team-advance/team-adv-card/team-adv-card.component.html
> +          <span>Approved on {{ advanceRequest.areq_approved_at | date: 'MMM dd, yyyy' }}</span>
can you add a screenshot with the approved on screen?

2021-12-16 13:14 UTC, Dimple16 commented on src/app/fyle/team-advance/team-adv-card/team-adv-card.component.scss
> +@import '../../../../theme/colors.scss';
same as above

2021-12-16 13:14 UTC, Dimple16 commented on src/app/fyle/team-advance/team-adv-card/team-adv-card.component.ts
> +    console.log('sam', this.advanceRequest);
remove

2021-12-16 13:15 UTC, Dimple16 requested changes
added comments

2021-12-16 16:19 UTC, Dimple16 approved these changes

2021-12-20 06:00 UTC, Julias0 commented on src/app/fyle/team-advance/team-adv-card/team-adv-card.component.ts
> +      (this.advanceRequest && new Date(this.advanceRequest.areq_created_at).toDateString()) !==
use moment to do this.

2021-12-20 11:45 UTC, Julias0 commented on src/app/fyle/my-advances/my-advances-card/my-advances-card.component.ts
> +      (this.advanceRequest && moment(new Date(this.advanceRequest.created_at)).format('ddd MMM DD YYYY')) !==
arrey na na use moment to compare the dates. Dont convert to string and compare

2021-12-20 11:45 UTC, Julias0 commented on src/app/fyle/team-advance/team-adv-card/team-adv-card.component.ts
> +      (this.prevDate && moment(new Date(this.prevDate)).format('ddd MMM DD YYYY'));
same comment as above

2021-12-20 11:45 UTC, Julias0 approved these changes

2021-12-20 13:51 UTC, merged