Add resend verification link page
fylein/fyle-mobile-app2 pull request #789
Opened 2021-12-16 14:31 UTC by yksolanki9

2021-12-16 15:24 UTC, Dimple16 commented on src/app/shared/components/send-email/send-email.component.html
> +      <div class="send-email__form" *ngIf="pageState === pageStates.failure">
test the failure case too

2021-12-16 15:25 UTC, Dimple16 commented on src/app/shared/components/send-email/send-email.component.ts
> +  @Input() content2: string;
can we name this differently? content and content2 is confusing

2021-12-16 15:26 UTC, Dimple16 commented on src/app/shared/components/send-email/send-email.component.ts
> +enum PageState {
can use the new model created?

2021-12-16 15:26 UTC, Dimple16 requested changes
few comments, also, remove the empty file

2021-12-17 06:00 UTC, yksolanki9 commented on src/app/shared/components/send-email/send-email.component.html
> +      <div class="send-email__form" *ngIf="pageState === pageStates.failure">
Already tested

2021-12-17 06:02 UTC, yksolanki9 commented on src/app/shared/components/send-email/send-email.component.ts
> +enum PageState {
Done

2021-12-17 06:11 UTC, yksolanki9 commented on src/app/shared/components/send-email/send-email.component.ts
> +  @Input() content2: string;
Done

2021-12-17 07:28 UTC, Dimple16 approved these changes

2021-12-20 05:37 UTC, Julias0 commented on src/app/core/models/page-state.model.ts
> +export enum PageState {
filename should be `page-state.enum.ts`

2021-12-20 05:38 UTC, Julias0 commented on src/app/auth/pending-verification/pending-verification.page.ts
> +  currentPageState: PageState = PageState.notSent;
set this inside ionViewWillEnter. Otherwise the 2nd time this page is opened, it will maintain the old state

2021-12-20 05:39 UTC, Julias0 commented on src/app/auth/reset-password/reset-password.page.html
> +  [pageState]="currentPageState"
page state is very specific to send email component. Better to name it like sendEmailPageState or something

2021-12-20 05:40 UTC, Julias0 commented on src/app/core/models/page-state.model.ts
> +export enum PageState {
Also this is not a core model but a component specific one

2021-12-20 05:41 UTC, Julias0 commented on src/app/core/services/router-auth.service.ts
> +      email: email?.trim().toLowerCase(),
should emails be lowercased before sending? Can you check some best practices around this?

2021-12-20 05:41 UTC, Julias0 commented on src/app/shared/components/send-email/send-email.component.html
> +      <ion-grid class="send-email__header text-center">
send-email__header - this is not BEM

`send-email--header` this is the block element configuration

2021-12-20 05:41 UTC, Julias0 commented on src/app/shared/components/send-email/send-email.component.html
> +            <img class="send-email__header__logo" src="../../../../assets/svg/logo-white.svg" alt="fyle-logo" />
send-email--header-logo

2021-12-20 05:42 UTC, Julias0 commented on src/app/shared/components/send-email/send-email.component.html
> +      <div class="send-email__form" *ngIf="pageState === pageStates.notSent">
follow the BEM convention for this please

2021-12-20 05:42 UTC, Julias0 requested changes
Have added a few comments

2021-12-20 05:55 UTC, yksolanki9 commented on src/app/shared/components/send-email/send-email.component.html
> +      <ion-grid class="send-email__header text-center">
Discussed

2021-12-20 05:55 UTC, yksolanki9 commented on src/app/shared/components/send-email/send-email.component.html
> +      <div class="send-email__form" *ngIf="pageState === pageStates.notSent">
Discussed

2021-12-20 05:55 UTC, yksolanki9 commented on src/app/shared/components/send-email/send-email.component.html
> +            <img class="send-email__header__logo" src="../../../../assets/svg/logo-white.svg" alt="fyle-logo" />
Discussed

2021-12-20 07:47 UTC, yksolanki9 commented on src/app/core/models/page-state.model.ts
> +export enum PageState {
It is used by `pending-verification.page`, `reset-password.page` and shared component `send-email`

2021-12-20 08:21 UTC, yksolanki9 commented on src/app/core/services/router-auth.service.ts
> +      email: email?.trim().toLowerCase(),
This is done for sake of consistency. [This](https://ux.stackexchange.com/questions/16848/if-your-login-is-an-email-should-you-canonicalize-lower-case-it) stackexchange answer suggests that that we should lowercase it before storing to avoid duplicates, which ig we are not doing here so it shouldn't matter.

2021-12-20 08:54 UTC, yksolanki9 commented on src/app/auth/pending-verification/pending-verification.page.ts
> +  currentPageState: PageState = PageState.notSent;
Done

2021-12-20 08:55 UTC, yksolanki9 commented on src/app/auth/reset-password/reset-password.page.html
> +  [pageState]="currentPageState"
Done

2021-12-20 08:55 UTC, yksolanki9 commented on src/app/core/models/page-state.model.ts
> +export enum PageState {
File name changed

2021-12-20 11:44 UTC, Julias0 approved these changes

2021-12-20 12:15 UTC, merged